/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Kapsyen Tertutup",
    "clcpatcc": "ATSC/52 bahagian-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Pembayang",
    "meta": "Metadata",
    "metamebx": "Metadata Bermasa",
    "musimusi": "Muzik",
    "muxx": "Muxed",
    "obje": "Objek QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Sari Kata",
    "sbtldrmt": "Sari Kata",
    "sbtltx3g": "Sari Kata",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Kulit",
    "skinskcr": "Kulit",
    "skinskdr": "Kulit",
    "soun": "Bunyi",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (disulitkan)",
    "sounpaac": "AAC (dilindungi)",
    "sounpac3": "AC-3 Dolby Digital (dilindungi)",
    "sounpach": "HE-AACv1 (dilindungi)",
    "sounpacp": "HE-AACv2 (dilindungi)",
    "sounpc+3": "Dolby Atmos (dilindungi)",
    "sounpec3": "EC-3 Dolby Digital+ (dilindungi)",
    "sounqaac": "AAC (dilindungi, MP4 terserpih)",
    "sounqac3": "AC-3 Dolby Digital (dilindungi, MP4 terserpih)",
    "sounqach": "HE-AACv1 (dilindungi, MP4 terserpih)",
    "sounqacp": "HE-AACv2 (dilindungi, MP4 terserpih)",
    "sounqc+3": "Dolby Atmos (dilindungi, MP4 terserpih)",
    "sounqec3": "EC-3 Dolby Digital+ (dilindungi, MP4 terserpih)",
    "sounqlac": "Apple Lossless (dilindungi, MP4 terserpih)",
    "sounvdva": "DV",
    "sounzaac": "AAC (dilindungi, strim pengangkutan)",
    "sounzac3": "AC-3 Dolby Digital (dilindungi, strim pengangkutan)",
    "sounzach": "HE-AACv1 (dilindungi, strim pengangkutan)",
    "sounzacp": "HE-AACv2 (dilindungi, strim pengangkutan)",
    "sounzc+3": "Dolby Atmos (dilindungi, strim pengangkutan)",
    "sounzec3": "EC-3 Dolby Digital+ (dilindungi, strim pengangkutan)",
    "sounzlac": "Apple Lossless (dilindungi, strim pengangkutan)",
    "sprt": "Sprite",
    "strm": "Penstriman",
    "strmrtsp": "Penstriman",
    "text": "Teks",
    "texttext": "Teks QuickTime",
    "texttx3g": "Teks 3GPP",
    "tmcd": "Kod Masa",
    "tmcdtmcd": "Kod Masa",
    "tmet": "Metadata Bermasa",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Warna Diindeks 1 bit Dinyahmampatkan",
    "vide2": "Warna Diindeks 2 bit Dinyahmampatkan",
    "vide2vuy": "Komponen Y'CbCr 8 bit tersusun 4:2:2 Cb Y'0 Cr Y'1",
    "vide4": "Warna Diindeks 4 bit Dinyahmampatkan",
    "vide8": "Warna Diindeks 8 bit Dinyahmampatkan",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555 16 bit Dinyahmampatkan (Big Endian)",
    "vide24": "RGB 24 bit Dinyahmampatkan",
    "vide24BG": "BGR 24 bit Dinyahmampatkan",
    "vide32": "ARGB 32 bit Dinyahmampatkan",
    "vide33": "Skala Kelabu 1 bit Dinyahmampatkan",
    "vide34": "Skala Kelabu 2 bit Dinyahmampatkan",
    "vide36": "Skala Kelabu 4 bit Dinyahmampatkan",
    "vide40": "Skala Kelabu 8 bit Dinyahmampatkan",
    "vide5551": "RGB 5551 16 bit Dinyahmampatkan (Little Endian)",
    "videa2vy": "Komponen Dua Satah Y'CbCr,A 8 bit 4:2:2,4",
    "videABGR": "ABGR 32 bit Dinyahmampatkan",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proksi",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Set Parameter dalam Strim Bit)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Skala Kelabu 16 bit Dinyahmampatkan",
    "videb32a": "AlphaGray 32 bit Dinyahmampatkan",
    "videb48r": "RGB 48 bit Dinyahmampatkan",
    "videb64a": "ARGB 64 bit Dinyahmampatkan",
    "videB565": "RGB 565 16 bit Dinyahmampatkan (Big Endian)",
    "videBGRA": "BGRA 32 bit Dinyahmampatkan",
    "videbhiv": "bhiv",
    "videblur": "Penapis Konvolusi",
    "videcdh1": "Dolby Vision HEVC (disulitkan)",
    "videclou": "Awan",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Pudar Silang",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Penapis Konvolusi",
    "videfire": "Api",
    "videfmns": "Penapis Bunyi Filem",
    "videgenk": "Penapis Konvolusi",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "HEVC (Set Parameter dalam Strim Bit)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Foto - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Pratonton)",
    "videkpcd": "Foto CD",
    "videL555": "RGB 555 16 bit Dinyahmampatkan (Little Endian)",
    "videL565": "RGB 565 16 bit Dinyahmampatkan (Little Endian)",
    "vidematt": "Sapu Gradien",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Video MPEG-1",
    "videmp2v": "Video MPEG-2",
    "videmp4v": "Video MPEG-4",
    "videmplo": "Meledak",
    "videmuxa": "HEVC dengan Alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Tidak Diketahui",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (dilindungi, MP4 terserpih)",
    "vider210": "RGB 10 bit Dinyahmampatkan",
    "vider408": "Komponen Y'CbCrA 8 bit tersusun 4:4:4:4 A Y' Cb Cr",
    "videRGBA": "RGBA 32 bit Dinyahmampatkan",
    "viderle ": "Animasi",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Penapis Konvolusi",
    "videslid": "Push",
    "videsmc ": "Grafik",
    "videsmpt": "Sapu",
    "videsolr": "Penapis Imbangan Warna",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Penapis Imbangan Warna",
    "videtrav": "Matte Bergerak",
    "videv210": "Komponen Y'CbCr 10 bit 4:2:2",
    "videv216": "Komponen Y'CbCr 10,12,14,16 bit 4:2:2",
    "videv308": "Komponen Y'CbCr 8 bit 4:4:4",
    "videv408": "Komponen Y'CbCrA 8 bit tersusun 4:4:4:4 Cb Y' Cr A",
    "videv410": "Komponen Y'CbCr 10 bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10 bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12 bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10 bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8 bit",
    "videxfia": "XF-AVC Intra 4:2:2 10 bit",
    "videxplo": "Meledak",
    "videy420": "Komponen Tiga Satah Y'CbCr 8 bit 4:2:0",
    "videyuvs": "Komponen Y'CbCr 8 bit tersusun 4:2:2 Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
