/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "クローズドキャプション",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "ヒント",
    "meta": "メタデータ",
    "metamebx": "時間メタデータ",
    "musimusi": "ミュージック",
    "muxx": "多重",
    "obje": "QTVR Object",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VRパノラマ",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "字幕",
    "sbtldrmt": "字幕",
    "sbtltx3g": "字幕",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "サウンド",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless（暗号化）",
    "sounpaac": "AAC（保護）",
    "sounpac3": "AC-3ドルビーデジタル（保護）",
    "sounpach": "HE-AACv1（保護）",
    "sounpacp": "HE-AACv2（保護）",
    "sounpc+3": "ドルビーアトモス（保護）",
    "sounpec3": "EC-3ドルビーデジタル+（保護）",
    "sounqaac": "AAC（保護、断片化したMP4）",
    "sounqac3": "AC-3ドルビーデジタル（保護、断片化したMP4）",
    "sounqach": "HE-AACv1（保護、断片化したMP4）",
    "sounqacp": "HE-AACv2（保護、断片化したMP4）",
    "sounqc+3": "ドルビーアトモス（保護、断片化したMP4）",
    "sounqec3": "EC-3ドルビーデジタル+（保護、断片化したMP4）",
    "sounqlac": "Apple Lossless（保護、断片化したMP4）",
    "sounvdva": "DV",
    "sounzaac": "AAC（保護、トランスポートストリーム）",
    "sounzac3": "AC-3ドルビーデジタル（保護、トランスポートストリーム）",
    "sounzach": "HE-AACv1（保護、トランスポートストリーム）",
    "sounzacp": "HE-AACv2（保護、トランスポートストリーム）",
    "sounzc+3": "ドルビーアトモス（保護、トランスポートストリーム）",
    "sounzec3": "EC-3ドルビーデジタル+（保護、トランスポートストリーム）",
    "sounzlac": "Apple Lossless（保護、トランスポートストリーム）",
    "sprt": "スプライト",
    "strm": "ストリーミング",
    "strmrtsp": "ストリーミング",
    "text": "テキスト",
    "texttext": "QuickTime Text",
    "texttx3g": "3GPP Text",
    "tmcd": "タイムコード",
    "tmcdtmcd": "タイムコード",
    "tmet": "時間メタデータ",
    "twen": "Tween",
    "vide": "ビデオ",
    "vide1": "非圧縮1ビットインデックス付きカラー",
    "vide2": "非圧縮2ビットインデックス付きカラー",
    "vide2vuy": "コンポーネントY'CbCr 8ビット4:2:2、順序Cb Y'0 Cr Y'1",
    "vide4": "非圧縮4ビットインデックス付きカラー",
    "vide8": "非圧縮8ビットインデックス付きカラー",
    "vide8BPS": "Planar RGB",
    "vide16": "非圧縮16ビットRGB 555（ビッグエンディアン）",
    "vide24": "非圧縮24ビットRGB",
    "vide24BG": "非圧縮24ビットBGR",
    "vide32": "非圧縮32ビットARGB",
    "vide33": "非圧縮1ビットグレイスケール",
    "vide34": "非圧縮2ビットグレイスケール",
    "vide36": "非圧縮4ビットグレイスケール",
    "vide40": "非圧縮8ビットグレイスケール",
    "vide5551": "非圧縮16ビットRGB 5551（リトルエンディアン）",
    "videa2vy": "2面コンポーネントY'CbCr,A 8ビット4:2:2,4",
    "videABGR": "非圧縮32ビットABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 プロキシ",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264（パラメータセットはビットストリームに内包）",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "モーションJPEG AVR",
    "videb16g": "非圧縮16ビットグレイスケール",
    "videb32a": "非圧縮32ビットアルファグレイ",
    "videb48r": "非圧縮48ビットRGB",
    "videb64a": "非圧縮64ビットARGB",
    "videB565": "非圧縮16ビットRGB 565（ビッグエンディアン）",
    "videBGRA": "非圧縮32ビットBGRA",
    "videbhiv": "bhiv",
    "videblur": "畳み込みフィルタ",
    "videcdh1": "ドルビービジョンHEVC（暗号化）",
    "videclou": "雲",
    "videcvid": "シネパック",
    "videdmb1": "モーションJPEG OpenDML",
    "videdrmi": "AVC0メディア",
    "videdslv": "クロスフェード",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "ドルビービジョンHEVC",
    "videdvh2": "DVCPRO HD（1080p25）",
    "videdvh3": "DVCPRO HD（1080p30）",
    "videdvh5": "DVCPRO HD（1080i50）",
    "videdvh6": "DVCPRO HD（1080i60）",
    "videdvhp": "DVCPRO HD（720p60）",
    "videdvhq": "DVCPRO HD（720p50）",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "畳み込みフィルタ",
    "videfire": "炎",
    "videfmns": "フィルムノイズフィルタ",
    "videgenk": "畳み込みフィルタ",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10ビット 4:2:2",
    "videhev1": "HEVC（パラメータセットはビットストリームに内包）",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ Video 5.1",
    "videjpeg": "フォト - JPEG",
    "videJvt3": "Apple H.264/AVCビデオ（プレビュー）",
    "videkpcd": "Photo CD",
    "videL555": "非圧縮16ビットRGB 555（リトルエンディアン）",
    "videL565": "非圧縮16ビットRGB 565（リトルエンディアン）",
    "vidematt": "グラデーションワイプ",
    "videmjp2": "JPEG 2000",
    "videmjpa": "モーションJPEG A",
    "videmjpb": "モーションJPEG B",
    "videmp1v": "MPEG-1ビデオ",
    "videmp2v": "MPEG-2ビデオ",
    "videmp4v": "MPEG-4ビデオ",
    "videmplo": "収縮",
    "videmuxa": "HEVC（アルファ値指定）",
    "videmx3n": "MPEG IMX 525/60（30 Mbps）",
    "videmx3p": "MPEG IMX 625/50（30 Mbps）",
    "videmx4n": "MPEG IMX 525/60（40 Mbps）",
    "videmx4p": "MPEG IMX 625/50（40 Mbps）",
    "videmx5n": "MPEG IMX 525/60（50 Mbps）",
    "videmx5p": "MPEG IMX 625/50（50 Mbps）",
    "VideoDynamicRangeDolbyVision": "ドルビービジョン5",
    "VideoDynamicRangeDolbyVision8p4": "ドルビービジョン8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "不明",
    "videpng ": "PNG",
    "videpush": "押し出し",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "ドルビービジョンHEVC（保護、断片化したMP4）",
    "vider210": "非圧縮10ビットRGB",
    "vider408": "コンポーネントY'CbCrA 8ビット4:4:4:4、順序A Y' Cb Cr",
    "videRGBA": "非圧縮32ビットRGBA",
    "viderle ": "アニメーション",
    "viderpza": "ビデオ",
    "vides263": "H.263",
    "videshrp": "畳み込みフィルタ",
    "videslid": "押し出し",
    "videsmc ": "グラフィックス",
    "videsmpt": "ワイプ",
    "videsolr": "カラーバランスフィルタ",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "カラーバランスフィルタ",
    "videtrav": "トラベリングマット",
    "videv210": "コンポーネントY'CbCr 10ビット4:2:2",
    "videv216": "コンポーネントY'CbCr 10、12、14、16ビット4:2:2",
    "videv308": "コンポーネントY'CbCr 8ビット4:4:4",
    "videv408": "コンポーネントY'CbCrA 8ビット4:4:4:4、順序Cb Y' Cr A",
    "videv410": "コンポーネントY'CbCr 10ビット4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "収縮",
    "videy420": "3面コンポーネントY'CbCr 8ビット4:2:0",
    "videyuvs": "コンポーネントY'CbCr 8ビット4:2:2、順序Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
