/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Closed Caption",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Hint",
    "meta": "Metadata",
    "metamebx": "Timed Metadata",
    "musimusi": "Music",
    "muxx": "Muxed",
    "obje": "QTVR Object",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Subtitle",
    "sbtldrmt": "Subtitle",
    "sbtltx3g": "Subtitle",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Sound",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (encrypted)",
    "sounpaac": "AAC (protected)",
    "sounpac3": "AC-3 Dolby Digital (protected)",
    "sounpach": "HE-AACv1 (protected)",
    "sounpacp": "HE-AACv2 (protected)",
    "sounpc+3": "Dolby Atmos (protected)",
    "sounpec3": "EC-3 Dolby Digital+ (protected)",
    "sounqaac": "AAC (protected, fragmented MP4)",
    "sounqac3": "AC-3 Dolby Digital (protected, fragmented MP4)",
    "sounqach": "HE-AACv1 (protected, fragmented MP4)",
    "sounqacp": "HE-AACv2 (protected, fragmented MP4)",
    "sounqc+3": "Dolby Atmos (protected, fragmented MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (protected, fragmented MP4)",
    "sounqlac": "Apple Lossless (protected, fragmented MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protected, transport stream)",
    "sounzac3": "AC-3 Dolby Digital (protected, transport stream)",
    "sounzach": "HE-AACv1 (protected, transport stream)",
    "sounzacp": "HE-AACv2 (protected, transport stream)",
    "sounzc+3": "Dolby Atmos (protected, transport stream)",
    "sounzec3": "EC-3 Dolby Digital+ (protected, transport stream)",
    "sounzlac": "Apple Lossless (protected, transport stream)",
    "sprt": "Sprite",
    "strm": "Streaming",
    "strmrtsp": "Streaming",
    "text": "Text",
    "texttext": "QuickTime Text",
    "texttx3g": "3GPP Text",
    "tmcd": "Timecode",
    "tmcdtmcd": "Timecode",
    "tmet": "Timed Metadata",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Uncompressed 1-bit Indexed Colour",
    "vide2": "Uncompressed 2-bit Indexed Colour",
    "vide2vuy": "Component Y'CbCr 8-bit 4:2:2 ordered Cb Y'0 Cr Y'1",
    "vide4": "Uncompressed 4-bit Indexed Colour",
    "vide8": "Uncompressed 8-bit Indexed Colour",
    "vide8BPS": "Planar RGB",
    "vide16": "Uncompressed 16-bit RGB 555 (Big Endian)",
    "vide24": "Uncompressed 24-bit RGB",
    "vide24BG": "Uncompressed 24-bit BGR",
    "vide32": "Uncompressed 32-bit ARGB",
    "vide33": "Uncompressed 1-bit Greyscale",
    "vide34": "Uncompressed 2-bit Greyscale",
    "vide36": "Uncompressed 4-bit Greyscale",
    "vide40": "Uncompressed 8-bit Greyscale",
    "vide5551": "Uncompressed 16-bit RGB 5551 (Little Endian)",
    "videa2vy": "Two-Plane Component Y'CbCr,A 8-bit 4:2:2,4",
    "videABGR": "Uncompressed 32-bit ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Parameter Sets in Bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Uncompressed 16-bit Greyscale",
    "videb32a": "Uncompressed 32-bit AlphaGray",
    "videb48r": "Uncompressed 48-bit RGB",
    "videb64a": "Uncompressed 64-bit ARGB",
    "videB565": "Uncompressed 16-bit RGB 565 (Big Endian)",
    "videBGRA": "Uncompressed 32-bit BGRA",
    "videbhiv": "bhiv",
    "videblur": "Convolution Filter",
    "videcdh1": "Dolby Vision HEVC (encrypted)",
    "videclou": "Cloud",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Cross Fade",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Convolution Filter",
    "videfire": "Fire",
    "videfmns": "Film Noise Filter",
    "videgenk": "Convolution Filter",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "HEVC (Parameter Sets in Bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Photo - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Preview)",
    "videkpcd": "Photo CD",
    "videL555": "Uncompressed 16-bit RGB 555 (Little Endian)",
    "videL565": "Uncompressed 16-bit RGB 565 (Little Endian)",
    "vidematt": "Gradient Wipe",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 Video",
    "videmp2v": "MPEG-2 Video",
    "videmp4v": "MPEG-4 Video",
    "videmplo": "Implode",
    "videmuxa": "HEVC with Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Unknown",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (protected, fragmented MP4)",
    "vider210": "Uncompressed 10-bit RGB",
    "vider408": "Component Y'CbCrA 8-bit 4:4:4:4 ordered A Y' Cb Cr",
    "videRGBA": "Uncompressed 32-bit RGBA",
    "viderle ": "Animation",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Convolution Filter",
    "videslid": "Push",
    "videsmc ": "Graphics",
    "videsmpt": "Wipe",
    "videsolr": "Colour Balance Filter",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Colour Balance Filter",
    "videtrav": "Travelling Matte",
    "videv210": "Component Y'CbCr 10-bit 4:2:2",
    "videv216": "Component Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Component Y'CbCr 8-bit 4:4:4",
    "videv408": "Component Y'CbCrA 8-bit 4:4:4:4 ordered Cb Y' Cr A",
    "videv410": "Component Y'CbCr 10-bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Implode",
    "videy420": "Three-Plane Component Y'CbCr 8-bit 4:2:0",
    "videyuvs": "Component Y'CbCr 8-bit 4:2:2 ordered Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
