/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Napisy dla niesłyszących",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Podpowiedź",
    "meta": "Metadane",
    "metamebx": "Metadane czasowe",
    "musimusi": "Muzyka",
    "muxx": "Muxed",
    "obje": "Obiekt QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Napisy",
    "sbtldrmt": "Napisy",
    "sbtltx3g": "Napisy",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Wygląd",
    "skinskcr": "Wygląd",
    "skinskdr": "Wygląd",
    "soun": "Dźwięk",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (zaszyfrowany)",
    "sounpaac": "AAC (zabezpieczony)",
    "sounpac3": "AC‑3 Dolby Digital (zabezpieczony)",
    "sounpach": "HE‑AACv1 (zabezpieczony)",
    "sounpacp": "HE‑AACv2 (zabezpieczony)",
    "sounpc+3": "Dolby Atmos (zabezpieczony)",
    "sounpec3": "EC‑3 Dolby Digital+ (zabezpieczony)",
    "sounqaac": "AAC (zabezpieczony, fragmentowany plik MP4)",
    "sounqac3": "AC‑3 Dolby Digital (zabezpieczony, fragmentowany plik MP4)",
    "sounqach": "HE‑AACv1 (zabezpieczony, fragmentowany plik MP4)",
    "sounqacp": "HE‑AACv2 (zabezpieczony, fragmentowany plik MP4)",
    "sounqc+3": "Dolby Atmos (zabezpieczony, fragmentowany plik MP4)",
    "sounqec3": "EC‑3 Dolby Digital+ (zabezpieczony, fragmentowany plik MP4)",
    "sounqlac": "Apple Lossless (zabezpieczony, fragmentowany plik MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (zabezpieczony, strumień transportowy)",
    "sounzac3": "AC‑3 Dolby Digital (zabezpieczony, strumień transportowy)",
    "sounzach": "HE‑AACv1 (zabezpieczony, strumień transportowy)",
    "sounzacp": "HE‑AACv2 (zabezpieczony, strumień transportowy)",
    "sounzc+3": "Dolby Atmos (zabezpieczony, strumień transportowy)",
    "sounzec3": "EC‑3 Dolby Digital+ (zabezpieczony, strumień transportowy)",
    "sounzlac": "Apple Lossless (zabezpieczony, strumień transportowy)",
    "sprt": "Sprite",
    "strm": "Strumieniowanie",
    "strmrtsp": "Strumieniowanie",
    "text": "Tekst",
    "texttext": "Tekst QuickTime",
    "texttx3g": "Tekst 3GPP",
    "tmcd": "Kod czasowy",
    "tmcdtmcd": "Kod czasowy",
    "tmet": "Metadane czasowe",
    "twen": "Klatka pośrednia",
    "vide": "Wideo",
    "vide1": "Nieskompresowany, zindeksowany kolor 1-bitowy",
    "vide2": "Nieskompresowany, zindeksowany kolor 2-bitowy",
    "vide2vuy": "Component Y'CbCr 8-bit 4:2:2 ordered Cb Y'0 Cr Y'1",
    "vide4": "Nieskompresowany, zindeksowany kolor 4-bitowy",
    "vide8": "Nieskompresowany, zindeksowany kolor 8-bitowy",
    "vide8BPS": "Planar RGB",
    "vide16": "Nieskompresowany 16-bitowy RGB 555 (Big Endian)",
    "vide24": "Nieskompresowany 24-bitowy RGB",
    "vide24BG": "Nieskompresowany 24-bitowy BGR",
    "vide32": "Nieskompresowany 32-bitowy ARGB",
    "vide33": "Nieskompresowana 1-bitowa skala szarości",
    "vide34": "Nieskompresowana 2-bitowa skala szarości",
    "vide36": "Nieskompresowana 4-bitowa skala szarości",
    "vide40": "Nieskompresowana 8-bitowa skala szarości",
    "vide5551": "Nieskompresowany 16-bitowy RGB 5551 (Little Endian)",
    "videa2vy": "Two-Plane Component Y'CbCr,A 8-bit 4:2:2,4",
    "videABGR": "Nieskompresowany 32-bitowy ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (zestawy parametrów w bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Nieskompresowana 16-bitowa skala szarości",
    "videb32a": "Nieskompresowany 32-bitowy AlphaGray",
    "videb48r": "Nieskompresowany 48-bitowy RGB",
    "videb64a": "Nieskompresowany 64-bitowy ARGB",
    "videB565": "Nieskompresowany 16-bitowy RGB 565 (Big Endian)",
    "videBGRA": "Nieskompresowany 32-bitowy BGRA",
    "videbhiv": "bhiv",
    "videblur": "Filtr splotu",
    "videcdh1": "Dolby Vision HEVC (zaszyfrowany)",
    "videclou": "Chmura",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "Nośnik AVC0",
    "videdslv": "Wzajemne przenikanie",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtr splotu",
    "videfire": "Ogień",
    "videfmns": "Filtr zakłóceń filmu",
    "videgenk": "Filtr splotu",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bitowy 4:2:2",
    "videhev1": "HEVC (zestawy parametrów w bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Photo - JPEG",
    "videJvt3": "Apple H.264/AVC Video (podgląd)",
    "videkpcd": "Photo CD",
    "videL555": "Nieskompresowany 16-bitowy RGB 555 (Little Endian)",
    "videL565": "Nieskompresowany 16-bitowy RGB 565 (Little Endian)",
    "vidematt": "Przecieranie gradientem",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Wideo MPEG-1",
    "videmp2v": "Wideo MPEG-2",
    "videmp4v": "Wideo MPEG-4",
    "videmplo": "Implozja",
    "videmuxa": "HEVC z kanałem alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Nieznany",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC zabezpieczony, fragmentowany plik MP4)",
    "vider210": "Nieskompresowany 10-bitowy RGB",
    "vider408": "Component Y'CbCrA 8-bit 4:4:4:4 ordered A Y' Cb Cr",
    "videRGBA": "Nieskompresowany 32-bitowy RGBA",
    "viderle ": "Animacja",
    "viderpza": "Wideo",
    "vides263": "H.263",
    "videshrp": "Filtr splotu",
    "videslid": "Wypchnięcie",
    "videsmc ": "Grafika",
    "videsmpt": "Ścieranie",
    "videsolr": "Filtr wyrównania koloru",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filtr wyrównania koloru",
    "videtrav": "Wędrująca maska",
    "videv210": "Component Y'CbCr 10-bit 4:2:2",
    "videv216": "Component Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Component Y'CbCr 8-bit 4:4:4",
    "videv408": "Component Y'CbCrA 8-bit 4:4:4:4 ordered Cb Y' Cr A",
    "videv410": "Component Y'CbCr 10-bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bitowy",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bitowy",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bitowy",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bitowy",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bitowy",
    "videxfia": "XF-AVC Intra 4:2:2 10-bitowy",
    "videxplo": "Implozja",
    "videy420": "Three-Plane Component Y'CbCr 8-bit 4:2:0",
    "videyuvs": "Component Y'CbCr 8-bit 4:2:2 ordered Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
