/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Skryté titulky",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Nápoveda",
    "meta": "Metadáta",
    "metamebx": "Časované metadáta",
    "musimusi": "Hudba",
    "muxx": "Multiplexované",
    "obje": "QTVR Objekt",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panoráma",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Titulky",
    "sbtldrmt": "Titulky",
    "sbtltx3g": "Titulky",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Vzhľad",
    "skinskcr": "Vzhľad",
    "skinskdr": "Vzhľad",
    "soun": "Zvuk",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (šifrované)",
    "sounpaac": "AAC (chránené)",
    "sounpac3": "AC-3 Dolby Digital (chránené)",
    "sounpach": "HE-AACv1 (chránené)",
    "sounpacp": "HE-AACv2 (chránené)",
    "sounpc+3": "Dolby Atmos (chránené)",
    "sounpec3": "EC-3 Dolby Digital+ (chránené)",
    "sounqaac": "AAC (chránené, fragmentovaný súbor MP4)",
    "sounqac3": "AC-3 Dolby Digital (chránené, fragmentovaný súbor MP4)",
    "sounqach": "HE-AACv1 (chránené, fragmentovaný súbor MP4)",
    "sounqacp": "HE-AACv2 (chránené, fragmentovaný súbor MP4)",
    "sounqc+3": "Dolby Atmos (chránené, fragmentovaný súbor MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (chránené, fragmentovaný súbor MP4)",
    "sounqlac": "Apple Lossless (chránené, fragmentovaný súbor MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (chránené, prenosový stream)",
    "sounzac3": "AC-3 Dolby Digital (chránené, prenosový stream)",
    "sounzach": "HE-AACv1 (chránené, prenosový stream)",
    "sounzacp": "HE-AACv2 (chránené, prenosový stream)",
    "sounzc+3": "Dolby Atmos (chránené, prenosový stream)",
    "sounzec3": "EC-3 Dolby Digital+ (chránené, prenosový stream)",
    "sounzlac": "Apple Lossless (chránené, prenosový stream)",
    "sprt": "Sprite",
    "strm": "Streamovanie",
    "strmrtsp": "Streamovanie",
    "text": "Text",
    "texttext": "QuickTime text",
    "texttx3g": "3GPP text",
    "tmcd": "Časový kód",
    "tmcdtmcd": "Časový kód",
    "tmet": "Časované metadáta",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Nekomprimovaný 1-bitový indexovaná farba",
    "vide2": "Nekomprimovaný 2-bitový indexovaná farba",
    "vide2vuy": "Komponentné Y'CbCr 8-bit 4:2:2 v poradí Cb Y'0 Cr Y'1",
    "vide4": "Nekomprimovaná 4-bitová indexovaná farba",
    "vide8": "Nekomprimovaný 8-bitový indexovaná farba",
    "vide8BPS": "Planárne RGB",
    "vide16": "Nekomprimovaný 16-bitový RGB 555 (Big Endian)",
    "vide24": "Nekomprimovaný 24-bitový RGB",
    "vide24BG": "Nekomprimovaný 24-bitový BGR",
    "vide32": "Nekomprimovaný 32-bitový ARGB",
    "vide33": "Nekomprimovaný 1-bitový šedý",
    "vide34": "Nekomprimovaný 2-bitový šedý",
    "vide36": "Nekomprimovaný 4-bitový šedý",
    "vide40": "Nekomprimovaný 8-bitový šedý",
    "vide5551": "Nekomprimovaný 16-bitový RGB 5551 (Little Endian)",
    "videa2vy": "Dvojrovinné komponentné Y'CbCr,A 8-bit 4:2:2,4",
    "videABGR": "Nekomprimovaný 32-bitový ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Sady parametrov v bitstreame)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Nekomprimovaný 16-bitový šedý",
    "videb32a": "Nekomprimovaný 32-bitový AlphaGray",
    "videb48r": "Nekomprimovaný 48-bitový RGB",
    "videb64a": "Nekomprimovaný 64-bitový ARGB",
    "videB565": "Nekomprimovaný 16-bitový RGB 565 (Big Endian)",
    "videBGRA": "Nekomprimovaný 32-bitový BGRA",
    "videbhiv": "bhiv",
    "videblur": "Konvolučný filter",
    "videcdh1": "Dolby Vision HEVC (šifrované)",
    "videclou": "Oblak",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Prelínačka",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Konvolučný filter",
    "videfire": "Oheň",
    "videfmns": "Filter filmový šum",
    "videgenk": "Konvolučný filter",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "HEVC (Sady parametrov v bitstreame)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Fotka - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Náhľad)",
    "videkpcd": "Photo CD",
    "videL555": "Nekomprimovaný 16-bitový RGB 555 (Little Endian)",
    "videL565": "Nekomprimovaný 16-bitový RGB 565 (Little Endian)",
    "vidematt": "Postupná stieračka",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 Video",
    "videmp2v": "MPEG-2 Video",
    "videmp4v": "MPEG-4 Video",
    "videmplo": "Implodovať",
    "videmuxa": "HEVC s alfou",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Neznámy",
    "videpng ": "PNG",
    "videpush": "Odtlačenie",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (chránené, fragmentovaný súbor MP4)",
    "vider210": "Nekomprimovaný 10-bitový RGB",
    "vider408": "Komponentné Y'CbCrA 8-bit 4:4:4:4 v poradí A Y' Cb Cr",
    "videRGBA": "Nekomprimovaný 32-bitový RGBA",
    "viderle ": "Animácia",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Konvolučný filter",
    "videslid": "Push",
    "videsmc ": "Grafika",
    "videsmpt": "Stieračka",
    "videsolr": "Filter vyváženia farieb",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filter vyváženia farieb",
    "videtrav": "Pohyblivá maska",
    "videv210": "Komponentné Y'CbCr 10-bit 4:2:2",
    "videv216": "Komponentné Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Komponentné Y'CbCr 8-bit 4:4:4",
    "videv408": "Komponentné Y'CbCrA 8-bit 4:4:4:4 v poradí Cb Y' Cr A",
    "videv410": "Komponentné Y'CbCr 10-bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Implodovať",
    "videy420": "Trojrovinné komponentné Y'CbCr 8-bit 4:2:0",
    "videyuvs": "Komponentné Y'CbCr 8-bit 4:2:2 v poradí Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
