/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "청각 장애인용 자막",
    "clcpatcc": "ATSC/52 파트-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "힌트",
    "meta": "메타데이터",
    "metamebx": "타임드 메타데이터",
    "musimusi": "음악",
    "muxx": "멀티플렉스됨",
    "obje": "QTVR 대상체",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR 파노라마",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "자막",
    "sbtldrmt": "자막",
    "sbtltx3g": "자막",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "스킨",
    "skinskcr": "스킨",
    "skinskdr": "스킨",
    "soun": "사운드",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless(암호화됨)",
    "sounpaac": "AAC(보호됨)",
    "sounpac3": "AC-3 Dolby Digital(보호됨)",
    "sounpach": "HE-AACv1(보호됨)",
    "sounpacp": "HE-AACv2(보호됨)",
    "sounpc+3": "Dolby Atmos(보호됨)",
    "sounpec3": "EC-3 Dolby Digital+(보호됨)",
    "sounqaac": "AAC(보호됨, 분할된 MP4)",
    "sounqac3": "AC-3 Dolby Digital(보호됨, 분할된 MP4)",
    "sounqach": "HE-AACv1(보호됨, 분할된 MP4)",
    "sounqacp": "HE-AACv2(보호됨, 분할된 MP4)",
    "sounqc+3": "Dolby Atmos(보호됨, 분할된 MP4)",
    "sounqec3": "EC-3 Dolby Digital+(보호됨, 분할된 MP4)",
    "sounqlac": "Apple Lossless(보호됨, 분할된 MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC(보호됨, 전송 스트림)",
    "sounzac3": "AC-3 Dolby Digital(보호됨, 전송 스트림)",
    "sounzach": "HE-AACv1(보호됨, 전송 스트림)",
    "sounzacp": "HE-AACv2(보호됨, 전송 스트림)",
    "sounzc+3": "Dolby Atmos(보호됨, 전송 스트림)",
    "sounzec3": "EC-3 Dolby Digital+(보호됨, 전송 스트림)",
    "sounzlac": "Apple Lossless(보호됨, 전송 스트림)",
    "sprt": "스프라이트",
    "strm": "스트리밍",
    "strmrtsp": "스트리밍",
    "text": "텍스트",
    "texttext": "QuickTime 텍스트",
    "texttx3g": "3GPP 텍스트",
    "tmcd": "타임 코드",
    "tmcdtmcd": "타임 코드",
    "tmet": "타임드 메타데이터",
    "twen": "Tween",
    "vide": "비디오",
    "vide1": "비압축 1비트 인덱스 색상",
    "vide2": "비압축 2비트 인덱스 색상",
    "vide2vuy": "Cb Y'0 Cr Y'1로 정렬된 Y'CbCr 8비트 4:2:2 컴포넌트",
    "vide4": "비압축 4비트 인덱스 색상",
    "vide8": "비압축 8비트 인덱스 색상",
    "vide8BPS": "Planar RGB",
    "vide16": "비압축 16비트 RGB 555(빅 엔디안)",
    "vide24": "비압축 24비트 RGB",
    "vide24BG": "비압축 24비트 BGR",
    "vide32": "비압축 32비트 ARGB",
    "vide33": "비압축 1비트 그레이 스케일",
    "vide34": "비압축 2비트 그레이 스케일",
    "vide36": "비압축 4비트 그레이 스케일",
    "vide40": "비압축 8비트 그레이 스케일",
    "vide5551": "비압축 16비트 RGB 5551(리틀 엔디안)",
    "videa2vy": "Y'CbCr,A 8비트 4:2:2,4 2면 컴포넌트",
    "videABGR": "비압축 32비트 ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 프록시",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264(매개변수 세트 위치: 비트스트림)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "비압축 16비트 그레이 스케일",
    "videb32a": "비압축 32비트 알파 그레이",
    "videb48r": "비압축 48비트 RGB",
    "videb64a": "비압축 64비트 ARGB",
    "videB565": "비압축 16비트 RGB 565(빅 엔디안)",
    "videBGRA": "비압축 32비트 BGRA",
    "videbhiv": "bhiv",
    "videblur": "회선 필터",
    "videcdh1": "Dolby Vision HEVC(암호화됨)",
    "videclou": "구름 효과",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 미디어",
    "videdslv": "교차 페이드",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD(1080p25)",
    "videdvh3": "DVCPRO HD(1080p30)",
    "videdvh5": "DVCPRO HD(1080i50)",
    "videdvh6": "DVCPRO HD(1080i60)",
    "videdvhp": "DVCPRO HD(720p60)",
    "videdvhq": "DVCPRO HD(720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "회선 필터",
    "videfire": "화염 효과",
    "videfmns": "필름 노이즈 필터",
    "videgenk": "회선 필터",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10비트 4:2:2",
    "videhev1": "HEVC(매개변수 세트 위치: 비트스트림)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "포토 - JPEG",
    "videJvt3": "Apple H.264/AVC 비디오(미리보기)",
    "videkpcd": "포토 CD",
    "videL555": "비압축 16비트 RGB 555(리틀 엔디안)",
    "videL565": "비압축 16비트 RGB 565(리틀 엔디안)",
    "vidematt": "그라디언트 와이프 효과",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 비디오",
    "videmp2v": "MPEG-2 비디오",
    "videmp4v": "MPEG-4 비디오",
    "videmplo": "내파 효과",
    "videmuxa": "HEVC(알파)",
    "videmx3n": "MPEG IMX 525/60(30Mb/초)",
    "videmx3p": "MPEG IMX 625/50(30Mb/초)",
    "videmx4n": "MPEG IMX 525/60(40Mb/초)",
    "videmx4p": "MPEG IMX 625/50(40Mb/초)",
    "videmx5n": "MPEG IMX 525/60(50Mb/초)",
    "videmx5p": "MPEG IMX 625/50(50Mb/초)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "알 수 없음",
    "videpng ": "PNG",
    "videpush": "밀어내기 효과",
    "videpxlt": "Apple Pixlet 비디오",
    "videqdh1": "Dolby Vision HEVC(보호됨, 분할된 MP4)",
    "vider210": "비압축 10비트 RGB",
    "vider408": "A Y' Cb Cr로 정렬된 Y'CbCrA 8비트 4:4:4:4 컴포넌트",
    "videRGBA": "비압축 32비트 RGBA",
    "viderle ": "애니메이션",
    "viderpza": "비디오",
    "vides263": "H.263",
    "videshrp": "회선 필터",
    "videslid": "밀어내기 효과",
    "videsmc ": "그래픽",
    "videsmpt": "닦아내기 효과",
    "videsolr": "색상 균형 필터",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "색상 균형 필터",
    "videtrav": "트래블링 매트",
    "videv210": "Y'CbCr 10비트 4:2:2 컴포넌트",
    "videv216": "Y'CbCr 10,12,14,16비트 4:2:2 컴포넌트",
    "videv308": "Y'CbCr 8비트 4:4:4 컴포넌트",
    "videv408": "Cb Y' Cr A로 정렬된 Y'CbCrA 8비트 4:4:4:4 컴포넌트",
    "videv410": "Y'CbCr 10비트 4:4:4 컴포넌트",
    "videVP31": "On2 VP3 비디오 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10비트",
    "videxf4c": "XF-AVC Intra 4:4:4 12비트",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8비트",
    "videxfga": "XF-AVC Long GOP 4:2:2 10비트",
    "videxfi8": "XF-AVC Intra 4:2:2 8비트",
    "videxfia": "XF-AVC Intra 4:2:2 10비트",
    "videxplo": "내파 효과",
    "videy420": "Y'CbCr 8비트 4:2:0 3면 컴포넌트",
    "videyuvs": "Y'0 Cb Y'1 Cr로 정렬된 Y'CbCr 8비트 4:2:2 컴포넌트",
    "videzygo": "ZyGoVideo",
]
