/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Sottotitoli (CC)",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Suggerimento",
    "meta": "Metadati",
    "metamebx": "Metadati temporizzati",
    "musimusi": "Musica",
    "muxx": "Muxed",
    "obje": "Oggetto QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Sottotitolo",
    "sbtldrmt": "Sottotitolo",
    "sbtltx3g": "Sottotitolo",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Suono",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (crittografato)",
    "sounpaac": "AAC (protetto)",
    "sounpac3": "AC‑3 Dolby Digital (protetto)",
    "sounpach": "HE‑AACv1 (protetto)",
    "sounpacp": "HE‑AACv2 (protetto)",
    "sounpc+3": "Dolby Atmos (protetto)",
    "sounpec3": "EC‑3 Dolby Digital+ (protetto)",
    "sounqaac": "AAC (protetto, MP4 frammentato)",
    "sounqac3": "AC‑3 Dolby Digital (protetto, MP4 frammentato)",
    "sounqach": "HE‑AACv1 (protetto, MP4 frammentato)",
    "sounqacp": "HE‑AACv2 (protetto, MP4 frammentato)",
    "sounqc+3": "Dolby Atmos (protetto, MP4 frammentato)",
    "sounqec3": "EC‑3 Dolby Digital+ (protetto, MP4 frammentato)",
    "sounqlac": "Apple Lossless (protetto, MP4 frammentato)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protetto, flusso di trasporto)",
    "sounzac3": "AC‑3 Dolby Digital (protetto, flusso di trasporto)",
    "sounzach": "HE‑AACv1 (protetto, flusso di trasporto)",
    "sounzacp": "HE‑AACv2 (protetto, flusso di trasporto)",
    "sounzc+3": "Dolby Atmos (protetto, flusso di trasporto)",
    "sounzec3": "EC‑3 Dolby Digital+ (protetto, flusso di trasporto)",
    "sounzlac": "Apple Lossless (protetto, flusso di trasporto)",
    "sprt": "Sprite",
    "strm": "Streaming",
    "strmrtsp": "Streaming",
    "text": "Testo",
    "texttext": "Testo QuickTime",
    "texttx3g": "Testo 3GPP",
    "tmcd": "Timecode",
    "tmcdtmcd": "Timecode",
    "tmet": "Metadati temporizzati",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Colore indicizzato 1-bit non compresso",
    "vide2": "Colore indicizzato 2-bit non compresso",
    "vide2vuy": "Componente Y’CbCr 8-bit 4:2:2 ordinato Cb Y’0 Cr Y’1",
    "vide4": "Colore indicizzato 4-bit non compresso",
    "vide8": "Colore indicizzato 8-bit non compresso",
    "vide8BPS": "Planar RGB",
    "vide16": "16-bit RGB 555 non compresso (Big Endian)",
    "vide24": "24-bit RGB non compresso",
    "vide24BG": "24-bit BGR non compresso",
    "vide32": "32-bit ARGB non compresso",
    "vide33": "Scala di grigio 1-bit non compresso",
    "vide34": "Scala di grigio 2-bit non compresso",
    "vide36": "Scala di grigio 4-bit non compresso",
    "vide40": "Scala di grigio 8-bit non compresso",
    "vide5551": "16-bit RGB 5551 non compresso (Little Endian)",
    "videa2vy": "Componente Two-Plane Y’CbCr,A 8-bit 4:2:2,4",
    "videABGR": "32-bit ABGR non compresso",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (set di parametri in bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Scala di grigio 16-bit non compresso",
    "videb32a": "32-bit AlphaGray non compresso",
    "videb48r": "48-bit RGB non compresso",
    "videb64a": "64-bit ARGB non compresso",
    "videB565": "16-bit RGB 565 non compresso (Big Endian)",
    "videBGRA": "32-bit BGRA non compresso",
    "videbhiv": "bhiv",
    "videblur": "Filtro contorsione",
    "videcdh1": "Dolby Vision HEVC (crittografato)",
    "videclou": "Cloud",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "Media AVC0",
    "videdslv": "Dissolvenza incrociata",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtro contorsione",
    "videfire": "Fire",
    "videfmns": "Filtro disturbo film",
    "videgenk": "Filtro contorsione",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "HEVC (set di parametri in bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Foto - JPEG",
    "videJvt3": "Video Apple H.264/AVC (Anteprima)",
    "videkpcd": "Foto CD",
    "videL555": "16-bit RGB 555 non compresso (Little Endian)",
    "videL565": "16-bit RGB 565 non compresso (Little Endian)",
    "vidematt": "Tendina a gradazione",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Video MPEG-1",
    "videmp2v": "Video MPEG-2",
    "videmp4v": "Video MPEG-4",
    "videmplo": "Implosione",
    "videmuxa": "HEVC con alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Sconosciuto",
    "videpng ": "PNG",
    "videpush": "Invia",
    "videpxlt": "Video Apple Pixlet",
    "videqdh1": "Dolby Vision HEVC (protetto, MP4 frammentato)",
    "vider210": "10-bit RGB non compresso",
    "vider408": "Componente Y’CbCrA 8-bit 4:4:4:4 ordinato A Y’ Cb Cr",
    "videRGBA": "32-bit RGBA non compresso",
    "viderle ": "Animazione",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Filtro contorsione",
    "videslid": "Invia",
    "videsmc ": "Grafica",
    "videsmpt": "Tendina",
    "videsolr": "Filtro bilanciamento colore",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filtro bilanciamento colore",
    "videtrav": "Traveling Matte",
    "videv210": "Componente Y’CbCr 10-bit 4:2:2",
    "videv216": "Componente Y’CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Componente Y’CbCr 8-bit 4:4:4",
    "videv408": "Componente Y’CbCrA 8-bit 4:4:4:4 ordinato Cb Y’ Cr A",
    "videv410": "Componente Y’CbCr 10-bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Implosione",
    "videy420": "Componente Three-Plane Y’CbCr 8-bit 4:2:0",
    "videyuvs": "Componente Y’CbCr 8-bit 4:2:2 ordinato Y’0 Cb Y’1 Cr",
    "videzygo": "ZyGoVideo",
]
