/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Szöveges átirat",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Tipp",
    "meta": "Metaadatok",
    "metamebx": "Időzített metaadat",
    "musimusi": "Zene",
    "muxx": "Multiplexelt",
    "obje": "QTVR objektum",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panoráma",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Felirat",
    "sbtldrmt": "Felirat",
    "sbtltx3g": "Felirat",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Felület",
    "skinskcr": "Felület",
    "skinskdr": "Felület",
    "soun": "Hang",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (titkosított)",
    "sounpaac": "AAC (védett)",
    "sounpac3": "AC-3 Dolby Digital (védett)",
    "sounpach": "HE-AACv1 (védett)",
    "sounpacp": "HE-AACv2 (védett)",
    "sounpc+3": "Dolby Atmos (védett)",
    "sounpec3": "EC-3 Dolby Digital+ (védett)",
    "sounqaac": "AAC (védett, töredezett MP4)",
    "sounqac3": "AC-3 Dolby Digital (védett, töredezett MP4)",
    "sounqach": "HE-AACv1 (védett, töredezett MP4)",
    "sounqacp": "HE-AACv2 (védett, töredezett MP4)",
    "sounqc+3": "Dolby Atmos (védett, töredezett MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (védett, töredezett MP4)",
    "sounqlac": "Apple Lossless (védett, töredezett MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (védett, átviteli stream)",
    "sounzac3": "AC-3 Dolby Digital (védett, átviteli stream)",
    "sounzach": "HE-AACv1 (védett, átviteli stream)",
    "sounzacp": "HE-AACv2 (védett, átviteli stream)",
    "sounzc+3": "Dolby Atmos (védett, átviteli stream)",
    "sounzec3": "EC-3 Dolby Digital+ (védett, átviteli stream)",
    "sounzlac": "Apple Lossless (védett, átviteli stream)",
    "sprt": "Folt",
    "strm": "Streamtovábbítás",
    "strmrtsp": "Streamtovábbítás",
    "text": "Szöveg",
    "texttext": "QuickTime-szöveg",
    "texttx3g": "3GPP-szöveg",
    "tmcd": "Időkód",
    "tmcdtmcd": "Időkód",
    "tmet": "Időzített metaadat",
    "twen": "Tween",
    "vide": "Videó",
    "vide1": "Tömörítetlen 1 bites indexelt színes",
    "vide2": "Tömörítetlen 2 bites indexelt színes",
    "vide2vuy": "Komponens Y'CbCr 8 bites 4:2:2 rendezett Cb Y'0 Cr Y'1",
    "vide4": "Tömörítetlen 4 bites indexelt színes",
    "vide8": "Tömörítetlen 8 bites indexelt színes",
    "vide8BPS": "Síkbeli RGB",
    "vide16": "Tömörítetlen 16 bites RGB 555 (Big Endian)",
    "vide24": "Tömörítetlen 24 bites RGB",
    "vide24BG": "Tömörítetlen 24 bites BGR",
    "vide32": "Tömörítetlen 32 bites ARGB",
    "vide33": "Tömörítetlen 1 bites szürkeárnyalatos",
    "vide34": "Tömörítetlen 2 bites szürkeárnyalatos",
    "vide36": "Tömörítetlen 4 bites szürkeárnyalatos",
    "vide40": "Tömörítetlen 8 bites szürkeárnyalatos",
    "vide5551": "Tömörítetlen 16 bites RGB 5551 (Little Endian)",
    "videa2vy": "Kétsíkú komponens Y'CbCr,A 8 bites 4:2:2,4",
    "videABGR": "Tömörítetlen 32 bites ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (paraméterkészletek az adatfolyamban)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Tömörítetlen 16 bites szürkeárnyalatos",
    "videb32a": "Tömörítetlen 32 bites AlphaGray",
    "videb48r": "Tömörítetlen 48 bites RGB",
    "videb64a": "Tömörítetlen 64 bites ARGB",
    "videB565": "Tömörítetlen 16 bites RGB 565 (Big Endian)",
    "videBGRA": "Tömörítetlen 32 bites BGRA",
    "videbhiv": "bhiv",
    "videblur": "Konvolúciós szűrő",
    "videcdh1": "Dolby Vision HEVC (titkosított)",
    "videclou": "Felhő",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 média",
    "videdslv": "Áttűnés",
    "videdv5n": "DVCPRO50 – NTSC",
    "videdv5p": "DVCPRO50 – PAL",
    "videdvc ": "DV/DVCPRO – NTSC",
    "videdvcp": "DVC – PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO – PAL",
    "videEIDI": "EIDI",
    "videembs": "Konvolúciós szűrő",
    "videfire": "Tűz",
    "videfmns": "Filmzajszűrő",
    "videgenk": "Konvolúciós szűrő",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 bites 4:2:2",
    "videhev1": "HEVC (paraméterkészletek az adatfolyamban)",
    "videhvc1": "HEVC",
    "videicod": "Apple közbenső kodek",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Fotó – JPEG",
    "videJvt3": "Apple H.264/AVC videó (előnézet)",
    "videkpcd": "Photo CD",
    "videL555": "Tömörítetlen 16 bites RGB 555 (Little Endian)",
    "videL565": "Tömörítetlen 16 bites RGB 565 (Little Endian)",
    "vidematt": "Átmenetes törlés",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 videó",
    "videmp2v": "MPEG-2 videó",
    "videmp4v": "MPEG-4 videó",
    "videmplo": "Berobbanás",
    "videmuxa": "HEVC alfával",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Ismeretlen",
    "videpng ": "PNG",
    "videpush": "Átnyomás",
    "videpxlt": "Apple Pixlet videó",
    "videqdh1": "Dolby Vision HEVC (védett, töredezett MP4)",
    "vider210": "Tömörítetlen 10 bites RGB",
    "vider408": "Komponens Y'CbCrA 8 bites 4:4:4:4 rendezett A Y' Cb Cr",
    "videRGBA": "Tömörítetlen 32 bites RGBA",
    "viderle ": "Animáció",
    "viderpza": "Videó",
    "vides263": "H.263",
    "videshrp": "Konvolúciós szűrő",
    "videslid": "Átnyomás",
    "videsmc ": "Grafika",
    "videsmpt": "Törlés",
    "videsolr": "Színegyensúlyszűrő",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Színegyensúlyszűrő",
    "videtrav": "Mozgó maszk",
    "videv210": "Komponens Y'CbCr 10 bites 4:2:2",
    "videv216": "Komponens Y'CbCr 10,12,14,16 bites 4:2:2",
    "videv308": "Komponens Y'CbCr 8 bites 4:4:4",
    "videv408": "Komponens: Y'CbCrA 8 bites 4:4:4:4 rendezett Cb Y' Cr A",
    "videv410": "Komponens Y'CbCr 10 bites 4:4:4",
    "videVP31": "On2 VP3 videó 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Berobbanás",
    "videy420": "Háromsíkú komponens Y'CbCr 8 bites 4:2:0",
    "videyuvs": "Komponens Y'CbCr 8 bites 4:2:2 rendezett Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
