/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Teks Tertulis",
    "clcpatcc": "ATSC/52 bagian-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Petunjuk",
    "meta": "Metadata",
    "metamebx": "Metadata Berjangka Waktu",
    "musimusi": "Musik",
    "muxx": "MUX",
    "obje": "Objek QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Subtitle",
    "sbtldrmt": "Subtitle",
    "sbtltx3g": "Subtitle",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Kulit",
    "skinskcr": "Kulit",
    "skinskdr": "Kulit",
    "soun": "Bunyi",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (dienkripsi)",
    "sounpaac": "AAC (dilindungi)",
    "sounpac3": "AC-3 Dolby Digital (dilindungi)",
    "sounpach": "HE-AACv1 (dilindungi)",
    "sounpacp": "HE-AACv2 (dilindungi)",
    "sounpc+3": "Dolby Atmos (dilindungi)",
    "sounpec3": "EC-3 Dolby Digital+ (dilindungi)",
    "sounqaac": "AAC (dilindungi, MP4 terfragmentasi)",
    "sounqac3": "AC-3 Dolby Digital (dilindungi, MP4 terfragmentasi)",
    "sounqach": "HE-AACv1 (dilindungi, MP4 terfragmentasi)",
    "sounqacp": "HE-AACv2 (dilindungi, MP4 terfragmentasi)",
    "sounqc+3": "Dolby Atmos (dilindungi, MP4 terfragmentasi)",
    "sounqec3": "EC-3 Dolby Digital+ (dilindungi, MP4 terfragmentasi)",
    "sounqlac": "Apple Lossless (dilindungi, MP4 terfragmentasi)",
    "sounvdva": "DV",
    "sounzaac": "AAC (dilindungi, stream transpor)",
    "sounzac3": "AC-3 Dolby Digital (dilindungi, stream transpor)",
    "sounzach": "HE-AACv1 (dilindungi, stream transpor)",
    "sounzacp": "HE-AACv2 (dilindungi, stream transpor)",
    "sounzc+3": "Dolby Atmos (dilindungi, stream transpor)",
    "sounzec3": "EC-3 Dolby Digital+ (dilindungi, stream transpor)",
    "sounzlac": "Apple Lossless (dilindungi, stream transpor)",
    "sprt": "Sprite",
    "strm": "Streaming",
    "strmrtsp": "Streaming",
    "text": "Teks",
    "texttext": "Teks QuickTime",
    "texttx3g": "Teks 3GPP",
    "tmcd": "Kode waktu",
    "tmcdtmcd": "Kode waktu",
    "tmet": "Metadata Waktu",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Warna Terindeks 1-bit tidak dikompresi",
    "vide2": "Warna Terindeks 2-bit tidak dikompresi",
    "vide2vuy": "Komponen Y'CbCr 8-bit 4:2:2 diurutkan Cb Y'0 Cr Y'1",
    "vide4": "Warna Terindeks 4-bit tidak dikompresi",
    "vide8": "Warna Terindeks 8-bit tidak dikompresi",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555 (Endian Besar) 16-bit tidak dikompresi",
    "vide24": "RGB 24-bit tidak dikompresi",
    "vide24BG": "BGR 24-bit tidak dikompresi",
    "vide32": "ARGB 32-bit tidak dikompresi",
    "vide33": "Skala Abu-Abu 1 bit tidak diringkas",
    "vide34": "Skala Abu-Abu 2 bit tidak diringkas",
    "vide36": "Skala Abu-Abu 4 bit tidak diringkas",
    "vide40": "Skala Abu-Abu 8 bit tidak diringkas",
    "vide5551": "RGB 5551 (Endian Kecil) 16-bit tidak dikompresi",
    "videa2vy": "Komponen Dua-Bidang Y'CbCr 8-bit 4:2:2,4",
    "videABGR": "ABGR 32-bit tidak dikompresi",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Parameter Diatur dalam Bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Skala Abu-Abu 16 bit tidak diringkas",
    "videb32a": "AlphaGray 32-bit tidak dikompresi",
    "videb48r": "RGB 48-bit tidak dikompresi",
    "videb64a": "ARGB 64-bit tidak dikompresi",
    "videB565": "RGB 565 (Endian Besar) 16-bit tidak dikompresi",
    "videBGRA": "BGRA 32-bit tidak dikompresi",
    "videbhiv": "bhiv",
    "videblur": "Filter Konvolusi",
    "videcdh1": "Dolby Vision HEVC (dienkripsi)",
    "videclou": "Awan",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "Media AVC0",
    "videdslv": "Cross Fade",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "HEVC Dolby Vision",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filter Konvolusi",
    "videfire": "Api",
    "videfmns": "Filter Derau Film",
    "videgenk": "Filter Konvolusi",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 bit 4:2:2",
    "videhev1": "HEVC (Parameter Diatur dalam Bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Video Intel Indeo™ 4.3",
    "videIV50": "Video Indeo™ 5.1",
    "videjpeg": "Foto - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Pratinjau)",
    "videkpcd": "CD Foto",
    "videL555": "RGB 555 (Endian Kecil) 16-bit tidak dikompresi",
    "videL565": "RGB 565 (Endian Kecil) 16-bit tidak dikompresi",
    "vidematt": "Sapuan Gradien",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Video MPEG-1",
    "videmp2v": "Video MPEG-2",
    "videmp4v": "Video MPEG-4",
    "videmplo": "Meledak",
    "videmuxa": "HEVC dengan Alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/d)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/d)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/d)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/d)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/d)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/d)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Tidak Diketahui",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Video Pikslet Apple",
    "videqdh1": "Dolby Vision HEVC (dilindungi, MP4 terfragmentasi)",
    "vider210": "RGB 10 bit tidak diringkas",
    "vider408": "Komponen Y'CbCrA 8-bit 4:4:4:4 diurutkan AY' Cb Cr",
    "videRGBA": "RGBA 32-bit tidak dikompresi",
    "viderle ": "Animasi",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Filter Konvolusi",
    "videslid": "Push",
    "videsmc ": "Grafik",
    "videsmpt": "Menyapu",
    "videsolr": "Filter Penyeimbang Warna",
    "videSVQ1": "Video Sorenson",
    "videSVQ3": "Video Sorenson 3",
    "videtiff": "TIFF",
    "videtint": "Filter Penyeimbang Warna",
    "videtrav": "Mayang Bergerak",
    "videv210": "Komponen Y'CbCr 10-bit 4:2:2",
    "videv216": "Komponen Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Komponen Y'CbCr 8-bit 4:4:4",
    "videv408": "Komponen Y'CbCrA 8-bit 4:4:4:4 diurutkan Cb Y' Cr A",
    "videv410": "Komponen Y'CbCr 10-bit 4:4:4",
    "videVP31": "Video On2 VP3 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10 bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12 bit",
    "videxfg8": "XF-AVC GOP Panjang 4:2:2 8 bit",
    "videxfga": "XF-AVC GOP Panjang 4:2:2 10 bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8 bit",
    "videxfia": "XF-AVC Intra 4:2:2 10 bit",
    "videxplo": "Meledak",
    "videy420": "Komponen Tiga-Bidang Y'CbCr 8-bit 4:2:0",
    "videyuvs": "Komponen Y'CbCr 8-bit 4:2:2 diurutkan Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
