/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Скрытые субтитры",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Дорожка управления",
    "meta": "Метаданные",
    "metamebx": "Синхронизированные метаданные",
    "musimusi": "Музыка",
    "muxx": "Мультиплекс",
    "obje": "Объект QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Панорама VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Субтитры",
    "sbtldrmt": "Субтитры",
    "sbtltx3g": "Субтитры",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Тема",
    "skinskcr": "Тема",
    "skinskdr": "Тема",
    "soun": "Звук",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (зашифрованное)",
    "sounpaac": "AAC (защищенное)",
    "sounpac3": "AC‑3 Dolby Digital (защищенное)",
    "sounpach": "HE‑AACv1 (защищенное)",
    "sounpacp": "HE‑AACv2 (защищенное)",
    "sounpc+3": "Dolby Atmos (защищенное)",
    "sounpec3": "EC‑3 Dolby Digital+ (защищенное)",
    "sounqaac": "AAC (защищенное, сегментированный MP4)",
    "sounqac3": "AC‑3 Dolby Digital (защищенное, сегментированный MP4)",
    "sounqach": "HE‑AACv1 (защищенное, сегментированный MP4)",
    "sounqacp": "HE‑AACv2 (защищенное, сегментированный MP4)",
    "sounqc+3": "Dolby Atmos (защищенное, сегментированный MP4)",
    "sounqec3": "EC‑3 Dolby Digital+ (защищенное, сегментированный MP4)",
    "sounqlac": "Apple Lossless (защищенное, сегментированный MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (защищенное, транспортный поток)",
    "sounzac3": "AC‑3 Dolby Digital (защищенное, транспортный поток)",
    "sounzach": "HE‑AACv1 (защищенное, транспортный поток)",
    "sounzacp": "HE‑AACv2 (защищенное, транспортный поток)",
    "sounzc+3": "Dolby Atmos (защищенное, транспортный поток)",
    "sounzec3": "EC‑3 Dolby Digital+ (защищенное, транспортный поток)",
    "sounzlac": "Apple Lossless (защищенное, транспортный поток)",
    "sprt": "Спрайт",
    "strm": "Поток",
    "strmrtsp": "Поток",
    "text": "Текст",
    "texttext": "Текст QuickTime",
    "texttx3g": "Текст 3GPP",
    "tmcd": "Временной код",
    "tmcdtmcd": "Временной код",
    "tmet": "Синхронизированные метаданные",
    "twen": "Твин",
    "vide": "Видео",
    "vide1": "Без сжатия, 1 бит, индексированный цвет",
    "vide2": "Без сжатия, 2 бит, индексированный цвет",
    "vide2vuy": "Компонент Y'CbCr 8 бит 4:2:2; порядок Cb Y'0 Cr Y'1",
    "vide4": "Без сжатия, 4 бит, индексированный цвет",
    "vide8": "Без сжатия, 8 бит, индексированный цвет",
    "vide8BPS": "Плоский RGB",
    "vide16": "Без сжатия, 16 бит, RGB 555 (Big Endian)",
    "vide24": "Без сжатия, 24 бит, RGB",
    "vide24BG": "Без сжатия, 24 бит, BGR",
    "vide32": "Без сжатия, 32 бит, ARGB",
    "vide33": "Без сжатия, 1 бит, оттенки серого",
    "vide34": "Без сжатия, 2 бит, оттенки серого",
    "vide36": "Без сжатия, 4 бит, оттенки серого",
    "vide40": "Без сжатия, 8 бит, оттенки серого",
    "vide5551": "Без сжатия, 16 бит, RGB 5551 (Little Endian)",
    "videa2vy": "Двухмерный компонент Y'CbCr,A 8 бит 4:2:2,4",
    "videABGR": "Без сжатия, 32 бит, ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (наборы параметров в потоке)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Без сжатия, 16 бит, оттенки серого",
    "videb32a": "Без сжатия, 32 бит, AlphaGray",
    "videb48r": "Без сжатия, 48 бит, RGB",
    "videb64a": "Без сжатия, 64 бит, ARGB",
    "videB565": "Без сжатия, 16 бит, RGB 565 (Big Endian)",
    "videBGRA": "Без сжатия, 32 бит, BGRA",
    "videbhiv": "bhiv",
    "videblur": "Свертка",
    "videcdh1": "Dolby Vision HEVC (зашифрованное)",
    "videclou": "Облако",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Наплыв",
    "videdv5n": "DVCPRO50 — NTSC",
    "videdv5p": "DVCPRO50 — PAL",
    "videdvc ": "DV/DVCPRO — NTSC",
    "videdvcp": "DVC — PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO — PAL",
    "videEIDI": "EIDI",
    "videembs": "Свертка",
    "videfire": "Пламя",
    "videfmns": "Старая пленка",
    "videgenk": "Свертка",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC, 10 бит, 4:2:2",
    "videhev1": "HEVC (наборы параметров в потоке)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Видео Intel Indeo™ 4.3",
    "videIV50": "Видео Indeo™ 5.1",
    "videjpeg": "Фото — JPEG",
    "videJvt3": "Видео Apple H.264/AVC (предварительный просмотр)",
    "videkpcd": "Photo CD",
    "videL555": "Без сжатия, 16 бит, RGB 555 (Little Endian)",
    "videL565": "Без сжатия, 16 бит, RGB 565 (Little Endian)",
    "vidematt": "Градиентное стирание",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Видео MPEG-1",
    "videmp2v": "Видео MPEG-2",
    "videmp4v": "Видео MPEG-4",
    "videmplo": "Поглощение",
    "videmuxa": "HEVC с Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Мбит/с)",
    "videmx3p": "MPEG IMX 625/50 (30 Мбит/с)",
    "videmx4n": "MPEG IMX 525/60 (40 Мбит/с)",
    "videmx4p": "MPEG IMX 625/50 (40 Мбит/с)",
    "videmx5n": "MPEG IMX 525/60 (50 Мбит/с)",
    "videmx5p": "MPEG IMX 625/50 (50 Мбит/с)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Неизвестно",
    "videpng ": "PNG",
    "videpush": "Выталкивание",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (защищенное, сегментированный MP4)",
    "vider210": "Без сжатия, 10 бит, RGB",
    "vider408": "Компонент Y'CbCrA 8 бит 4:4:4:4; порядок A Y' Cb Cr",
    "videRGBA": "Без сжатия, 32 бит, RGBA",
    "viderle ": "Анимация",
    "viderpza": "Видео",
    "vides263": "H.263",
    "videshrp": "Свертка",
    "videslid": "Выталкивание",
    "videsmc ": "Графика",
    "videsmpt": "Стирание",
    "videsolr": "Баланс цвета",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Баланс цвета",
    "videtrav": "Блуждающая маска",
    "videv210": "Компонент Y'CbCr 10 бит 4:2:2",
    "videv216": "Компонент Y'CbCr 10,12,14,16 бит 4:2:2",
    "videv308": "Компонент Y'CbCr 8 бит 4:4:4",
    "videv408": "Компонент Y'CbCrA 8 бит 4:4:4:4; порядок Cb Y' Cr A",
    "videv410": "Компонент Y'CbCr 10 бит 4:4:4",
    "videVP31": "Видео On2 VP3 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10‑бит",
    "videxf4c": "XF-AVC Intra 4:4:4 12‑бит",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8‑бит",
    "videxfga": "XF-AVC Long GOP 4:2:2 10‑бит",
    "videxfi8": "XF-AVC Intra 4:2:2 8‑бит",
    "videxfia": "XF-AVC Intra 4:2:2 10‑бит",
    "videxplo": "Поглощение",
    "videy420": "Трехмерный компонент Y'CbCr 8 бит 4:2:0",
    "videyuvs": "Компонент Y'CbCr 8 бит 4:2:2; порядок Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
