/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "隐藏式字幕",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "分包",
    "meta": "元数据",
    "metamebx": "计时元数据",
    "musimusi": "音乐",
    "muxx": "混合",
    "obje": "QTVR物件",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR全景",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "字幕",
    "sbtldrmt": "字幕",
    "sbtltx3g": "字幕",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "外观",
    "skinskcr": "外观",
    "skinskdr": "外观",
    "soun": "声音",
    "sounalac": "Apple保真压缩",
    "sounclac": "Apple保真压缩（已加密）",
    "sounpaac": "AAC（受保护）",
    "sounpac3": "AC-3杜比数字（受保护）",
    "sounpach": "HE-AACv1（受保护）",
    "sounpacp": "HE-AACv2（受保护）",
    "sounpc+3": "杜比全景声（受保护）",
    "sounpec3": "EC-3杜比数字+（受保护）",
    "sounqaac": "AAC（受保护，fMP4）",
    "sounqac3": "AC-3杜比数字（受保护，fMP4）",
    "sounqach": "HE-AACv1（受保护，fMP4）",
    "sounqacp": "HE-AACv2（受保护，fMP4）",
    "sounqc+3": "杜比全景声（受保护，fMP4）",
    "sounqec3": "EC-3杜比数字+（受保护，fMP4）",
    "sounqlac": "Apple保真压缩（受保护，fMP4）",
    "sounvdva": "DV",
    "sounzaac": "AAC（受保护，传输流）",
    "sounzac3": "AC-3杜比数字（受保护，传输流）",
    "sounzach": "HE-AACv1（受保护，传输流）",
    "sounzacp": "HE-AACv2（受保护，传输流）",
    "sounzc+3": "杜比全景声（受保护，传输流）",
    "sounzec3": "EC-3杜比数字+（受保护，传输流）",
    "sounzlac": "Apple保真压缩（受保护，传输流）",
    "sprt": "角色",
    "strm": "流化",
    "strmrtsp": "流化",
    "text": "文本",
    "texttext": "QuickTime文本",
    "texttx3g": "3GPP文本",
    "tmcd": "时间码",
    "tmcdtmcd": "时间码",
    "tmet": "计时元数据",
    "twen": "中间帧",
    "vide": "视频",
    "vide1": "未压缩1位索引颜色",
    "vide2": "未压缩2位索引颜色",
    "vide2vuy": "组件Y'CbCr 8位4:2:2有序Cb Y'0 Cr Y'1",
    "vide4": "未压缩4位索引颜色",
    "vide8": "未压缩8位索引颜色",
    "vide8BPS": "Planar RGB",
    "vide16": "未压缩16位RGB 555（大端字节序）",
    "vide24": "未压缩24位RGB",
    "vide24BG": "未压缩24位BGR",
    "vide32": "未压缩32位ARGB",
    "vide33": "未压缩1位灰度",
    "vide34": "未压缩2位灰度",
    "vide36": "未压缩4位灰度",
    "vide40": "未压缩8位灰度",
    "vide5551": "未压缩16位RGB 5551（小端字节序）",
    "videa2vy": "二平面分量Y'CbCr,A 8位4:2:2,4",
    "videABGR": "未压缩32位ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264（比特流参数集）",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "未压缩16位灰度",
    "videb32a": "未压缩32位AlphaGray",
    "videb48r": "未压缩48位RGB",
    "videb64a": "未压缩64位ARGB",
    "videB565": "未压缩16位RGB 565（大端字节序）",
    "videBGRA": "未压缩32位BGRA",
    "videbhiv": "bhiv",
    "videblur": "卷积滤波",
    "videcdh1": "杜比视界HEVC（已加密）",
    "videclou": "云",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0媒体",
    "videdslv": "交叉淡出",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "杜比视界HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "卷积滤波",
    "videfire": "火焰",
    "videfmns": "影片杂波滤镜",
    "videgenk": "卷积滤波",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10位4:2:2",
    "videhev1": "HEVC（比特流参数集）",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "照片 - JPEG",
    "videJvt3": "Apple H.264/AVC视频（预览）",
    "videkpcd": "照片CD",
    "videL555": "未压缩16位RGB 555（小端字节序）",
    "videL565": "未压缩16位RGB 565（小端字节序）",
    "vidematt": "渐变擦除",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1视频",
    "videmp2v": "MPEG-2视频",
    "videmp4v": "MPEG-4视频",
    "videmplo": "内爆",
    "videmuxa": "含Alpha的HEVC",
    "videmx3n": "MPEG IMX 525/60（30 Mb/秒）",
    "videmx3p": "MPEG IMX 625/50（30 Mb/秒）",
    "videmx4n": "MPEG IMX 525/60（40 Mb/秒）",
    "videmx4p": "MPEG IMX 625/50（40 Mb/秒）",
    "videmx5n": "MPEG IMX 525/60（50 Mb/秒）",
    "videmx5p": "MPEG IMX 625/50（50 Mb/秒）",
    "VideoDynamicRangeDolbyVision": "杜比视界5",
    "VideoDynamicRangeDolbyVision8p4": "杜比视界8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "未知",
    "videpng ": "PNG",
    "videpush": "推移",
    "videpxlt": "Apple Pixlet视频",
    "videqdh1": "杜比视界HEVC（受保护，fMP4）",
    "vider210": "未压缩10位RGB",
    "vider408": "组件Y'CbCrA 8位4:4:4:4有序A Y' Cb Cr",
    "videRGBA": "未压缩32位RGBA",
    "viderle ": "动画",
    "viderpza": "视频",
    "vides263": "H.263",
    "videshrp": "卷积滤波",
    "videslid": "推移",
    "videsmc ": "图形",
    "videsmpt": "擦除",
    "videsolr": "颜色平衡滤镜",
    "videSVQ1": "Sorenson视频",
    "videSVQ3": "Sorenson视频3",
    "videtiff": "TIFF",
    "videtint": "颜色平衡滤镜",
    "videtrav": "移动遮片",
    "videv210": "组件Y'CbCr 10位4:2:2",
    "videv216": "分量Y'CbCr 10、12、14、16位4:2:2",
    "videv308": "组件Y'CbCr 8位4:4:4",
    "videv408": "组件Y'CbCrA 8位4:4:4:4有序Cb Y' Cr A",
    "videv410": "组件Y'CbCr 10位4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10位",
    "videxf4c": "XF-AVC Intra 4:4:4 12位",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8位",
    "videxfga": "XF-AVC Long GOP 4:2:2 10位",
    "videxfi8": "XF-AVC Intra 4:2:2 8位",
    "videxfia": "XF-AVC Intra 4:2:2 10位",
    "videxplo": "内爆",
    "videy420": "三平面分量Y'CbCr 8位4:2:0",
    "videyuvs": "组件Y'CbCr 8位4:2:2有序Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
