/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Skryté titulky",
    "clcpatcc": "ATSC/52 part‑4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Nápověda",
    "meta": "Metadata",
    "metamebx": "Časovaná metadata",
    "musimusi": "Hudba",
    "muxx": "Muxované",
    "obje": "QTVR objekt",
    "odsm": "MPEG‑4 ODSM",
    "odsmmp4s": "MPEG‑4 ODSM",
    "pano": "VR panoráma",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Titulky",
    "sbtldrmt": "Titulky",
    "sbtltx3g": "Titulky",
    "sdsm": "MPEG‑4 SDSM",
    "sdsmmp4s": "MPEG‑4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Zvuk",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (zašifrované)",
    "sounpaac": "AAC (chráněné)",
    "sounpac3": "AC‑3 Dolby Digital (chráněné)",
    "sounpach": "HE‑AACv1 (chráněné)",
    "sounpacp": "HE‑AACv2 (chráněné)",
    "sounpc+3": "Dolby Atmos (chráněné)",
    "sounpec3": "EC‑3 Dolby Digital+ (chráněné)",
    "sounqaac": "AAC (chráněné, fragmentované MP4)",
    "sounqac3": "AC‑3 Dolby Digital (chráněné, fragmentované MP4)",
    "sounqach": "HE‑AACv1 (chráněné, fragmentované MP4)",
    "sounqacp": "HE‑AACv2 (chráněné, fragmentované MP4)",
    "sounqc+3": "Dolby Atmos (chráněné, fragmentované MP4)",
    "sounqec3": "EC‑3 Dolby Digital+ (chráněné, fragmentované MP4)",
    "sounqlac": "Apple Lossless (chráněné, fragmentované MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (chráněné, přenosový stream)",
    "sounzac3": "AC‑3 Dolby Digital (chráněné, přenosový stream)",
    "sounzach": "HE‑AACv1 (chráněné, přenosový stream)",
    "sounzacp": "HE‑AACv2 (chráněné, přenosový stream)",
    "sounzc+3": "Dolby Atmos (chráněné, přenosový stream)",
    "sounzec3": "EC‑3 Dolby Digital+ (chráněné, přenosový stream)",
    "sounzlac": "Apple Lossless (chráněné, přenosový stream)",
    "sprt": "Sprite",
    "strm": "Streamování",
    "strmrtsp": "Streamování",
    "text": "Text",
    "texttext": "QuickTime Text",
    "texttx3g": "3GPP Text",
    "tmcd": "Časový kód",
    "tmcdtmcd": "Časový kód",
    "tmet": "Časovaná metadata",
    "twen": "Přechod",
    "vide": "Video",
    "vide1": "Nekomprimované 1bitové indexované barvy",
    "vide2": "Nekomprimované 2bitové indexované barvy",
    "vide2vuy": "Složkové Y'CbCr 8bitové 4:2:2 uspořádané Cb Y'0 Cr Y'1",
    "vide4": "Nekomprimované 4bitové indexované barvy",
    "vide8": "Nekomprimované 8bitové indexované barvy",
    "vide8BPS": "Planar RGB",
    "vide16": "Nekomprimované 16bitové RGB 555 (Big Endian)",
    "vide24": "Nekomprimované 24bitové RGB",
    "vide24BG": "Nekomprimované 24bitové BGR",
    "vide32": "Nekomprimované 32bitové ARGB",
    "vide33": "Nekomprimované 1bitové stupně šedi",
    "vide34": "Nekomprimované 2bitové stupně šedi",
    "vide36": "Nekomprimované 4bitové stupně šedi",
    "vide40": "Nekomprimované 8bitové stupně šedi",
    "vide5551": "Nekomprimované 16bitové RGB 5551 (Little Endian)",
    "videa2vy": "Dvouvrstvé složkové Y'CbCr,A 8bitové 4:2:2,4",
    "videABGR": "Nekomprimované 32bitové ABGR",
    "videACTL": "Streambox ACT‑L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (sady parametrů v bitstreamu)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Nekomprimované 16bitové stupně šedi",
    "videb32a": "Nekomprimované 32bitové AlphaGray",
    "videb48r": "Nekomprimované 48bitové RGB",
    "videb64a": "Nekomprimované 64bitové ARGB",
    "videB565": "Nekomprimované 16bitové RGB 565 (Big Endian)",
    "videBGRA": "Nekomprimované 32bitové BGRA",
    "videbhiv": "bhiv",
    "videblur": "Konvoluční filtr",
    "videcdh1": "Dolby Vision HEVC (zašifrované)",
    "videclou": "Mrak",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 média",
    "videdslv": "Prolnutí",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Konvoluční filtr",
    "videfire": "Oheň",
    "videfmns": "Filtr Poškozený film",
    "videgenk": "Konvoluční filtr",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "10bitový HEVC 4:2:2",
    "videhev1": "HEVC (sady parametrů v bitstreamu)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Photo - JPEG",
    "videJvt3": "Apple H.264/AVC video (náhled)",
    "videkpcd": "Photo CD",
    "videL555": "Nekomprimované 16bitové RGB 555 (Little Endian)",
    "videL565": "Nekomprimované 16bitové RGB 565 (Little Endian)",
    "vidematt": "Postupné setření",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG‑1 video",
    "videmp2v": "MPEG‑2 video",
    "videmp4v": "MPEG‑4 video",
    "videmplo": "Imploze",
    "videmuxa": "HEVC s alfa kanálem",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Není známo",
    "videpng ": "PNG",
    "videpush": "Odsunutí",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (chráněné, fragmentované MP4)",
    "vider210": "Nekomprimované 10bitové RGB",
    "vider408": "Složkové Y'CbCrA 8bitové 4:4:4:4 uspořádané A Y' Cb Cr",
    "videRGBA": "Nekomprimované 32bitové RGBA",
    "viderle ": "Animace",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Konvoluční filtr",
    "videslid": "Odsunutí",
    "videsmc ": "Grafika",
    "videsmpt": "Setření",
    "videsolr": "Filtr Vyvážení barev",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filtr Vyvážení barev",
    "videtrav": "Pohyblivá maska",
    "videv210": "Složkové Y'CbCr 10bitové 4:2:2",
    "videv216": "Složkové Y'CbCr 10,12,14,16bitové 4:2:2",
    "videv308": "Složkové Y'CbCr 8bitové 4:4:4",
    "videv408": "Složkové Y'CbCrA 8bitové 4:4:4:4 uspořádané Cb Y' Cr A",
    "videv410": "Složkové Y'CbCr 10bitové 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Imploze",
    "videy420": "Třívrstvé složkové Y'CbCr 8bitové 4:2:0",
    "videyuvs": "Složkové Y'CbCr 8bitové 4:2:2 uspořádané Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
