/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "隱藏式字幕",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "分封指示",
    "meta": "後設資料",
    "metamebx": "計時後設資料",
    "musimusi": "音樂",
    "muxx": "混合",
    "obje": "QTVR物件",
    "odsm": "MPEG-4 ODSM ",
    "odsmmp4s": "MPEG-4 ODSM ",
    "pano": "VR全景",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "字幕",
    "sbtldrmt": "字幕",
    "sbtltx3g": "字幕",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "外觀介面",
    "skinskcr": "外觀介面",
    "skinskdr": "外觀介面",
    "soun": "聲音",
    "sounalac": "Apple保真壓縮",
    "sounclac": "Apple保真壓縮（已加密）",
    "sounpaac": "AAC（版權保護）",
    "sounpac3": "AC-3杜比數位（版權保護）",
    "sounpach": "HE-AACv1（版權保護）",
    "sounpacp": "HE-AACv2（版權保護）",
    "sounpc+3": "杜比全景聲（版權保護）",
    "sounpec3": "EC-3杜比數位+（版權保護）",
    "sounqaac": "AAC（版權保護、分散式MP4）",
    "sounqac3": "AC-3杜比數位（版權保護、分散式MP4）",
    "sounqach": "HE-AACv1（版權保護、分散式MP4）",
    "sounqacp": "HE-AACv2（版權保護、分散式MP4）",
    "sounqc+3": "杜比全景聲（版權保護、分散式MP4）",
    "sounqec3": "EC-3杜比數位+（版權保護、分散式MP4）",
    "sounqlac": "Apple保真壓縮（版權保護、分散式MP4）",
    "sounvdva": "DV",
    "sounzaac": "AAC（版權保護、傳輸串流）",
    "sounzac3": "AC-3杜比數位（版權保護、傳輸串流）",
    "sounzach": "HE-AACv1（版權保護、傳輸串流）",
    "sounzacp": "HE-AACv2（版權保護、傳輸串流）",
    "sounzc+3": "杜比全景聲（版權保護、傳輸串流）",
    "sounzec3": "EC-3杜比數位+（版權保護、傳輸串流）",
    "sounzlac": "Apple保真壓縮（版權保護、傳輸串流）",
    "sprt": "動畫拼合",
    "strm": "串流",
    "strmrtsp": "串流",
    "text": "文字",
    "texttext": "QuickTime文字",
    "texttx3g": "3GPP文字",
    "tmcd": "時間碼",
    "tmcdtmcd": "時間碼",
    "tmet": "計時後設資料",
    "twen": "軌跡動作",
    "vide": "影片",
    "vide1": "未壓縮1位元索引色",
    "vide2": "未壓縮2位元索引色",
    "vide2vuy": "色差端子Y'CbCr 8位元4:2:2順序Cb Y'0 Cr Y'1",
    "vide4": "未壓縮4位元索引色",
    "vide8": "未壓縮8位元索引色",
    "vide8BPS": "Planar RGB",
    "vide16": "未壓縮16位元RGB 555（高位元排序）",
    "vide24": "未壓縮24位元RGB",
    "vide24BG": "未壓縮24位元BGR",
    "vide32": "未壓縮32位元ARGB",
    "vide33": "未壓縮1位元灰階",
    "vide34": "未壓縮2位元灰階",
    "vide36": "未壓縮4位元灰階",
    "vide40": "未壓縮8位元灰階",
    "vide5551": "未壓縮16位元RGB 5551（低位元排序）",
    "videa2vy": "雙平面色差端子Y'CbCr,A 8位元4:2:2,4",
    "videABGR": "未壓縮32位元ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422代理伺服器",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264（位元串流參數組）",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "未壓縮16位元灰階",
    "videb32a": "未壓縮32位元AlphaGray",
    "videb48r": "未壓縮48位元RGB",
    "videb64a": "未壓縮64位元ARGB",
    "videB565": "未壓縮16位元RGB 565（高位元排序）",
    "videBGRA": "未壓縮32位元BGRA",
    "videbhiv": "bhiv",
    "videblur": "卷積濾鏡",
    "videcdh1": "杜比視界HEVC（已加密）",
    "videclou": "雲端",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0媒體",
    "videdslv": "交疊淡出",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "杜比視界HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "卷積濾鏡",
    "videfire": "火焰",
    "videfmns": "影片雜訊濾鏡",
    "videgenk": "卷積濾鏡",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10位元4:2:2",
    "videhev1": "HEVC（位元串流參數組）",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "照片 - JPEG",
    "videJvt3": "Apple H.264/AVC影片（預覽）",
    "videkpcd": "Photo CD",
    "videL555": "未壓縮16位元RGB 555（低位元排序）",
    "videL565": "未壓縮16位元RGB 565（低位元排序）",
    "vidematt": "漸變移除",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1影片",
    "videmp2v": "MPEG-2影片",
    "videmp4v": "MPEG-4影片",
    "videmplo": "向內收縮",
    "videmuxa": "帶有Alpha的HEVC",
    "videmx3n": "MPEG IMX 525/60（30 Mb/秒）",
    "videmx3p": "MPEG IMX 625/50（30 Mb/秒）",
    "videmx4n": "MPEG IMX 525/60（40 Mb/秒）",
    "videmx4p": "MPEG IMX 625/50（40 Mb/秒）",
    "videmx5n": "MPEG IMX 525/60（50 Mb/秒）",
    "videmx5p": "MPEG IMX 625/50（50 Mb/秒）",
    "VideoDynamicRangeDolbyVision": "杜比視界5",
    "VideoDynamicRangeDolbyVision8p4": "杜比視界8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "未知",
    "videpng ": "PNG",
    "videpush": "推播",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "杜比視界HEVC（版權保護、分散式MP4）",
    "vider210": "未壓縮10位元RGB",
    "vider408": "色差端子Y'CbCrA 8位元4:4:4:4順序A Y' Cb Cr",
    "videRGBA": "未壓縮32位元RGBA",
    "viderle ": "動畫",
    "viderpza": "影片",
    "vides263": "H.263",
    "videshrp": "卷積濾鏡",
    "videslid": "推播",
    "videsmc ": "圖形",
    "videsmpt": "移除",
    "videsolr": "色彩平衡濾鏡",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "色彩平衡濾鏡",
    "videtrav": "滑動遮罩",
    "videv210": "色差端子Y'CbCr 10位元4:2:2",
    "videv216": "色差端子Y'CbCr 10、12、14、16位元4:2:2",
    "videv308": "色差端子Y'CbCr 8位元4:4:4",
    "videv408": "色差端子Y'CbCrA 8位元4:4:4:4順序Cb Y' Cr A",
    "videv410": "色差端子Y'CbCr 10位元4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10位元",
    "videxf4c": "XF-AVC Intra 4:4:4 12位元",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8位元",
    "videxfga": "XF-AVC Long GOP 4:2:2 10位元",
    "videxfi8": "XF-AVC Intra 4:2:2 8位元",
    "videxfia": "XF-AVC Intra 4:2:2 10位元",
    "videxplo": "向內收縮",
    "videy420": "三平面色差端子Y'CbCr 8位元4:2:0",
    "videyuvs": "色差端子Y'CbCr 8位元4:2:2順序Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
