/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "क्लोज़्ड कैप्शन",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "संकेत",
    "meta": "मेटाडेटा",
    "metamebx": "टाइम्ड मेटाडेटा",
    "musimusi": "संगीत",
    "muxx": "बहुसंकेतीय",
    "obje": "QTVR ऑब्जेक्ट",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR पैनोरमा",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "सबटाइटल",
    "sbtldrmt": "सबटाइटल",
    "sbtltx3g": "सबटाइटल",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "आवरण",
    "skinskcr": "आवरण",
    "skinskdr": "आवरण",
    "soun": "ध्वनि",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (एंक्रिप्टेड)",
    "sounpaac": "AAC (सुरक्षित)",
    "sounpac3": "AC-3 Dolby Digital (संरक्षित)",
    "sounpach": "HE-AACv1 (संरक्षित)",
    "sounpacp": "HE-AACv2 (संरक्षित)",
    "sounpc+3": "Dolby Atmos (संरक्षित)",
    "sounpec3": "EC-3 Dolby Digital+ (संरक्षित)",
    "sounqaac": "AAC (संरक्षित, फ़्रैगमेंटेड MP4)",
    "sounqac3": "AC-3 Dolby Digital (संरक्षित, फ़्रैगमेंटेड MP4)",
    "sounqach": "HE-AACv1 (संरक्षित, फ़्रैगमेंटेड MP4)",
    "sounqacp": "HE-AACv2 (संरक्षित, फ़्रैगमेंटेड MP4)",
    "sounqc+3": "Dolby Atmos (संरक्षित, फ़्रैगमेंटेड MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (संरक्षित, फ़्रैगमेंटेड MP4)",
    "sounqlac": "Apple Lossless (संरक्षित, फ़्रैगमेंटेड MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (संरक्षित, ट्रांसपोर्ट स्ट्रीम)",
    "sounzac3": "AC-3 Dolby Digital (संरक्षित, ट्रांसपोर्ट स्ट्रीम)",
    "sounzach": "HE-AACv1 (संरक्षित, ट्रांसपोर्ट स्ट्रीम)",
    "sounzacp": "HE-AACv2 (संरक्षित, ट्रांसपोर्ट स्ट्रीम)",
    "sounzc+3": "Dolby Atmos (संरक्षित, ट्रांसपोर्ट स्ट्रीम)",
    "sounzec3": "EC-3 Dolby Digital+ (संरक्षित, ट्रांसपोर्ट स्ट्रीम)",
    "sounzlac": "Apple Lossless (संरक्षित, ट्रांसपोर्ट स्ट्रीम)",
    "sprt": "स्पिरिट",
    "strm": "स्ट्रीमिंग",
    "strmrtsp": "स्ट्रीमिंग",
    "text": "टेक्स्ट",
    "texttext": "QuickTime टेक्स्ट",
    "texttx3g": "3GPP टेक्स्ट",
    "tmcd": "टाइमकोड",
    "tmcdtmcd": "टाइमकोड",
    "tmet": "टाइम्ड मेटाडेटा",
    "twen": "ट्वीन",
    "vide": "वीडियो",
    "vide1": "अनकंप्रेस्ड 1-बिट अनुक्रमणित रंग",
    "vide2": "अनकंप्रेस्ड 2-बिट अनुक्रमणित रंग",
    "vide2vuy": "कंपोनेंट Y'CbCr 8-बिट 4:2:2 क्रमित Cb Y'0 Cr Y'1",
    "vide4": "अनकंप्रेस्ड 4-बिट अनुक्रमणित रंग",
    "vide8": "अनकंप्रेस्ड 8-बिट अनुक्रमणित रंग",
    "vide8BPS": "समतल RGB",
    "vide16": "अनकंप्रेस्ड 16-बिट RGB 555 (बिग एंडियन)",
    "vide24": "अनकंप्रेस्ड 24-बिट RGB",
    "vide24BG": "अनकंप्रेस्ड 24-बिट BGR",
    "vide32": "अनकंप्रेस्ड 32-बिट ARGB",
    "vide33": "अनकंप्रेस्ड 1-बिट ग्रेस्केल",
    "vide34": "अनकंप्रेस्ड 2-बिट ग्रेस्केल",
    "vide36": "अनकंप्रेस्ड 4-बिट ग्रेस्केल",
    "vide40": "अनकंप्रेस्ड 8-बिट ग्रेस्केल",
    "vide5551": "अनकंप्रेस्ड 16-बिट RGB 5551 (लिटिल एंडियन)",
    "videa2vy": "द्वि-तलीय कंपोनेंट Y'CbCr,A 8-बिट 4:2:2,4",
    "videABGR": "अनकंप्रेस्ड 32-बिट ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (मानदंड बिटस्ट्रीम में सेट होता है)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "अनकंप्रेस्ड 16-बिट ग्रेस्केल",
    "videb32a": "अनकंप्रेस्ड 32-बिट अल्फ़ाग्रे",
    "videb48r": "अनकंप्रेस्ड 48-बिट RGB",
    "videb64a": "अनकंप्रेस्ड 64-बिट ARGB",
    "videB565": "अनकंप्रेस्ड 16-बिट RGB 565 (बिग एंडियन)",
    "videBGRA": "अनकंप्रेस्ड 32-बिट BGRA",
    "videbhiv": "bhiv",
    "videblur": "घुमाव फ़िल्टर",
    "videcdh1": "Dolby Vision HEVC (एंक्रिप्टेड)",
    "videclou": "क्लाउड",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 मीडिया",
    "videdslv": "क्रॉस फ़ेड",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "घुमाव फ़िल्टर",
    "videfire": "आग",
    "videfmns": "फ़िल्म नॉइज़ फ़िल्टर",
    "videgenk": "घुमाव फ़िल्टर",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-बिट 4:2:2",
    "videhev1": "HEVC (मानदंड बिटस्ट्रीम में सेट होता है)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "तस्वीर - JPEG",
    "videJvt3": "Apple H.264/AVC वीडियो (प्रीव्यू)",
    "videkpcd": "Photo CD",
    "videL555": "अनकंप्रेस्ड 16-बिट RGB 555 (लिटिल एंडियन)",
    "videL565": "अनकंप्रेस्ड 16-बिट RGB 565 (लिटिल एंडियन)",
    "vidematt": "ग्रेडिएंट वाइप",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 वीडियो",
    "videmp2v": "MPEG-2 वीडियो",
    "videmp4v": "MPEG-4 वीडियो",
    "videmplo": "इंप्लोड",
    "videmuxa": "अल्फ़ा के साथ HEVC",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "अज्ञात",
    "videpng ": "PNG",
    "videpush": "पुश",
    "videpxlt": "Apple Pixlet वीडियो",
    "videqdh1": "Dolby Vision HEVC (संरक्षित, फ़्रैगमेंटेड MP4)",
    "vider210": "अनकंप्रेस्ड 10-बिट RGB",
    "vider408": "कंपोनेंट Y'CbCrA 8-बिट 4:4:4:4 क्रमित A Y' Cb Cr",
    "videRGBA": "अनकंप्रेस्ड 32-बिट RGBA",
    "viderle ": "ऐनिमेशन",
    "viderpza": "वीडियो",
    "vides263": "H.263",
    "videshrp": "घुमाव फ़िल्टर",
    "videslid": "पुश",
    "videsmc ": "ग्राफ़िक्स",
    "videsmpt": "वाइप",
    "videsolr": "रंग संतुलन फ़िल्टर",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "रंग संतुलन फ़िल्टर",
    "videtrav": "ट्रैवलिंग मैटे",
    "videv210": "कंपोनेंट Y'CbCr 10-बिट 4:2:2",
    "videv216": "कंपोनेंट Y'CbCr 10,12,14,16-बिट 4:2:2",
    "videv308": "कंपोनेंट Y'CbCr 8-बिट 4:4:4",
    "videv408": "कंपोनेंट Y'CbCrA 8-बिट 4:4:4:4 क्रमित Cb Y' Cr A",
    "videv410": "कंपोनेंट Y'CbCr 10-बिट 4:4:4",
    "videVP31": "On2 VP3 वीडियो 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "इंप्लोड",
    "videy420": "त्रि-तलीय कंपोनेंट Y'CbCr 8-बिट 4:2:0",
    "videyuvs": "कंपोनेंट Y'CbCr 8-बिट 4:2:2 क्रमित Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
