/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Bijschriften geluid",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Hint",
    "meta": "Metadata",
    "metamebx": "Timed metadata",
    "musimusi": "Muziek",
    "muxx": "Muxed",
    "obje": "QTVR-object",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR-panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Ondertiteling",
    "sbtldrmt": "Ondertiteling",
    "sbtltx3g": "Ondertiteling",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Geluid",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (versleuteld)",
    "sounpaac": "AAC (beveiligd)",
    "sounpac3": "AC-3 Dolby Digital (beveiligd)",
    "sounpach": "HE-AACv1 (beveiligd)",
    "sounpacp": "HE-AACv2 (beveiligd)",
    "sounpc+3": "Dolby Atmos (beveiligd)",
    "sounpec3": "EC-3 Dolby Digital+ (beveiligd)",
    "sounqaac": "AAC (beveiligde, gefragmenteerde MP4)",
    "sounqac3": "AC-3 Dolby Digital (beveiligde, gefragmenteerde MP4)",
    "sounqach": "HE-AACv1 (beveiligde, gefragmenteerde MP4)",
    "sounqacp": "HE-AACv2 (beveiligde, gefragmenteerde MP4)",
    "sounqc+3": "Dolby Atmos (beveiligde, gefragmenteerde MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (beveiligde, gefragmenteerde MP4)",
    "sounqlac": "Apple Lossless (beveiligde, gefragmenteerde MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (beveiligd, transportstream)",
    "sounzac3": "AC-3 Dolby Digital (beveiligd, transportstream)",
    "sounzach": "HE-AACv1 (beveiligd, transportstream)",
    "sounzacp": "HE-AACv2 (beveiligd, transportstream)",
    "sounzc+3": "Dolby Atmos (beveiligd, transportstream)",
    "sounzec3": "EC-3 Dolby Digital+ (beveiligd, transportstream)",
    "sounzlac": "Apple Lossless (beveiligd, transportstream)",
    "sprt": "Sprite",
    "strm": "Streaming",
    "strmrtsp": "Streaming",
    "text": "Tekst",
    "texttext": "QuickTime-tekst",
    "texttx3g": "3GPP-tekst",
    "tmcd": "Tijdcode",
    "tmcdtmcd": "Tijdcode",
    "tmet": "Timed metadata",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Ongecomprimeerd, 1-bits geïndexeerde kleuren",
    "vide2": "Ongecomprimeerd, 2-bits geïndexeerde kleuren",
    "vide2vuy": "Component Y'CbCr 8-bits 4:2:2 geordend Cb Y'0 Cr Y'1",
    "vide4": "Ongecomprimeerd, 4-bits geïndexeerde kleuren",
    "vide8": "Ongecomprimeerd, 8-bits geïndexeerde kleuren",
    "vide8BPS": "Planar RGB",
    "vide16": "Ongecomprimeerd, 16-bits RGB 555 (Big Endian)",
    "vide24": "Ongecomprimeerd, 24-bits RGB",
    "vide24BG": "Ongecomprimeerd, 24-bits BGR",
    "vide32": "Ongecomprimeerd, 32-bits ARGB",
    "vide33": "Ongecomprimeerd, 1-bits grijsschaal",
    "vide34": "Ongecomprimeerd, 2-bits grijsschaal",
    "vide36": "Ongecomprimeerd, 4-bits grijsschaal",
    "vide40": "Ongecomprimeerd, 8-bits grijsschaal",
    "vide5551": "Ongecomprimeerd, 16-bits RGB 5551 (Little Endian)",
    "videa2vy": "Tweevlakscomponent Y'CbCr,A 8-bits 4:2:2,4",
    "videABGR": "Ongecomprimeerd, 32-bits ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (parametersets in bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Ongecomprimeerd, 16-bits grijsschaal",
    "videb32a": "Ongecomprimeerd, 32-bits AlfaGrijs",
    "videb48r": "Ongecomprimeerd, 48-bits RGB",
    "videb64a": "Ongecomprimeerd, 64-bits ARGB",
    "videB565": "Ongecomprimeerd, 16-bits RGB 565 (Big Endian)",
    "videBGRA": "Ongecomprimeerd, 32-bits BGRA",
    "videbhiv": "bhiv",
    "videblur": "Convolutiefilter",
    "videcdh1": "Dolby Vision HEVC (versleuteld)",
    "videclou": "Wolk",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0-media",
    "videdslv": "Overvloeien",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Convolutiefilter",
    "videfire": "Brand",
    "videfmns": "Filmruisfilter",
    "videgenk": "Convolutiefilter",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bits 4:2:2",
    "videhev1": "HEVC (parametersets in bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Photo - JPEG",
    "videJvt3": "Apple H.264/AVC-video (voorvertoning)",
    "videkpcd": "Photo CD",
    "videL555": "Ongecomprimeerd, 16-bits RGB 555 (Little Endian)",
    "videL565": "Ongecomprimeerd, 16-bits RGB 565 (Little Endian)",
    "vidematt": "Geleidelijk vegen",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1-video",
    "videmp2v": "MPEG-2-video",
    "videmp4v": "MPEG-4-video",
    "videmplo": "Implosie",
    "videmuxa": "HEVC met alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/sec)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/sec)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/sec)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/sec)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/sec)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/sec)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Onbekend",
    "videpng ": "PNG",
    "videpush": "Duwen",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (beveiligde, gefragmenteerde MP4)",
    "vider210": "Ongecomprimeerd 10-bits RGB",
    "vider408": "Component Y'CbCrA 8-bits 4:4:4:4 geordend A Y' Cb Cr",
    "videRGBA": "Ongecomprimeerd, 32-bits RGBA",
    "viderle ": "Animatie",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Convolutiefilter",
    "videslid": "Duwen",
    "videsmc ": "Illustraties",
    "videsmpt": "Uitwissen",
    "videsolr": "Kleurbalansfilter",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Kleurbalansfilter",
    "videtrav": "Bewegend masker",
    "videv210": "Component Y'CbCr 10-bits 4:2:2",
    "videv216": "Component Y'CbCr 10,12,14,16-bits 4:2:2",
    "videv308": "Component Y'CbCr 8-bits 4:4:4",
    "videv408": "Component Y'CbCrA 8-bits 4:4:4:4 geordend Cb Y' Cr A",
    "videv410": "Component Y'CbCr 10-bits 4:4:4",
    "videVP31": "On2 VP3-video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bits",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bits",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bits",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bits",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bits",
    "videxfia": "XF-AVC Intra 4:2:2 10-bits",
    "videxplo": "Implosie",
    "videy420": "Drievlakscomponent Y'CbCr 8-bits 4:2:0",
    "videyuvs": "Component Y'CbCr 8-bits 4:2:2 geordend Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
