/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "כתוביות",
    "clcpatcc": "‏ATSC/52 חלק 4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "רמז",
    "meta": "מטא-נתונים",
    "metamebx": "מטא-נתונים מתוזמנים",
    "musimusi": "מוזיקה",
    "muxx": "מרובב",
    "obje": "אובייקט QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "פנורמת VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "כתובית",
    "sbtldrmt": "כתובית",
    "sbtltx3g": "כתובית",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "מעטפת",
    "skinskcr": "מעטפת",
    "skinskdr": "מעטפת",
    "soun": "צליל",
    "sounalac": "‏Apple Lossless",
    "sounclac": "‏Apple Lossless (מוצפן)",
    "sounpaac": "‏AAC (מוגן)",
    "sounpac3": "‏AC-3 Dolby Digital (מוגן)",
    "sounpach": "‏HE-AACv1 (מוגן)",
    "sounpacp": "‏HE-AACv2 (מוגן)",
    "sounpc+3": "‏Dolby Atmos (מוגן)",
    "sounpec3": "‏⁨EC-3 Dolby Digital+⁩ (מוגן)",
    "sounqaac": "‏AAC (מוגן, MP4 מפוצל)",
    "sounqac3": "‏AC-3 Dolby Digital (מוגן, MP4 מפוצל)",
    "sounqach": "‏HE-AACv1 (מוגן, MP4 מפוצל)",
    "sounqacp": "‏HE-AACv2 (מוגן, MP4 מפוצל)",
    "sounqc+3": "‏Dolby Atmos (מוגן, MP4 מפוצל)",
    "sounqec3": "‏⁨EC-3 Dolby Digital+⁩ (מוגן, MP4 מפוצל)",
    "sounqlac": "‏Apple Lossless (מוגן, MP4 מפוצל)",
    "sounvdva": "DV",
    "sounzaac": "‏AAC (מוגן, זרם הובלה)",
    "sounzac3": "‏AC-3 Dolby Digital (מוגן, זרם הובלה)",
    "sounzach": "‏HE-AACv1 (מוגן, זרם הובלה)",
    "sounzacp": "‏HE-AACv2 (מוגן, זרם הובלה)",
    "sounzc+3": "‏Dolby Atmos (מוגן, זרם הובלה)",
    "sounzec3": "‏⁨EC-3 Dolby Digital+⁩ (מוגן, זרם הובלה)",
    "sounzlac": "‏Apple Lossless (מוגן, זרם הובלה)",
    "sprt": "גרפיקת ספרייט",
    "strm": "הזרמה",
    "strmrtsp": "הזרמה",
    "text": "מלל",
    "texttext": "מלל של QuickTime",
    "texttx3g": "3GPP מלל",
    "tmcd": "חותמת זמן",
    "tmcdtmcd": "חותמת זמן",
    "tmet": "מטא-נתונים מתוזמנים",
    "twen": "טווין",
    "vide": "סרטון",
    "vide1": "צבע בעל אינדקס של סיבית אחת ללא דחיסה",
    "vide2": "צבע בעל אינדקס של שתי סיביות ללא דחיסה",
    "vide2vuy": "קומפוננט Y'CbCr‏ 8 סיביות 4:2:2 מסודר Cb Y'0 Cr Y'1",
    "vide4": "צבע בעל אינדקס של 4 סיביות ללא דחיסה",
    "vide8": "צבע בעל אינדקס של 8 סיביות ללא דחיסה",
    "vide8BPS": "‏RGB מישורי",
    "vide16": "‏RGB 555 של 16 סיביות ללא דחיסה (Big Endian)",
    "vide24": "‏RGB של 24 סיביות ללא דחיסה",
    "vide24BG": "‏BGR של 24 סיביות ללא דחיסה",
    "vide32": "‏ARGB של 32 סיביות ללא דחיסה",
    "vide33": "גווני אפור - סיבית אחת, לא מכווץ",
    "vide34": "גווני אפור של שתי סיביות ללא דחיסה",
    "vide36": "גווני אפור של 4 סיביות ללא דחיסה",
    "vide40": "גווני אפור - 8 סיביות, לא מכווץ",
    "vide5551": "‏RGB 5551 של 16 סיביות ללא דחיסה (Little Endian)",
    "videa2vy": "קומפוננט דו-מישורי Y'CbCr,A‏ 8 סיביות 4:2:2,4",
    "videABGR": "‏ABGR של 32 סיביות ללא דחיסה",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "‏Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "‏H.264 (קבוצות פרמטרים בזרם הסיביות)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "גווני אפור של 16 סיביות ללא דחיסה",
    "videb32a": "אלפא-אפור של 32 סיביות ללא דחיסה",
    "videb48r": "‏RGB של 48 סיביות ללא דחיסה",
    "videb64a": "‏ARGB של 64 סיביות ללא דחיסה",
    "videB565": "‏RGB 565 של 16 סיביות ללא דחיסה (Big Endian)",
    "videBGRA": "‏BGRA של 32 סיביות ללא דחיסה",
    "videbhiv": "bhiv",
    "videblur": "מסנן קונבולוציה",
    "videcdh1": "‏Dolby Vision HEVC (מוצפן)",
    "videclou": "ענן",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "מדיית AVC0",
    "videdslv": "מעבר הדרגתי",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "‏Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)‎",
    "videdvh3": "DVCPRO HD (1080p30)‎",
    "videdvh5": "‏DVCPRO HD ‏(1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)‎",
    "videdvhp": "DVCPRO HD (720p60)‎",
    "videdvhq": "DVCPRO HD (720p50)‎",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "מסנן קונבולוציה",
    "videfire": "אש",
    "videfmns": "מסנן לסינון רעשים בסרט",
    "videgenk": "מסנן קונבולוציה",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "‏HEVC 10-bit 4:2:2",
    "videhev1": "‏HEVC (קבוצות פרמטרים בזרם הסיביות)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ Video 5.1",
    "videjpeg": "תמונה - JPEG",
    "videJvt3": "‏Apple H.264/AVC Video (תצוגה מקדימה)",
    "videkpcd": "תקליטור CD של תמונות",
    "videL555": "‏RGB 555 של 16 סיביות ללא דחיסה (Little Endian)",
    "videL565": "‏RGB 565 של 16 סיביות ללא דחיסה (Little Endian)",
    "vidematt": "ניגוב הדרגתי",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "וידאו MPEG-1",
    "videmp2v": "וידאו MPEG-2",
    "videmp4v": "סרט MPEG-4",
    "videmplo": "קריסה פנימה",
    "videmuxa": "‏HEVC עם אלפא",
    "videmx3n": "‏MPEG IMX 525/60 (‏30 מ״ב/שנייה)",
    "videmx3p": "‏MPEG IMX 625/50 (‏30 מ״ב/שנייה)",
    "videmx4n": "‏MPEG IMX 525/60 (‏40 מ״ב/שנייה)",
    "videmx4p": "‏MPEG IMX 625/50 (‏40 מ״ב/שנייה)",
    "videmx5n": "‏MPEG IMX 525/60 (‏50 מ״ב/שנייה)",
    "videmx5p": "‏MPEG IMX 625/50 (‏50 מ״ב/שנייה)",
    "VideoDynamicRangeDolbyVision": "‏Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "‏Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "‏SDR",
    "VideoDynamicRangeUnknown": "לא ידוע",
    "videpng ": "PNG",
    "videpush": "‏Push",
    "videpxlt": "סרט Apple Pixlet",
    "videqdh1": "‏Dolby Vision HEVC (מוגן, MP4 מפוצל)",
    "vider210": "‏RGB‏ 10 סיביות לא מכווץ",
    "vider408": "קומפוננט Y'CbCrA‏ 8 סיביות 4:4:4:4 מסודר A Y' Cb Cr",
    "videRGBA": "‏RGBA של 32 סיביות ללא דחיסה",
    "viderle ": "אנימציה",
    "viderpza": "סרטון",
    "vides263": "H.263",
    "videshrp": "מסנן קונבולוציה",
    "videslid": "‏Push",
    "videsmc ": "גרפיקה",
    "videsmpt": "ניגוב",
    "videsolr": "מסנן איזון צבעים",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "מסנן איזון צבעים",
    "videtrav": "מט נע",
    "videv210": "קומפוננט Y'CbCr‏ 10 סיביות 4:2:2",
    "videv216": "קומפוננט Y'CbCr‏ 10,‏12,‏14,‏16 סיביות 4:2:2",
    "videv308": "קומפוננט Y'CbCr‏ 8 סיביות 4:4:4",
    "videv408": "קומפוננט Y'CbCrA‏ 8 סיביות 4:4:4:4 מסודר Cb Y' Cr A",
    "videv410": "קומפוננט Y'CbCr‏ 10 סיביות 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "‏XF-AVC Intra 4:4:4 ‏10-סיביות",
    "videxf4c": "‏XF-AVC Intra 4:4:4 ‏12-סיביות",
    "videxfg8": "‏XF-AVC LONG GOP 4:2:2 ‏8-סיביות",
    "videxfga": "‏XF-AVC LONG GOP 4:2:2 ‏10-סיביות",
    "videxfi8": "‏XF-AVC Intra 4:2:2 ‏8-סיביות",
    "videxfia": "‏XF-AVC Intra 4:2:2 ‏10-סיביות",
    "videxplo": "קריסה פנימה",
    "videy420": "קומפוננט תלת-מישורי Y'CbCr‏ 8 סיביות 4:2:0",
    "videyuvs": "קומפוננט Y'CbCr‏ 8 סיביות 4:2:2 מסודר Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
