/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Amb subtítols",
    "clcpatcc": "ATSC/52 de 4 parts",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Indicació",
    "meta": "Metadades",
    "metamebx": "Metadades temporals",
    "musimusi": "Música",
    "muxx": "Multiplexat",
    "obje": "Objecte QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Subtítol",
    "sbtldrmt": "Subtítol",
    "sbtltx3g": "Subtítol",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Aparença",
    "skinskcr": "Aparença",
    "skinskdr": "Aparença",
    "soun": "So",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (encriptat)",
    "sounpaac": "AAC (protegit)",
    "sounpac3": "AC‑3 Dolby Digital (protegit)",
    "sounpach": "HE‑AACv1 (protegit)",
    "sounpacp": "HE‑AACv2 (protegit)",
    "sounpc+3": "Dolby Atmos (protegit)",
    "sounpec3": "EC‑3 Dolby Digital+ (protegit)",
    "sounqaac": "AAC (protegit, MP4 fragmentat)",
    "sounqac3": "AC‑3 Dolby Digital (protegit, MP4 fragmentat)",
    "sounqach": "HE‑AACv1 (protegit, MP4 fragmentat)",
    "sounqacp": "HE‑AACv2 (protegit, MP4 fragmentat)",
    "sounqc+3": "Dolby Atmos (protegit, MP4 fragmentat)",
    "sounqec3": "EC‑3 Dolby Digital+ (protegit, MP4 fragmentat)",
    "sounqlac": "Apple Lossless (protegit, MP4 fragmentat)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protegit, seqüència de transport)",
    "sounzac3": "AC‑3 Dolby Digital (protegit, seqüència de transport)",
    "sounzach": "HE‑AACv1 (protegit, seqüència de transport)",
    "sounzacp": "HE‑AACv2 (protegit, seqüència de transport)",
    "sounzc+3": "Dolby Atmos (protegit, seqüència de transport)",
    "sounzec3": "EC‑3 Dolby Digital+ (protegit, seqüència de transport)",
    "sounzlac": "Apple Lossless (protegit, seqüència de transport)",
    "sprt": "Sprite",
    "strm": "Reproducció en línia",
    "strmrtsp": "Reproducció en línia",
    "text": "Text",
    "texttext": "Text del QuickTime",
    "texttx3g": "Text 3GPP",
    "tmcd": "Codi temporal",
    "tmcdtmcd": "Codi temporal",
    "tmet": "Metadades temporals",
    "twen": "Tween",
    "vide": "Vídeo",
    "vide1": "Color indexat d’1 bit sense comprimir",
    "vide2": "Color indexat de 2 bits sense comprimir",
    "vide2vuy": "Component Y’CbCr de 8 bits 4:2:2 ordenat Cb Y’0 Cr Y’1",
    "vide4": "Color indexat de 4 bits sense comprimir",
    "vide8": "Color indexat de 8 bits sense comprimir",
    "vide8BPS": "RGB planar",
    "vide16": "RGB 555 de 16 bits sense comprimir (Big Endian)",
    "vide24": "RGB de 24 bits sense comprimir",
    "vide24BG": "BGR de 24 bits sense comprimir",
    "vide32": "ARGB de 32 bits sense comprimir",
    "vide33": "Escala de grisos d’1 bit sense comprimir",
    "vide34": "Escala de grisos de 2 bits sense comprimir",
    "vide36": "Escala de grisos de 4 bits sense comprimir",
    "vide40": "Escala de grisos de 8 bits sense comprimir",
    "vide5551": "RGB 5551 de 16 bits sense comprimir (Little Endian)",
    "videa2vy": "Component de dos plans Y’CbCr,A de 8 bits 4:2:2,4",
    "videABGR": "ABGR de 32 bits sense comprimir",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Conjunts de paràmetres en ràfega de bits)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Escala de grisos de 16 bits sense comprimir",
    "videb32a": "AlphaGray de 32 bits sense comprimir",
    "videb48r": "RGB de 48 bits sense comprimir",
    "videb64a": "ARGB de 64 bits sense comprimir",
    "videB565": "RGB 565 de 16 bits sense comprimir (Big Endian)",
    "videBGRA": "BGRA de 32 bits sense comprimir",
    "videbhiv": "bhiv",
    "videblur": "Filtre de convolució",
    "videcdh1": "Dolby Vision HEVC (encriptat)",
    "videclou": "Núvol",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Transició creuada",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtre de convolució",
    "videfire": "Fire",
    "videfmns": "Filtre Film Noise",
    "videgenk": "Filtre de convolució",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 4:2:2 de 10 bits",
    "videhev1": "HEVC (Conjunts de paràmetres en ràfega de bits)",
    "videhvc1": "HEVC",
    "videicod": "Còdec Apple Intermediate",
    "videIV41": "Vídeo Intel Indeo™ 4.3",
    "videIV50": "Vídeo Indeo™ 5.1",
    "videjpeg": "Photo - JPEG",
    "videJvt3": "Vídeo Apple H.264/AVC (previsualització)",
    "videkpcd": "Photo CD",
    "videL555": "RGB 555 de 16 bits sense comprimir (Little Endian)",
    "videL565": "RGB 565 de 16 bits sense comprimir (Little Endian)",
    "vidematt": "Escombratge de gradient",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Vídeo MPEG-1",
    "videmp2v": "Vídeo MPEG-2",
    "videmp4v": "Vídeo MPEG-4",
    "videmplo": "Implosionar",
    "videmuxa": "HEVC amb alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Desconegut",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Vídeo Apple Pixlet",
    "videqdh1": "Dolby Vision HEVC (protegit, MP4 fragmentat)",
    "vider210": "RGB de 10 bits sense comprimir",
    "vider408": "Component Y’CbCrA de 8 bits 4:4:4:4 ordenat A Y’ Cb Cr",
    "videRGBA": "RGBA de 32 bits sense comprimir",
    "viderle ": "Animació",
    "viderpza": "Vídeo",
    "vides263": "H.263",
    "videshrp": "Filtre de convolució",
    "videslid": "Push",
    "videsmc ": "Gràfics",
    "videsmpt": "Escombratge",
    "videsolr": "Filtre de balanç de color",
    "videSVQ1": "Vídeo Sorenson",
    "videSVQ3": "Vídeo Sorenson 3",
    "videtiff": "TIFF",
    "videtint": "Filtre de balanç de color",
    "videtrav": "Màscara mòbil",
    "videv210": "Component Y’CbCr de 10 bits 4:2:2",
    "videv216": "Component Y’CbCr de 10-12-14-16 bits 4:2:2",
    "videv308": "Component Y’CbCr de 8 bits 4:4:4",
    "videv408": "Component Y’CbCrA de 8 bits 4:4:4:4 ordenat Cb Y’ Cr A",
    "videv410": "Component Y’CbCr de 10 bits 4:4:4",
    "videVP31": "Vídeo On2 VP3 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 de 10 bits",
    "videxf4c": "XF-AVC Intra 4:4:4 de 12 bits",
    "videxfg8": "XF-AVC Long GOP 4:2:2 de 8 bits",
    "videxfga": "XF-AVC Long GOP 4:2:2 de 10 bits",
    "videxfi8": "XF-AVC Intra 4:2:2 de 8 bits",
    "videxfia": "XF-AVC Intra 4:2:2 de 10 bits",
    "videxplo": "Implosionar",
    "videy420": "Component de tres plans Y’CbCr de 8 bits 4:2:0",
    "videyuvs": "Component Y’CbCr de 8 bits 4:2:2 ordenat Y’0 Cb Y’1 Cr",
    "videzygo": "ZyGoVideo",
]
