/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Subtítulos opcionales",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Indicación",
    "meta": "Metadatos",
    "metamebx": "Metadatos Timed",
    "musimusi": "Música",
    "muxx": "Muxed",
    "obje": "QTVR Object",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Subtítulo",
    "sbtldrmt": "Subtítulo",
    "sbtltx3g": "Subtítulo",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Sonido",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (encriptado)",
    "sounpaac": "AAC (protegido)",
    "sounpac3": "AC‑3 Dolby Digital (protegido)",
    "sounpach": "HE-AACv1 (protegido)",
    "sounpacp": "HE-AACv2 (protegido)",
    "sounpc+3": "Dolby Atmos (protegido)",
    "sounpec3": "EC‑3 Dolby Digital+ (protegido)",
    "sounqaac": "AAC (protegido, MP4 fragmentado)",
    "sounqac3": "AC‑3 Dolby Digital (protegido, MP4 fragmentado)",
    "sounqach": "HE‑AACv1 (protegido, MP4 fragmentado)",
    "sounqacp": "HE‑AACv2 (protegido, MP4 fragmentado)",
    "sounqc+3": "Dolby Atmos (protegido, MP4 fragmentado)",
    "sounqec3": "EC‑3 Dolby Digital+ (protegido, MP4 fragmentado)",
    "sounqlac": "Apple Lossless (protegido, MP4 fragmentado)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protegido, secuencia de transporte)",
    "sounzac3": "AC‑3 Dolby Digital (protegido, secuencia de transporte)",
    "sounzach": "HE‑AACv1 (protegido, secuencia de transporte)",
    "sounzacp": "HE‑AACv2 (protegido, secuencia de transporte)",
    "sounzc+3": "Dolby Atmos (protegido, secuencia de transporte)",
    "sounzec3": "EC‑3 Dolby Digital+ (protegido, secuencia de transporte)",
    "sounzlac": "Apple Lossless (protegido, secuencia de transporte)",
    "sprt": "Sprite",
    "strm": "Transmisión",
    "strmrtsp": "Transmisión",
    "text": "Texto",
    "texttext": "Texto QuickTime",
    "texttx3g": "Texto 3GPP",
    "tmcd": "Código de tiempo",
    "tmcdtmcd": "Código de tiempo",
    "tmet": "Metadatos Timed",
    "twen": "Interpolación",
    "vide": "Vídeo",
    "vide1": "Color indexado de 1 bit sin comprimir",
    "vide2": "Color indexado de 2 bits sin comprimir",
    "vide2vuy": "Componente Y'CbCr de 8 bits 4:2:2 ordenado Cb Y'0 Cr Y'1",
    "vide4": "Color indexado de 4 bits sin comprimir",
    "vide8": "Color indexado de 8 bits sin comprimir",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555 de 16 bits sin comprimir (Big Endian)",
    "vide24": "RGB de 24 bits sin comprimir",
    "vide24BG": "BGR de 24 bits sin comprimir",
    "vide32": "ARGB de 32 bits sin comprimir",
    "vide33": "Escala de gris de 1 bit sin comprimir",
    "vide34": "Escala de gris de 2 bits sin comprimir",
    "vide36": "Escala de gris de 4 bits sin comprimir",
    "vide40": "Escala de gris de 8 bits sin comprimir",
    "vide5551": "RGB 5551 de 16 bits sin comprimir (Little Endian)",
    "videa2vy": "Componente de dos planos Y'CbCr,A de 8 bits 4:2:2,4",
    "videABGR": "ABGR de 32 bits sin comprimir",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Conjuntos de parámetros en corriente de bits)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Escala de gris de 16 bits sin comprimir",
    "videb32a": "AlphaGray de 32 bits sin comprimir",
    "videb48r": "RGB de 48 bits sin comprimir",
    "videb64a": "ARGB de 64 bits sin comprimir",
    "videB565": "RGB 565 de 16 bits sin comprimir (Big Endian)",
    "videBGRA": "BGRA de 32 bits sin comprimir",
    "videbhiv": "bhiv",
    "videblur": "Filtro de convolución",
    "videcdh1": "Dolby Vision HEVC (encriptado)",
    "videclou": "Nube",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "Contenidos AVC0",
    "videdslv": "Fundido",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtro de convolución",
    "videfire": "Fuego",
    "videfmns": "Filtro de interferencias",
    "videgenk": "Filtro de convolución",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC de 10 bits 4:2:2",
    "videhev1": "HEVC (Conjuntos de parámetros en corriente de bits)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Vídeo Intel Indeo™ 4.3",
    "videIV50": "Vídeo Indeo™ 5.1",
    "videjpeg": "Photo - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Previsualización)",
    "videkpcd": "Photo CD",
    "videL555": "RGB 555 de 16 bits sin comprimir (Little Endian)",
    "videL565": "RGB 565 de 16 bits sin comprimir (Little Endian)",
    "vidematt": "Gradación",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Vídeo MPEG-1",
    "videmp2v": "Vídeo MPEG-2",
    "videmp4v": "Vídeo MPEG-4",
    "videmplo": "Implosión",
    "videmuxa": "HEVC con alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Desconocido",
    "videpng ": "PNG",
    "videpush": "Arrastre",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (protegido, MP4 fragmentado)",
    "vider210": "RGB de 10 bits sin comprimir",
    "vider408": "Componente Y'CbCrA de 8 bits 4:4:4:4 ordenado A Y' Cb Cr",
    "videRGBA": "RGBA de 32 bits sin comprimir",
    "viderle ": "Animación",
    "viderpza": "Vídeo",
    "vides263": "H.263",
    "videshrp": "Filtro de convolución",
    "videslid": "Arrastre",
    "videsmc ": "Gráficos",
    "videsmpt": "Barrido",
    "videsolr": "Filtro de balance de colores",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filtro de balance de colores",
    "videtrav": "Máscara móvil",
    "videv210": "Componente Y'CbCr de 10 bits 4:2:2",
    "videv216": "Componente Y'CbCr de 10, 12, 14, 16 bits 4:2:2",
    "videv308": "Componente Y'CbCr de 8 bits 4:4:4",
    "videv408": "Componente Y'CbCrA de 8 bits 4:4:4:4 ordenado Cb Y' Cr A",
    "videv410": "Componente Y'CbCr de 10 bits 4:4:4",
    "videVP31": "Vídeo On2 VP3 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10 bits",
    "videxf4c": "XF-AVC Intra 4:4:4 12 bits",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 bits",
    "videxfga": "XF-AVC Long GOP 4:2:2 10 bits",
    "videxfi8": "XF-AVC Intra 4:2:2 8 bits",
    "videxfia": "XF-AVC Intra 4:2:2 10 bits",
    "videxplo": "Implosión",
    "videy420": "Componente de tres planos Y'CbCr de 8 bits 4:2:0",
    "videyuvs": "Componente Y'CbCr de 8 bits 4:2:2 ordenado Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
