/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "الشرح المكتوب",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "تلميح",
    "meta": "بيانات التعريف",
    "metamebx": "بيانات تعريف بتوقيت",
    "musimusi": "موسيقى",
    "muxx": "متعدد الإرسال",
    "obje": "عنصر QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "بانوراما VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "مؤلف Quartz",
    "qtz qtz ": "مؤلف Quartz",
    "sbtl": "عنوان فرعي",
    "sbtldrmt": "عنوان فرعي",
    "sbtltx3g": "عنوان فرعي",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "المظهر الخارجي",
    "skinskcr": "المظهر الخارجي",
    "skinskdr": "سطح",
    "soun": "الصوت",
    "sounalac": "Apple Lossless",
    "sounclac": "‏Apple Lossless (مشفَّر)",
    "sounpaac": "‏AAC (محمي)",
    "sounpac3": "‏AC-3 Dolby Digital (محمي)",
    "sounpach": "‏HE-AACv1 (محمي)",
    "sounpacp": "‏HE-AACv2 (محمي)",
    "sounpc+3": "‏Dolby Atmos (محمي)",
    "sounpec3": "‏EC-3 Dolby Digital+‎ (محمي)",
    "sounqaac": "‏AAC (محمي، MP4 مقسَّم)",
    "sounqac3": "‏AC-3 Dolby Digital (محمي، MP4 مقسَّم)",
    "sounqach": "‏HE-AACv1 (محمي، MP4 مقسَّم)",
    "sounqacp": "‏HE-AACv2 (محمي، MP4 مقسَّم)",
    "sounqc+3": "‏Dolby Atmos (محمي، MP4 مقسَّم)",
    "sounqec3": "‏EC-3 Dolby Digital+‎ (محمي، MP4 مقسَّم)",
    "sounqlac": "‏Apple Lossless (محمي، MP4 مقسَّم)",
    "sounvdva": "DV",
    "sounzaac": "‏AAC (محمي، تدفق نقل)",
    "sounzac3": "‏AC-3 Dolby Digital (محمي، تدفق نقل)",
    "sounzach": "‏HE-AACv1 (محمي، تدفق نقل)",
    "sounzacp": "‏HE-AACv2 (محمي، تدفق نقل)",
    "sounzc+3": "‏Dolby Atmos (محمي، تدفق نقل)",
    "sounzec3": "‏EC-3 Dolby Digital+‎ (محمي، تدفق نقل)",
    "sounzlac": "‏Apple Lossless (محمي، تدفق نقل)",
    "sprt": "Sprite",
    "strm": "تدفق",
    "strmrtsp": "تدفق",
    "text": "نص",
    "texttext": "نص QuickTime",
    "texttx3g": "نص 3GPP",
    "tmcd": "رمز الوقت",
    "tmcdtmcd": "رمز الوقت",
    "tmet": "بيانات تعريف بتوقيت",
    "twen": "Tween",
    "vide": "فيديو",
    "vide1": "لون مفهرس ١ بت غير مضغوط",
    "vide2": "لون مفهرس ٢ بت غير مضغوط",
    "vide2vuy": "قام المكوّن Y'CbCr ٨ بت بطلب Cb Y'0 Cr Y'1",
    "vide4": "لون مفهرس ٤ بت غير مضغوط",
    "vide8": "لون مفهرس ٨ بت غير مضغوط",
    "vide8BPS": "Planar RGB",
    "vide16": "‏RGB 555 16 بت غير مضغوط (بناء طرفي كبير)",
    "vide24": "‏RGB ٢٤ بت غير مضغوط",
    "vide24BG": "‏BGR ٢٤ بت غير مضغوط",
    "vide32": "‏ARGB ٣٢ بت غير مضغوط",
    "vide33": "Uncompressed 1-bit Grayscale",
    "vide34": "تدرج الرمادي ٢ بت غير مضغوط",
    "vide36": "تدرج الرمادي ٤ بت غير مضغوط",
    "vide40": "تدرج الرمادي ٨ بت غير مضغوط",
    "vide5551": "‏RGB 5551 ١٦ بت غير مضغوط (بناء طرفي صغير)",
    "videa2vy": "مكوّن ذو مستويين Y'CbCr، A ٨ بت 4:2:2,4",
    "videABGR": "Uncompressed 32-bit ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "‏‪AVC-Intra 200 1080p60/30/24‬",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "‏‪AVC-Intra 4:4:4‬",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "‏‪Apple ProRes 4444 XQ‬",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "‏‪Apple ProRes 422 Proxy‬",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "‪Apple ProRes RAW HQ‬",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "‏H.264 (مجموعات معاملات في تدفق بت)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "حركة JPEG AVR",
    "videb16g": "Uncompressed 16-bit Grayscale",
    "videb32a": "‏AlphaGray ٣٢ بت غير مضغوط",
    "videb48r": "‏RGB ٤٨ بت غير مضغوط",
    "videb64a": "‏ARGB ٦٤ بت غير مضغوط",
    "videB565": "‏RGB 565 ١٦ بت غير مضغوط (بناء طرفي كبير)",
    "videBGRA": "‏BGRA ٣٢ بت غير مضغوط",
    "videbhiv": "bhiv",
    "videblur": "فلتر الالتفاف",
    "videcdh1": "‏Dolby Vision HEVC (مشفَّر)",
    "videclou": "السحابة",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "وسائط AVC0",
    "videdslv": "تلاشي متقاطع",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "‏Dolby Vision HEVC",
    "videdvh2": "‪DVCPRO HD (1080p25)‬",
    "videdvh3": "‪DVCPRO HD (1080p30)‬",
    "videdvh5": "‪DVCPRO HD (1080i50)‬",
    "videdvh6": "‪DVCPRO HD (1080i60)‬",
    "videdvhp": "‪DVCPRO HD (720p60)‬",
    "videdvhq": "‪DVCPRO HD (720p50)‬",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "فلتر الالتفاف",
    "videfire": "نار",
    "videfmns": "فلتر ضوضاء الفيلم",
    "videgenk": "فلتر الالتفاف",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "‏HEVC (مجموعات المعاملات في تدفق البت)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "صورة - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Preview)",
    "videkpcd": "قرص مضغوط للصور",
    "videL555": "Uncompressed 16-bit RGB 555 (Little Endian)",
    "videL565": "‏RGB 565 ١٦ بت غير مضغوط (بناء طرفي صغير)",
    "vidematt": "المسح المتدرج",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 فيديو",
    "videmp2v": "MPEG-2 فيديو",
    "videmp4v": "MPEG-4 فيديو",
    "videmplo": "الإبعاد",
    "videmuxa": "ترميز HEVC مع ألفا",
    "videmx3n": "‏MPEG IMX 525/60 (٣٠ ميغابت/ثانية)",
    "videmx3p": "‏‪MPEG IMX 625/50‬ ‏(٣٠ م.ب/ث)",
    "videmx4n": "‏MPEG IMX 525/60 (٤٠ ميغابت/ثانية)",
    "videmx4p": "‏MPEG IMX 625/50 (٤٠ ميغابت/ثانية)",
    "videmx5n": "‏MPEG IMX 525/60 (٥٠ ميغابت/ثانية)",
    "videmx5p": "‏MPEG IMX 625/50 (٥٠ ميغابت/ثانية)",
    "VideoDynamicRangeDolbyVision": "‏Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "‏SDR",
    "VideoDynamicRangeUnknown": "غير معروف",
    "videpng ": "PNG",
    "videpush": "إشعارات لحظية",
    "videpxlt": "Apple Pixlet فيديو",
    "videqdh1": "‏Dolby Vision HEVC (محمي، MP4 مقسَّم)",
    "vider210": "‏RGB ١٠ بت غير مضغوط",
    "vider408": "قام المكوّن Y'CbCrA ٨ بت 4:4:4:4 بطلب A Y' Cb Cr",
    "videRGBA": "‏RGBA ٣٢ بت غير مضغوط",
    "viderle ": "حركة",
    "viderpza": "الفيديو",
    "vides263": "H.263",
    "videshrp": "فلتر الالتفاف",
    "videslid": "دفع",
    "videsmc ": "الرسومات",
    "videsmpt": "مسح",
    "videsolr": "فلتر توازن اللون",
    "videSVQ1": "فيديو Sorenson",
    "videSVQ3": "فيديو Sorenson ٣",
    "videtiff": "TIFF",
    "videtint": "فلتر توازن اللون",
    "videtrav": "سفري غير لامع",
    "videv210": "محتوى Y'CbCr 10-bit 4:2:2",
    "videv216": "محتوى Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "المكوّن Y'CbCr ٨ بت 4:4:4",
    "videv408": "قام المكوّن Y'CbCrA ٨ بت 4:4:4:4 بطلب Cb Y' Cr A",
    "videv410": "المكوّن Y'CbCr ١٠ بت 4:4:4",
    "videVP31": "3.2 On2 VP3 فيديو",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "‏XF-AVC Intra 4:4:4 ١٠ بت",
    "videxf4c": "‏XF-AVC Intra 4:4:4 ١٢ بت",
    "videxfg8": "‏XF-AVC Intra 4:2:2 ٨ بت",
    "videxfga": "‏XF-AVC Intra 4:2:2 ١٠ بت",
    "videxfi8": "‏XF-AVC Intra 4:2:2 ٨ بت",
    "videxfia": "‏XF-AVC Intra 4:2:2 ١٠ بت",
    "videxplo": "الإبعاد",
    "videy420": "مكوّن ذو ثلاثة مستويات Y'CbCr ٨ بت 4:2:0",
    "videyuvs": "قام المكوّن Y'CbCr ٨ بت 4:2:2 بطلب Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
