/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Prošireni titlovi",
    "clcpatcc": "ATSC/52 dio 4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Savjet",
    "meta": "Metapodaci",
    "metamebx": "Vremenski ograničeni metapodaci",
    "musimusi": "Glazba",
    "muxx": "Multipleksirano",
    "obje": "QTVR objekt",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Titlovi",
    "sbtldrmt": "Titlovi",
    "sbtltx3g": "Titlovi",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Tema",
    "skinskcr": "Tema",
    "skinskdr": "Tema",
    "soun": "Zvuk",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (kriptirano)",
    "sounpaac": "AAC (zaštićeno)",
    "sounpac3": "AC-3 Dolby Digital (zaštićeno)",
    "sounpach": "HE-AACv1 (zaštićeno)",
    "sounpacp": "HE-AACv2 (zaštićeno)",
    "sounpc+3": "Dolby Atmos (zaštićeno)",
    "sounpec3": "EC-3 Dolby Digital+ (zaštićeno)",
    "sounqaac": "AAC (zaštićeno, fragmentirani MP4)",
    "sounqac3": "AC-3 Dolby Digital (zaštićeno, fragmentirani MP4)",
    "sounqach": "HE-AACv1 (zaštićeno, fragmentirani MP4)",
    "sounqacp": "HE-AACv2 (zaštićeno, fragmentirani MP4)",
    "sounqc+3": "Dolby Atmos (zaštićeno, fragmentirani MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (zaštićeno, fragmentirani MP4)",
    "sounqlac": "Apple Lossless (zaštićeno, fragmentirani MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (zaštićeno, transportni stream)",
    "sounzac3": "AC-3 Dolby Digital (zaštićeno, transportni stream)",
    "sounzach": "HE-AACv1 (zaštićeno, transportni stream)",
    "sounzacp": "HE-AACv2 (zaštićeno, transportni stream)",
    "sounzc+3": "Dolby Atmos (zaštićeno, transportni stream)",
    "sounzec3": "EC-3 Dolby Digital+ (zaštićeno, transportni stream)",
    "sounzlac": "Apple Lossless (zaštićeno, transportni stream)",
    "sprt": "Sprite",
    "strm": "Streaming",
    "strmrtsp": "Streaming",
    "text": "Tekst",
    "texttext": "QuickTime tekst",
    "texttx3g": "3GPP tekst",
    "tmcd": "Vremenski kôd",
    "tmcdtmcd": "Vremenski kôd",
    "tmet": "Vremenski ograničeni metapodaci",
    "twen": "Prijelazna slika",
    "vide": "Video",
    "vide1": "Nekomprimirana 1-bitna indeksirana boja",
    "vide2": "Nekomprimirana 2-bitna indeksirana boja",
    "vide2vuy": "Komponentni Y'CbCr 8-bitni 4:2:2 naručeni Cb Y'0 Cr Y'1",
    "vide4": "Nekomprimirana 4-bitna indeksirana boja",
    "vide8": "Nekomprimirana 8-bitna indeksirana boja",
    "vide8BPS": "Planar RGB",
    "vide16": "Nekomprimirani 16-bitni RGB 555 (Big Endian)",
    "vide24": "Nekomprimirani 24-bitni RGB",
    "vide24BG": "Nekomprimirani 24-bitni BGR",
    "vide32": "Nekomprimirani 32-bitni ARGB",
    "vide33": "Nekomprimirani 1-bitni sivi tonovi",
    "vide34": "Nekomprimirani 2-bitni sivi tonovi",
    "vide36": "Nekomprimirani 4-bitni sivi tonovi",
    "vide40": "Nekomprimirani 8-bitni sivi tonovi",
    "vide5551": "Nekomprimirani 16-bitni RGB 5551 (Little Endian)",
    "videa2vy": "Dvoravninska komponenta Y'CbCr,A 8 bita 4:2:2,4",
    "videABGR": "Nekomprimirani 32-bitni ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (setovi parametara u bitstreamu)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Nekomprimirani 16-bitni sivi tonovi",
    "videb32a": "Nekomprimirani 32-bitni AlphaGray",
    "videb48r": "Nekomprimirani 48-bitni RGB",
    "videb64a": "Nekomprimirani 64-bitni ARGB",
    "videB565": "Nekomprimirani 16-bitni RGB 565 (Big Endian)",
    "videBGRA": "Nekomprimirani 32-bitni BGRA",
    "videbhiv": "bhiv",
    "videblur": "Filtar konvolucije",
    "videcdh1": "Dolby Vision HEVC (kriptirano)",
    "videclou": "Oblak",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 mediji",
    "videdslv": "Zatamnjenje",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtar konvolucije",
    "videfire": "Vatra",
    "videfmns": "Filtar smetnji na flimu",
    "videgenk": "Filtar konvolucije",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bitni 4:2:2",
    "videhev1": "HEVC (setovi parametara u Bitstreamu)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Fotografija - JPEG",
    "videJvt3": "Apple H.264/AVC video (pregled)",
    "videkpcd": "Foto CD",
    "videL555": "Nekomprimirani 16-bitni RGB 555 (Little Endian)",
    "videL565": "Nekomprimirani 16-bitni RGB 565 (Little Endian)",
    "vidematt": "Pomak gradijenta",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 video",
    "videmp2v": "MPEG-2 video",
    "videmp4v": "MPEG-4 video",
    "videmplo": "Implozija",
    "videmuxa": "HEVC s alfom",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Nepoznato",
    "videpng ": "PNG",
    "videpush": "Proslijedi",
    "videpxlt": "Apple Pixlet video",
    "videqdh1": "Dolby Vision HEVC (zaštićeno, fragmentirani MP4)",
    "vider210": "Nekomprimirani 10-bitni RGB",
    "vider408": "Komponentni Y'CbCrA 8-bitni 4:4:4:4 naručeni A Y' Cb Cr",
    "videRGBA": "Nekomprimirani 32-bitni RGBA",
    "viderle ": "Animacija",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Filtar konvolucije",
    "videslid": "Proslijedi",
    "videsmc ": "Grafika",
    "videsmpt": "Potez",
    "videsolr": "Filtar ravnoteže boje",
    "videSVQ1": "Sorenson video",
    "videSVQ3": "Sorenson video 3",
    "videtiff": "TIFF",
    "videtint": "Filtar ravnoteže boje",
    "videtrav": "Predložak",
    "videv210": "Komponentni Y'CbCr 10-bitni 4:2:2",
    "videv216": "Komponentni Y'CbCr 10,12,14,16-bitni 4:2:2",
    "videv308": "Komponentni Y'CbCr 8-bitni 4:4:4",
    "videv408": "Komponentni Y'CbCrA 8-bitni 4:4:4:4 naručeni Cb Y' Cr A",
    "videv410": "Komponentni Y'CbCr 10-bitni 4:4:4",
    "videVP31": "On2 VP3 video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bitno",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bitno",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 bita",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bitno",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bitno",
    "videxfia": "XF-AVC Intra 4:2:2 10-bitno",
    "videxplo": "Implozija",
    "videy420": "Troravninska komponenta Y'CbCr,A 8 bita 4:2:0",
    "videyuvs": "Komponentni Y'CbCr 8-bitni 4:2:2 naručeni Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
