/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Жасырын субтитр",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Сөзкөмек",
    "meta": "Метадеректер",
    "metamebx": "Синхрондалған метадеректер",
    "musimusi": "Музыка",
    "muxx": "Мультиплекс",
    "obje": "QTVR объекті",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR панорамасы",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Субтитр",
    "sbtldrmt": "Субтитр",
    "sbtltx3g": "Субтитр",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Тақырып",
    "skinskcr": "Тақырып",
    "skinskdr": "Тақырып",
    "soun": "Дыбыс",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (шифрланған)",
    "sounpaac": "AAC (қорғалған)",
    "sounpac3": "AC-3 Dolby Digital (қорғалған)",
    "sounpach": "HE-AACv1 (қорғалған)",
    "sounpacp": "HE-AACv2 (қорғалған)",
    "sounpc+3": "Dolby Atmos (қорғалған)",
    "sounpec3": "EC-3 Dolby Digital+ (қорғалған)",
    "sounqaac": "AAC (қорғалған, фрагменттелген MP4)",
    "sounqac3": "AC-3 Dolby Digital (қорғалған, фрагменттелген MP4)",
    "sounqach": "HE-AACv1 (қорғалған, фрагменттелген MP4)",
    "sounqacp": "HE-AACv2 (қорғалған, фрагменттелген MP4)",
    "sounqc+3": "Dolby Atmos (қорғалған, фрагменттелген MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (қорғалған, фрагменттелген MP4)",
    "sounqlac": "Apple Lossless (қорғалған, фрагменттелген MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (қорғалған, тасымалдау ағыны)",
    "sounzac3": "AC-3 Dolby Digital (қорғалған, тасымалдау ағыны)",
    "sounzach": "HE-AACv1 (қорғалған, тасымалдау ағыны)",
    "sounzacp": "HE-AACv2 (қорғалған, тасымалдау ағыны)",
    "sounzc+3": "Dolby Atmos (қорғалған, тасымалдау ағыны)",
    "sounzec3": "EC-3 Dolby Digital+ (қорғалған, тасымалдау ағыны)",
    "sounzlac": "Apple Lossless (қорғалған, тасымалдау ағыны)",
    "sprt": "Sprite",
    "strm": "Трансляция",
    "strmrtsp": "Трансляция",
    "text": "Мәтін",
    "texttext": "QuickTime мәтіні",
    "texttx3g": "3GPP мәтіні",
    "tmcd": "Уақыт коды",
    "tmcdtmcd": "Уақыт коды",
    "tmet": "Синхрондалған метадеректер",
    "twen": "Твин",
    "vide": "Видео",
    "vide1": "Қысылмаған, 1 бит, индекстелген түс",
    "vide2": "Қысылмаған, 2 бит, индекстелген түс",
    "vide2vuy": "Компонент Y'CbCr 8 бит 4:2:2; Cb Y'0 Cr Y'1 реті",
    "vide4": "Қысылмаған, 4 бит, индекстелген түс",
    "vide8": "Қысылмаған, 8 бит, индекстелген түс",
    "vide8BPS": "Жалпақ RGB",
    "vide16": "Қысылмаған, 16 бит, RGB 555 (Big Endian)",
    "vide24": "Қысылмаған, 24 бит, RGB",
    "vide24BG": "Қысылмаған, 24 бит, BGR",
    "vide32": "Қысылмаған, 32 бит, ARGB",
    "vide33": "Қысылмаған, 1 бит, сұр реңктер",
    "vide34": "Қысылмаған, 2 бит, сұр реңктер",
    "vide36": "Қысылмаған, 4 бит, сұр реңктер",
    "vide40": "Қысылмаған, 8 бит, сұр реңктер",
    "vide5551": "Қысылмаған, 16 бит, RGB 5551 (Little Endian)",
    "videa2vy": "Екі өлшемді компонент Y'CbCr,A 8 бит 4:2:2,4",
    "videABGR": "Қысылмаған, 32 бит, ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (ағындағы параметрлер жинағы)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Қысылмаған, 16 бит, сұр реңктер",
    "videb32a": "Қысылмаған, 32 бит, AlphaGray",
    "videb48r": "Қысылмаған, 48 бит, RGB",
    "videb64a": "Қысылмаған, 64 бит, ARGB",
    "videB565": "Қысылмаған, 16 бит, RGB 565 (Big Endian)",
    "videBGRA": "Қысылмаған, 32 бит, BGRA",
    "videbhiv": "bhiv",
    "videblur": "Үйірткілі сүзгі",
    "videcdh1": "Dolby Vision HEVC (шифрланған)",
    "videclou": "Бұлт",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 тасығышы",
    "videdslv": "Айқас ағылыс",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Үйірткілі сүзгі",
    "videfire": "Жалын",
    "videfmns": "Ескі таспа",
    "videgenk": "Үйірткілі сүзгі",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 бит 4:2:2",
    "videhev1": "HEVC (ағындағы параметрлер жинағы)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ видео 4.3",
    "videIV50": "Indeo™ видео 5.1",
    "videjpeg": "Фото — JPEG",
    "videJvt3": "Apple H.264/AVC видео (алдын ала көру)",
    "videkpcd": "Фото CD",
    "videL555": "Қысылмаған, 16 бит, RGB 555 (Little Endian)",
    "videL565": "Қысылмаған, 16 бит, RGB 565 (Little Endian)",
    "vidematt": "Градиенттік сүрту",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 видео",
    "videmp2v": "MPEG-2 видео",
    "videmp4v": "MPEG-4 видео",
    "videmplo": "Жұту",
    "videmuxa": "Alpha бар HEVC",
    "videmx3n": "MPEG IMX 525/60 (30 Мбит/с)",
    "videmx3p": "MPEG IMX 625/50 (30 Мбит/с)",
    "videmx4n": "MPEG IMX 525/60 (40 Мбит/с)",
    "videmx4p": "MPEG IMX 625/50 (40 Мбит/с)",
    "videmx5n": "MPEG IMX 525/60 (50 Мбит/с)",
    "videmx5p": "MPEG IMX 625/50 (50 Мбит/с)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Белгісіз",
    "videpng ": "PNG",
    "videpush": "Итеріп шығару",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (қорғалған, фрагменттелген MP4)",
    "vider210": "Қысылмаған, 10 бит, RGB",
    "vider408": "Компонент Y'CbCrA 8 бит 4:4:4:4; A Y' Cb Cr реті",
    "videRGBA": "Қысылмаған, 32 бит, RGBA",
    "viderle ": "Анимация",
    "viderpza": "Видео",
    "vides263": "H.263",
    "videshrp": "Үйірткілі сүзгі",
    "videslid": "Итеріп шығару",
    "videsmc ": "Графика",
    "videsmpt": "Сүрту",
    "videsolr": "Түс балансының сүзгісі",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Түс балансының сүзгісі",
    "videtrav": "Жылжымалы маска",
    "videv210": "Компонент Y'CbCr 10 бит 4:2:2",
    "videv216": "Компонент Y'CbCr 10,12,14,16 бит 4:2:2",
    "videv308": "Компонент Y'CbCr 8 бит 4:4:4",
    "videv408": "Компонент Y'CbCrA 8 бит 4:4:4:4; Cb Y' Cr A реті",
    "videv410": "Компонент Y'CbCr 10 бит 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10 бит",
    "videxf4c": "XF-AVC Intra 4:4:4 12 бит",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 бит",
    "videxfga": "XF-AVC Long GOP 4:2:2 10 бит",
    "videxfi8": "XF-AVC Intra 4:2:2 8 бит",
    "videxfia": "XF-AVC Intra 4:2:2 10 бит",
    "videxplo": "Жұту",
    "videy420": "Үш өлшемді компонент Y'CbCr 8 бит 4:2:0",
    "videyuvs": "Компонент Y'CbCr 8 бит 4:2:2; Y'0 Cb Y'1 Cr реті",
    "videzygo": "ZyGoVideo",
]
