/// Generated from CheckpointBase.plist
let CheckpointBase = [
    "AudioCodecs": [
        "AAC": [
            "AppleDRM": true,
            "LC": [
                "PerceptualNoiseSubsitution": true,
                "VariableBitRate": true,
            ],
            "MaximumSampleRate": 96000,
        ],
        "AC3": [
            "AppleDRM": true,
            "MaximumSampleRate": 48000,
        ],
        "AIFF": [
            "MaximumBitDepth": 24,
            "Mono": true,
            "Multichannel": false,
            "Stereo": true,
        ],
        "AMR": [
            "Codec": "samr",
            "MaximumBitDepth": 16,
            "MaximumSampleRate": 8000,
            "Mono": true,
            "Multichannel": false,
            "Stereo": false,
        ],
        "AppleLossless": [
            "AppleDRM": true,
            "MaximumBitDepth": 32,
            "MaximumBitDepthUntruncated": 16,
            "Mono": true,
            "Multichannel": false,
            "Stereo": true,
        ],
        "Audible": [
            "AAC": true,
            "Type1": false,
            "Type2": true,
            "Type3": true,
            "Type4": true,
        ],
        "EnhancedAC3": [
            "AppleDRM": true,
            "MaximumSampleRate": 48000,
        ],
        "FLAC": [
            "Codec": "flac",
            "Mono": true,
            "Multichannel": false,
            "Stereo": true,
        ],
        "MP3": [
            "MaximumDataRate": 320,
            "MaximumSampleRate": 48000,
            "Mono": true,
            "Stereo": true,
        ],
        "USAC": [
            "Codec": "usac",
            "MaximumSampleRate": 96000,
            "Mono": true,
            "Multichannel": false,
            "Stereo": true,
        ],
        "WAV": [
            "MaximumBitDepth": 24,
            "Mono": true,
            "Multichannel": false,
            "Stereo": true,
        ],
    ],
    "VideoCodecs": [
        "H.263": [
            "AudioCodecs": [
                "AMR": [
                    "Codec": "samr",
                ],
            ],
            "Codec": "h263",
            "Level": 45,
            "MaximumHeight": 144,
            "MaximumResolution": 25344,
            "MaximumWidth": 176,
            "MinimumHeight": 16,
            "MinimumWidth": 16,
            "NumericProfile": 0,
            "xMaximumPixelsPerSecond": 633_600,
        ],
        "H.264": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Level": 41,
            "MaximumHeight": 1920,
            "MaximumPixelsPerSecond": 65_318_400,
            "MaximumResolution": 2_088_960,
            "MaximumWidth": 1920,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "B",
        ],
        "H.264_HDVideo42": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Level": 42,
            "MaximumHeight": 1920,
            "MaximumPixelsPerSecond": 130_636_800,
            "MaximumResolution": 2_088_960,
            "MaximumWidth": 1920,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "B",
        ],
        "H.264_UHDVideo": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Level": 51,
            "MaximumBitrate": 135_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 130_636_800,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "B",
        ],
        "H.264_UHDVideo2": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Level": 51,
            "MaximumBitrate": 240_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 261_273_600,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "B",
        ],
        "H.264_UHDVideo3": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Level": 52,
            "MaximumBitrate": 240_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 261_273_600,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "B",
        ],
        "H.264H": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 41,
            "MaximumHeight": 1920,
            "MaximumPixelsPerSecond": 65_318_400,
            "MaximumResolution": 2_088_960,
            "MaximumWidth": 1920,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "NumericProfile": 100,
            "SupportsBFrames": true,
        ],
        "H.264H_HDVideo42": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 42,
            "MaximumHeight": 1920,
            "MaximumPixelsPerSecond": 130_636_800,
            "MaximumResolution": 2_088_960,
            "MaximumWidth": 1920,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "NumericProfile": 100,
            "SupportsBFrames": true,
        ],
        "H.264H_UHDVideo": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 51,
            "MaximumBitrate": 100_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 130_636_800,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "NumericProfile": 100,
            "SupportsBFrames": true,
        ],
        "H.264H_UHDVideo2": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 51,
            "MaximumBitrate": 230_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 261_273_600,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "NumericProfile": 100,
            "SupportsBFrames": true,
        ],
        "H.264H_UHDVideo3": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 52,
            "MaximumBitrate": 230_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 261_273_600,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "NumericProfile": 100,
            "SupportsBFrames": true,
        ],
        "H.264LC": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "ComplexityLevel": 1,
            "Level": 41,
            "MaximumHeight": 1280,
            "MaximumResolution": 921_600,
            "MaximumWidth": 1280,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "B",
        ],
        "H.264M": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 41,
            "MaximumHeight": 1920,
            "MaximumPixelsPerSecond": 65_318_400,
            "MaximumResolution": 2_088_960,
            "MaximumWidth": 1920,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "M",
            "SupportsBFrames": true,
        ],
        "H.264M_HDVideo42": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 42,
            "MaximumHeight": 1920,
            "MaximumPixelsPerSecond": 130_636_800,
            "MaximumResolution": 2_088_960,
            "MaximumWidth": 1920,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "M",
            "SupportsBFrames": true,
        ],
        "H.264M_UHDVideo": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 51,
            "MaximumBitrate": 100_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 130_636_800,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "M",
            "SupportsBFrames": true,
        ],
        "H.264M_UHDVideo2": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 51,
            "MaximumBitrate": 230_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 261_273_600,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "M",
            "SupportsBFrames": true,
        ],
        "H.264M_UHDVideo3": [
            "AppleVideoDRM": [
                "MaximumEncryptionPercentage": 100,
            ],
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "Codec": "avc1",
            "Level": 52,
            "MaximumBitrate": 230_000_000,
            "MaximumHeight": 3840,
            "MaximumPixelsPerSecond": 261_273_600,
            "MaximumResolution": 8_294_400,
            "MaximumWidth": 3840,
            "MinimumHeight": 32,
            "MinimumWidth": 32,
            "Profile": "M",
            "SupportsBFrames": true,
        ],
        "MPEG4": [
            "AudioCodecs": [
                "AAC": [
                    "AppleDRM": true,
                    "LC": [
                        "Multichannel": false,
                        "VariableBitRate": true,
                    ],
                    "MaximumBitRate": 256,
                    "MaximumSampleRate": 96000,
                ],
                "AC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "EnhancedAC3": [
                    "AppleDRM": true,
                    "MaximumSampleRate": 48000,
                ],
                "PCM": [
                    "Codec": "pcm ",
                    "MaximumBitDepth": 16,
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
                "USAC": [
                    "Codec": "usac",
                    "MaximumSampleRate": 96000,
                    "Mono": true,
                    "Multichannel": false,
                    "Stereo": true,
                ],
            ],
            "MaximumAverageBitRate": 5000,
            "MaximumHeight": 576,
            "MaximumResolution": 307_200,
            "MaximumWidth": 720,
            "MinimumHeight": 16,
            "MinimumWidth": 16,
            "Profile-Level-ID": 3,
        ],
    ],
]
