/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Надпис",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Съвет",
    "meta": "Метаданни",
    "metamebx": "Времеви метаданни",
    "musimusi": "Музика",
    "muxx": "Мултиплексиран",
    "obje": "QTVR Обект",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Панорама",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Субтитри",
    "sbtldrmt": "Субтитри",
    "sbtltx3g": "Субтитри",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Кожа",
    "skinskcr": "Кожа",
    "skinskdr": "Кожа",
    "soun": "Звук",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (криптиран)",
    "sounpaac": "AAC (защитено)",
    "sounpac3": "AC-3 Dolby Digital (защитен)",
    "sounpach": "HE-AACv1 (защитен)",
    "sounpacp": "HE-AACv2 (защитен)",
    "sounpc+3": "Dolby Atmos (защитен)",
    "sounpec3": "EC-3 Dolby Digital+ (защитен)",
    "sounqaac": "AAC (защитен, фрагментиран MP4)",
    "sounqac3": "AC-3 Dolby Digital (защитен, фрагментиран MP4)",
    "sounqach": "HE-AACv1 (защитен, фрагментиран MP4)",
    "sounqacp": "HE-AACv2 (защитен, фрагментиран MP4)",
    "sounqc+3": "Dolby Atmos (защитен, фрагментиран MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (защитен, фрагментиран MP4)",
    "sounqlac": "Apple Lossless (защитен, фрагментиран MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (защитен, транспортен поток)",
    "sounzac3": "AC-3 Dolby Digital (защитен, транспортен поток)",
    "sounzach": "HE-AACv1 (защитен, транспортен поток)",
    "sounzacp": "HE-AACv2 (защитен, транспортен поток)",
    "sounzc+3": "Dolby Atmos (защитен, транспортен поток)",
    "sounzec3": "EC-3 Dolby Digital+ (защитен, транспортен поток)",
    "sounzlac": "Apple Lossless (защитен, транспортен поток)",
    "sprt": "Спрайт",
    "strm": "Стрийминг",
    "strmrtsp": "Стрийминг",
    "text": "Текст",
    "texttext": "QuickTime Text",
    "texttx3g": "3GPP Text",
    "tmcd": "Времеви код",
    "tmcdtmcd": "Времеви код",
    "tmet": "Времеви метаданни",
    "twen": "Преходен кадър",
    "vide": "Видео",
    "vide1": "Некомпресиран 1-битов Индексиран цвят",
    "vide2": "Некомпресиран 2-битов Индексиран цвят",
    "vide2vuy": "Компонент Y'CbCr 8-битов 4:2:2 подредба Cb Y'0 Cr Y'1",
    "vide4": "Некомпресиран 4-битов Индексиран цвят",
    "vide8": "Некомпресиран 8-битов Индексиран цвят",
    "vide8BPS": "Планарен RGB",
    "vide16": "Некомпресиран 16-битов RGB 555 (Голям ендиан)",
    "vide24": "Некомпресиран 24-битов RGB",
    "vide24BG": "Некомпресиран 24-битов BGR",
    "vide32": "Некомпресиран 32-битов ARGB",
    "vide33": "Некомпресиран 1-битов цвят нива на сивото",
    "vide34": "Некомпресиран 2-битов цвят нива на сивото",
    "vide36": "Некомпресиран 4-битов цвят нива на сивото",
    "vide40": "Некомпресиран 8-битов цвят нива на сивото",
    "vide5551": "Некомпресиран 16-битов RGB 5551 (Малък ендиан)",
    "videa2vy": "Двупланов компонент Y'CbCr,A 8-битов 4:2:2,4",
    "videABGR": "Некомпресиран 32-битов ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Набор от параметри в последователност от битове)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Некомпресиран 16-битов цвят нива на сивото",
    "videb32a": "Некомпресиран 32-битов AlphaGray",
    "videb48r": "Некомпресиран 48-битов RGB",
    "videb64a": "Некомпресиран 64-битов ARGB",
    "videB565": "Некомпресиран 16-битов RGB 565 (Голям ендиан)",
    "videBGRA": "Некомпресиран 32-битов BGRA",
    "videbhiv": "bhiv",
    "videblur": "Филтър за конволюция",
    "videcdh1": "Dolby Vision HEVC (криптиран)",
    "videclou": "Cloud",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Плавен преход",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Филтър за конволюция",
    "videfire": "Огън",
    "videfmns": "Филтър за филмов шум",
    "videgenk": "Филтър за конволюция",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "HEVC (Набор от параметри в последователност от битове)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Видео 4.3",
    "videIV50": "Indeo™ видео 5.1",
    "videjpeg": "Снимка - JPEG",
    "videJvt3": "Apple H.264/AVC Видео (Преглед)",
    "videkpcd": "Фотографски компакт диск",
    "videL555": "Некомпресиран 16-битов RGB 555 (Малък ендиан)",
    "videL565": "Некомпресиран 16-битов RGB 565 (Малък ендиан)",
    "vidematt": "Изтриване на преход",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1 Video",
    "videmp2v": "MPEG-2 Video",
    "videmp4v": "MPEG-4 Video",
    "videmplo": "Имплозия",
    "videmuxa": "HEVC with Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Неизвестен",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (защитен, фрагментиран MP4)",
    "vider210": "Некомпресиран 10-битов RGB",
    "vider408": "Компонент Y'CbCrA 8-битов 4:4:4:4 подредба A Y' Cb Cr",
    "videRGBA": "Некомпресиран 32-битов RGBA",
    "viderle ": "Анимация",
    "viderpza": "Видео",
    "vides263": "H.263",
    "videshrp": "Филтър за конволюция",
    "videslid": "Push",
    "videsmc ": "Графики",
    "videsmpt": "Изтриване",
    "videsolr": "Филтър за баланс на цвят",
    "videSVQ1": "Sorenson Видео",
    "videSVQ3": "Sorenson Видео 3",
    "videtiff": "TIFF",
    "videtint": "Филтър за баланс на цвят",
    "videtrav": "Traveling Matte",
    "videv210": "Компонент Y'CbCr 10-битов 4:2:2",
    "videv216": "Компонент Y'CbCr 10,12,14,16-битов 4:2:2",
    "videv308": "Компонент Y'CbCr 8-битов 4:4:4",
    "videv408": "Компонент Y'CbCrA 8-битов 4:4:4:4 подредба Cb Y' Cr A",
    "videv410": "Компонент Y'CbCr 10-битов 4:4:4",
    "videVP31": "On2 VP3 Видео 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Имплозия",
    "videy420": "Трипланов компонент Y'CbCr 8-битов 4:2:0",
    "videyuvs": "Компонент Y'CbCr 8-битов 4:2:2 подредба Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
