/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Phụ đề",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Gợi ý",
    "meta": "Siêu dữ liệu",
    "metamebx": "Siêu dữ liệu hạn định",
    "musimusi": "Nhạc",
    "muxx": "Đã trộn kênh",
    "obje": "Đối tượng QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Toàn cảnh VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Phụ đề",
    "sbtldrmt": "Phụ đề",
    "sbtltx3g": "Phụ đề",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Da",
    "skinskcr": "Da",
    "skinskdr": "Da",
    "soun": "Âm báo",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (được mã hóa)",
    "sounpaac": "AAC (được bảo vệ)",
    "sounpac3": "AC-3 Dolby Digital (được bảo vệ)",
    "sounpach": "HE-AACv1 (được bảo vệ)",
    "sounpacp": "HE-AACv2 (được bảo vệ)",
    "sounpc+3": "Dolby Atmos (được bảo vệ)",
    "sounpec3": "EC-3 Dolby Digital+ (được bảo vệ)",
    "sounqaac": "AAC (MP4 phân mảnh, được bảo vệ)",
    "sounqac3": "AC-3 Dolby Digital (MP4 phân mảnh, được bảo vệ)",
    "sounqach": "HE-AACv1 (MP4 phân mảnh, được bảo vệ)",
    "sounqacp": "HE-AACv2 (MP4 phân mảnh, được bảo vệ)",
    "sounqc+3": "Dolby Atmos (MP4 phân mảnh, được bảo vệ)",
    "sounqec3": "EC-3 Dolby Digital+ (MP4 phân mảnh, được bảo vệ)",
    "sounqlac": "Apple Lossless (MP4 phân mảnh, được bảo vệ)",
    "sounvdva": "DV",
    "sounzaac": "AAC (luồng truyền tải, được bảo vệ)",
    "sounzac3": "AC-3 Dolby Digital (luồng truyền tải, được bảo vệ)",
    "sounzach": "HE-AACv1 (luồng truyền tải, được bảo vệ)",
    "sounzacp": "HE-AACv2 (luồng truyền tải, được bảo vệ)",
    "sounzc+3": "Dolby Atmos (luồng truyền tải, được bảo vệ)",
    "sounzec3": "EC-3 Dolby Digital+ (luồng truyền tải, được bảo vệ)",
    "sounzlac": "Apple Lossless (luồng truyền tải, được bảo vệ)",
    "sprt": "Sprite",
    "strm": "Phân luồng",
    "strmrtsp": "Phân luồng",
    "text": "Văn bản",
    "texttext": "Văn bản QuickTime",
    "texttx3g": "Văn bản 3GPP",
    "tmcd": "Mã thời gian",
    "tmcdtmcd": "Mã thời gian",
    "tmet": "Siêu dữ liệu hạn định",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Màu có chỉ mục 1-bit không nén",
    "vide2": "Màu có chỉ mục 2-bit không nén",
    "vide2vuy": "Cấu phần Y'CbCr 8-bit 4:2:2 yêu cầu Cb Y'0 Cr Y'1",
    "vide4": "Màu có chỉ mục 4-bit không nén",
    "vide8": "Màu có chỉ mục 8-bit không nén",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555 16-bit không nén (Big Endian)",
    "vide24": "Giải nén RGB 24-bit",
    "vide24BG": "BGR 24-bit không được nén",
    "vide32": "ARGB 32-bit không nén",
    "vide33": "Màu xám 1-bit không nén",
    "vide34": "Màu xám 2-bit không nén",
    "vide36": "Màu xám 4-bit không nén",
    "vide40": "Màu xám 8-bit không nén",
    "vide5551": "RGB 5551 16-bit không nén (Little Endian)",
    "videa2vy": "Cấu phần hai bảng Y'CbCr,A 8-bit 4:2:2,4",
    "videABGR": "ABGR 32-bit không nén",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Bộ tham số theo luồng bit)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Màu xám 16-bit không nén",
    "videb32a": "AlphaGray 32-bit không nén",
    "videb48r": "RGB 48-bit không nén",
    "videb64a": "ARGB 64-bit không nén",
    "videB565": "RGB 565 16-bit không nén (Big Endian)",
    "videBGRA": "BGRA 32-bit không nén",
    "videbhiv": "bhiv",
    "videblur": "Bộ lọc nhân chập",
    "videcdh1": "Dolby Vision HEVC (được mã hóa)",
    "videclou": "Mây",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "Phương tiện AVC0",
    "videdslv": "Cross Fade",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Bộ lọc nhân chập",
    "videfire": "Lửa",
    "videfmns": "Bộ lọc nhiễu phim",
    "videgenk": "Bộ lọc nhân chập",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "HEVC (Bộ tham số theo luồng bit)",
    "videhvc1": "HEVC",
    "videicod": "Codec trung gian của Apple",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Ảnh - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Xem trước)",
    "videkpcd": "CD ảnh",
    "videL555": "RGB 555 16-bit không nén (Little Endian)",
    "videL565": "RGB 565 16-bit không nén (Little Endian)",
    "vidematt": "Xóa Gradient",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Video MPEG-1",
    "videmp2v": "Video MPEG-2",
    "videmp4v": "Video MPEG-4",
    "videmplo": "Nổ",
    "videmuxa": "HEVC có Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/giây)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/giây)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/giây)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/giây)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/giây)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/giây)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Không xác định",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (MP4 phân mảnh, được bảo vệ)",
    "vider210": "RGB 10-bit không nén",
    "vider408": "Cấu phần Y'CbCrA 8-bit 4:4:4:4 yêu cầu A Y' Cb Cr",
    "videRGBA": "RGBA 32-bit không nén",
    "viderle ": "Hình động",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Bộ lọc nhân chập",
    "videslid": "Push",
    "videsmc ": "Đồ họa",
    "videsmpt": "Xóa sạch",
    "videsolr": "Bộ lọc cân bằng màu",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Bộ lọc cân bằng màu",
    "videtrav": "Đến Matte",
    "videv210": "Cấu phần Y'CbCr 10-bit 4:2:2",
    "videv216": "Cấu phần Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Cấu phần Y'CbCr 8-bit 4:4:4",
    "videv408": "Cấu phần Y'CbCrA 8-bit 4:4:4:4 yêu cầu Cb Y' Cr A",
    "videv410": "Cấu phần Y'CbCr 10-bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Nổ",
    "videy420": "Cấu phần ba bảng Y'CbCr 8-bit 4:2:0",
    "videyuvs": "Cấu phần Y'CbCr 8-bit 4:2:2 yêu cầu Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
