/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Legendagem opcional",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Pista",
    "meta": "Metadados",
    "metamebx": "Metadados regulados",
    "musimusi": "Música",
    "muxx": "Multiplexado",
    "obje": "Objeto QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Legenda",
    "sbtldrmt": "Legenda",
    "sbtltx3g": "Legenda",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Máscara",
    "skinskcr": "Máscara",
    "skinskdr": "Máscara",
    "soun": "Som",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (cifrado)",
    "sounpaac": "AAC (protegido)",
    "sounpac3": "AC‑3 Dolby Digital (protegido)",
    "sounpach": "HE‑AACv1 (protegido)",
    "sounpacp": "HE‑AACv2 (protegido)",
    "sounpc+3": "Dolby Atmos (protegido)",
    "sounpec3": "EC‑3 Dolby Digital+ (protegido)",
    "sounqaac": "AAC (protegido, MP4 fragmentado)",
    "sounqac3": "AC‑3 Dolby Digital (protegido, MP4 fragmentado)",
    "sounqach": "HE‑AACv1 (protegido, MP4 fragmentado)",
    "sounqacp": "HE‑AACv2 (protegido, MP4 fragmentado)",
    "sounqc+3": "Dolby Atmos (protegido, MP4 fragmentado)",
    "sounqec3": "EC‑3 Dolby Digital+ (protegido, MP4 fragmentado)",
    "sounqlac": "Apple Lossless (protegido, MP4 fragmentado)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protegido, stream de transporte)",
    "sounzac3": "AC‑3 Dolby Digital (protegido, stream de transporte)",
    "sounzach": "HE‑AACv1 (protegido, stream de transporte)",
    "sounzacp": "HE‑AACv2 (protegido, stream de transporte)",
    "sounzc+3": "Dolby Atmos (protegido, stream de transporte)",
    "sounzec3": "EC‑3 Dolby Digital+ (protegido, stream de transporte)",
    "sounzlac": "Apple Lossless (protegido, stream de transporte)",
    "sprt": "Animação",
    "strm": "Streaming",
    "strmrtsp": "Streaming",
    "text": "Texto",
    "texttext": "Texto do QuickTime",
    "texttx3g": "Texto 3GPP",
    "tmcd": "Código de tempo",
    "tmcdtmcd": "Código de tempo",
    "tmet": "Metadados regulados",
    "twen": "Interpolação",
    "vide": "Vídeo",
    "vide1": "Cor indexada 1 bit sem compressão",
    "vide2": "Cor indexada 2 bits sem compressão",
    "vide2vuy": "Componente Y'CbCr 8 bits 4:2:2 pedido Cb Y'0 Cr Y'1",
    "vide4": "Cor indexada 4 bits sem compressão",
    "vide8": "Cor indexada 8 bits sem compressão",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555 16 bits sem compressão (Big Endian)",
    "vide24": "RGB 24 bits sem compressão",
    "vide24BG": "BGR 24 bits sem compressão",
    "vide32": "ARGB 32 bits sem compressão",
    "vide33": "Nível de cinzentos 1 bit sem compressão",
    "vide34": "Cinzentos 2 bits sem compressão",
    "vide36": "Nível de cinzentos 4 bits sem compressão",
    "vide40": "Nível de cinzentos 8 bits sem compressão",
    "vide5551": "RGB 5551 16 bits sem compressão (Little Endian)",
    "videa2vy": "Componente em dois planos Y'CbCr,A 8 bits 4:2:2,4",
    "videABGR": "ABGR 32 bits sem compressão",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (conjuntos de parâmetros em Bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Nível de cinzentos 16 bits sem compressão",
    "videb32a": "AlphaGray 32 bits sem compressão",
    "videb48r": "RGB 48 bits sem compressão",
    "videb64a": "ARGB 64 bits sem compressão",
    "videB565": "RGB 565 16 bits sem compressão (Big Endian)",
    "videBGRA": "BGRA 32 bits sem compressão",
    "videbhiv": "bhiv",
    "videblur": "Filtro de convolução",
    "videcdh1": "Dolby Vision HEVC (cifrado)",
    "videclou": "Nuvem",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Fade cruzado",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtro de convolução",
    "videfire": "Fogo",
    "videfmns": "Filtro do ruído da película",
    "videgenk": "Filtro de convolução",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 4:2:2 de 10 bits",
    "videhev1": "HEVC (conjuntos de parâmetros em Bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ Video 5.1",
    "videjpeg": "Fotografia - JPEG",
    "videJvt3": "Apple H.264/AVC Video (pré‑visualização)",
    "videkpcd": "Photo CD",
    "videL555": "RGB 555 16 bits sem compressão (Little Endian)",
    "videL565": "RGB 565 16 bits sem compressão (Little Endian)",
    "vidematt": "Gradação",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Vídeo MPEG-1",
    "videmp2v": "Vídeo MPEG-2",
    "videmp4v": "Vídeo MPEG-4",
    "videmplo": "Implodir",
    "videmuxa": "HEVC com Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Desconhecido",
    "videpng ": "PNG",
    "videpush": "Deslocação",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (protegido, MP4 fragmentado)",
    "vider210": "RGB 10 bits sem compressão",
    "vider408": "Componente Y'CbCrA 8 bits 4:4:4:4 pedido A Y' Cb Cr",
    "videRGBA": "RGBA 32 bits sem compressão",
    "viderle ": "Animação",
    "viderpza": "Vídeo",
    "vides263": "H.263",
    "videshrp": "Filtro de convolução",
    "videslid": "Deslocação",
    "videsmc ": "Gráficos",
    "videsmpt": "Varrimento",
    "videsolr": "Filtro de equilíbrio cromático",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filtro de equilíbrio cromático",
    "videtrav": "Composição de imagens",
    "videv210": "Componente Y'CbCr 10 bits 4:2:2",
    "videv216": "Componente Y'CbCr 10,12,14,16 bits 4:2:2",
    "videv308": "Componente Y'CbCr 8 bits 4:4:4",
    "videv408": "Componente Y'CbCrA 8 bits 4:4:4:4 pedido Cb Y' Cr A",
    "videv410": "Componente Y'CbCr 10 bits 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10 bits",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 bits",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8 bits",
    "videxfia": "XF-AVC Intra 4:2:2 10 bits",
    "videxplo": "Implodir",
    "videy420": "Componente em três planos Y'CbCr 8 bits 4:2:0",
    "videyuvs": "Componente Y'CbCr 8 bits 4:2:2 pedido Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
