/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Açıklamalı Altyazılar",
    "clcpatcc": "ATSC/52 bölüm-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "İpucu",
    "meta": "Üst veri",
    "metamebx": "Süreli Üst Veri",
    "musimusi": "Müzik",
    "muxx": "Çoklanmış",
    "obje": "QTVR Nesnesi",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Altyazı",
    "sbtldrmt": "Altyazı",
    "sbtltx3g": "Altyazı",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Ses",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (şifreli)",
    "sounpaac": "AAC (korumalı)",
    "sounpac3": "AC-3 Dolby Digital (korumalı)",
    "sounpach": "HE-AACv1 (korumalı)",
    "sounpacp": "HE-AACv2 (korumalı)",
    "sounpc+3": "Dolby Atmos (korumalı)",
    "sounpec3": "EC-3 Dolby Digital+ (korumalı)",
    "sounqaac": "AAC (korumalı, parçalanmış MP4)",
    "sounqac3": "AC-3 Dolby Digital (korumalı, parçalanmış MP4)",
    "sounqach": "HE-AACv1 (korumalı, parçalanmış MP4)",
    "sounqacp": "HE-AACv2 (korumalı, parçalanmış MP4)",
    "sounqc+3": "Dolby Atmos (korumalı, parçalanmış MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (korumalı, parçalanmış MP4)",
    "sounqlac": "Apple Lossless (korumalı, parçalanmış MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (korumalı, aktarım yayını)",
    "sounzac3": "AC-3 Dolby Digital (korumalı, aktarım yayını)",
    "sounzach": "HE-AACv1 (korumalı, aktarım yayını)",
    "sounzacp": "HE-AACv2 (korumalı, aktarım yayını)",
    "sounzc+3": "Dolby Atmos (korumalı, aktarım yayını)",
    "sounzec3": "EC-3 Dolby Digital+ (korumalı, aktarım yayını)",
    "sounzlac": "Apple Lossless (korumalı, aktarım yayını)",
    "sprt": "Hareketli",
    "strm": "Duraksız Yayın",
    "strmrtsp": "Duraksız Yayın",
    "text": "Metin",
    "texttext": "QuickTime Metni",
    "texttx3g": "3GPP Metni",
    "tmcd": "Zaman Kodu",
    "tmcdtmcd": "Zaman Kodu",
    "tmet": "Süreli Üst Veri",
    "twen": "Şekil Değiştirme",
    "vide": "Video",
    "vide1": "Sıkıştırılmamış 1 Bit Dizinlenmiş Renk",
    "vide2": "Sıkıştırılmamış 2 Bit Dizinlenmiş Renk",
    "vide2vuy": "Bileşen Y'CbCr 8 bit 4:2:2 sıralı Cb Y'0 Cr Y'1",
    "vide4": "Sıkıştırılmamış 4 Bit Dizinlenmiş Renk",
    "vide8": "Sıkıştırılmamış 8 Bit Dizinlenmiş Renk",
    "vide8BPS": "Planar RGB",
    "vide16": "Sıkıştırılmamış 16 Bit RGB 555 (Büyüğü Başta)",
    "vide24": "Sıkıştırılmamış 24 Bit RGB",
    "vide24BG": "Sıkıştırılmamış 24 Bit BGR",
    "vide32": "Sıkıştırılmamış 32 Bit ARGB",
    "vide33": "Sıkıştırılmamış 1 Bit Gri Tonlu",
    "vide34": "Sıkıştırılmamış 2 Bit Gri Tonlu",
    "vide36": "Sıkıştırılmamış 4 Bit Gri Tonlu",
    "vide40": "Sıkıştırılmamış 8 Bit Gri Tonlu",
    "vide5551": "Sıkıştırılmamış 16 Bit RGB 5551 (Küçüğü Başta)",
    "videa2vy": "İki Düzlemli Bileşen Y'CbCr,A 8 Bit 4:2:2,4",
    "videABGR": "Sıkıştırılmamış 32 Bit ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Bit Akışındaki Parametre Kümeleri)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Hareketli JPEG AVR",
    "videb16g": "Sıkıştırılmamış 16 Bit Gri Tonlu",
    "videb32a": "Sıkıştırılmamış 32 Bit AlphaGray",
    "videb48r": "Sıkıştırılmamış 48 Bit RGB",
    "videb64a": "Sıkıştırılmamış 64 Bit ARGB",
    "videB565": "Sıkıştırılmamış 16 Bit RGB 565 (Büyüğü Başta)",
    "videBGRA": "Sıkıştırılmamış 32 Bit BGRA",
    "videbhiv": "bhiv",
    "videblur": "Evrişim Filtresi",
    "videcdh1": "Dolby Vision HEVC (şifreli)",
    "videclou": "Bulut",
    "videcvid": "Cinepak",
    "videdmb1": "Hareketli JPEG OpenDML",
    "videdrmi": "AVC0 Ortamı",
    "videdslv": "Çapraz Geçiş",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Evrişim Filtresi",
    "videfire": "Ateş",
    "videfmns": "Film Parazit Filtresi",
    "videgenk": "Evrişim Filtresi",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 bit 4:2:2",
    "videhev1": "HEVC (Bit Akışındaki Parametre Kümeleri)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Fotoğraf - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Önizleme)",
    "videkpcd": "Photo CD",
    "videL555": "Sıkıştırılmamış 16 Bit RGB 555 (Küçüğü Başta)",
    "videL565": "Sıkıştırılmamış 16 Bit RGB 565 (Küçüğü Başta)",
    "vidematt": "Gradyanla Silme",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Hareketli JPEG A",
    "videmjpb": "Hareketli JPEG B",
    "videmp1v": "MPEG-1 Video",
    "videmp2v": "MPEG-2 Video",
    "videmp4v": "MPEG-4 Video",
    "videmplo": "İçe Çökme",
    "videmuxa": "Alfa ile HEVC",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/sn)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/sn)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/sn)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/sn)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/sn)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Bilinmeyen",
    "videpng ": "PNG",
    "videpush": "İtiş",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (korumalı, parçalanmış MP4)",
    "vider210": "Sıkıştırılmamış 10 bit RGB",
    "vider408": "Bileşen Y'CbCrA 8 bit 4:4:4:4 sıralı A Y' Cb Cr",
    "videRGBA": "Sıkıştırılmamış 32 Bit RGBA",
    "viderle ": "Canlandırma",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Evrişim Filtresi",
    "videslid": "İtiş",
    "videsmc ": "Grafikler",
    "videsmpt": "Silme",
    "videsolr": "Renk Dengesi Filtresi",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Renk Dengesi Filtresi",
    "videtrav": "Hareketli Arka Plan",
    "videv210": "Bileşen Y'CbCr 10 bit 4:2:2",
    "videv216": "Bileşen Y'CbCr 10,12,14,16 bit 4:2:2",
    "videv308": "Bileşen Y'CbCr 8 bit 4:4:4",
    "videv408": "Bileşen Y'CbCrA 8 bit 4:4:4:4 sıralı Cb Y' Cr A",
    "videv410": "Bileşen Y'CbCr 10 bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10 bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "İçe Çökme",
    "videy420": "Üç Düzlemli Bileşen Y'CbCr 8 bit 4:2:0",
    "videyuvs": "Bileşen Y'CbCr 8 bit 4:2:2 sıralı Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
