/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "คำบรรยายภาพ",
    "clcpatcc": "ATSC/52 ส่วน-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "คำอธิบายเบื้องต้น",
    "meta": "เมตาดาต้า",
    "metamebx": "เมตาดาต้าตามเวลา",
    "musimusi": "เพลง",
    "muxx": "รวมสัญญาณ (Muxed)",
    "obje": "วัตถุ QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "พาโนรามา VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "คำบรรยาย",
    "sbtldrmt": "คำบรรยาย",
    "sbtltx3g": "คำบรรยาย",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "เสียง",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (แบบเข้ารหัส)",
    "sounpaac": "AAC (แบบปกป้อง)",
    "sounpac3": "AC-3 Dolby Digital (แบบปกป้อง)",
    "sounpach": "HE-AACv1 (แบบปกป้อง)",
    "sounpacp": "HE-AACv2 (แบบปกป้อง)",
    "sounpc+3": "Dolby Atmos (แบบปกป้อง)",
    "sounpec3": "EC-3 Dolby Digital+ (แบบปกป้อง)",
    "sounqaac": "AAC (แบบปกป้อง, fragmented MP4)",
    "sounqac3": "AC-3 Dolby Digital (แบบปกป้อง, fragmented MP4)",
    "sounqach": "HE-AACv1 (แบบปกป้อง, fragmented MP4)",
    "sounqacp": "HE-AACv2 (แบบปกป้อง, fragmented MP4)",
    "sounqc+3": "Dolby Atmos (แบบปกป้อง, fragmented MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (แบบปกป้อง, fragmented MP4)",
    "sounqlac": "Apple Lossless (แบบปกป้อง, fragmented MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (แบบปกป้อง, การส่งถ่ายสตรีม)",
    "sounzac3": "AC-3 Dolby Digital (แบบปกป้อง, การส่งถ่ายสตรีม)",
    "sounzach": "HE-AACv1 (แบบปกป้อง, การส่งถ่ายสตรีม)",
    "sounzacp": "HE-AACv2 (แบบปกป้อง, การส่งถ่ายสตรีม)",
    "sounzc+3": "Dolby Atmos (แบบปกป้อง, การส่งถ่ายสตรีม)",
    "sounzec3": "EC-3 Dolby Digital+ (แบบปกป้อง, การส่งถ่ายสตรีม)",
    "sounzlac": "Apple Lossless (แบบปกป้อง, การส่งถ่ายสตรีม)",
    "sprt": "Sprite",
    "strm": "การสตรีม",
    "strmrtsp": "การสตรีม",
    "text": "ข้อความ",
    "texttext": "ข้อความ QuickTime",
    "texttx3g": "ข้อความ 3GPP",
    "tmcd": "รหัสเวลา",
    "tmcdtmcd": "รหัสเวลา (Timecode)",
    "tmet": "เมตาดาต้าตามเวลา",
    "twen": "Tween",
    "vide": "วิดีโอ",
    "vide1": "สีแบบดัชนีขนาด 1-บิตที่ไม่บีบอัด",
    "vide2": "สีแบบดัชนีขนาด 2-บิตที่ไม่บีบอัด",
    "vide2vuy": "ส่วนประกอบของ Y'CbCr 8-บิต 4:2:2 ตามลำดับ Cb Y'0 Cr Y'1",
    "vide4": "สีแบบดัชนีขนาด 4-บิตที่ไม่บีบอัด",
    "vide8": "สีแบบดัชนีขนาด 8-บิตที่ไม่บีบอัด",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555 ขนาด 16-บิตแบบไม่บีบอัด (Big Endian)",
    "vide24": "RGB ขนาด 24-บิตแบบไม่บีบอัด",
    "vide24BG": "BGR ขนาด 24-บิตแบบไม่บีบอัด",
    "vide32": "ARGB ขนาด 32-บิตแบบไม่บีบอัด",
    "vide33": "ขาวดำขนาด 1-บิตแบบไม่บีบอัด",
    "vide34": "ขาวดำขนาด 2-บิต แบบไม่บีบอัด",
    "vide36": "ขาวดำขนาด 4-บิตแบบไม่บีบอัด",
    "vide40": "ขาวดำขนาด 8-บิตแบบไม่บีบอัด",
    "vide5551": "RGB 5551 ขนาด 16-บิตแบบไม่บีบอัด (Little Endian)",
    "videa2vy": "ส่วนประกอบ Y'CbCr,A 8-บิต 4:2:2,4 แบบ Two-Plane",
    "videABGR": "ABGR ขนาด 32-บิตแบบไม่บีบอัด",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "พร็อกซี่ Apple ProRes 422",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (ชุดพารามิเตอร์ในรูปแบบบิตสตรีม)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "ขาวดำขนาด 16-บิตแบบไม่บีบอัด",
    "videb32a": "AlphaGray ขนาด 32-บิตแบบไม่บีบอัด",
    "videb48r": "RGB ขนาด 48-บิตแบบไม่บีบอัด",
    "videb64a": "ARGB ขนาด 64-บิตแบบไม่บีบอัด",
    "videB565": "RGB 565 ขนาด 16-บิตแบบไม่บีบอัด (Big Endian)",
    "videBGRA": "BGRA ขนาด 32-บิตแบบไม่บีบอัด",
    "videbhiv": "bhiv",
    "videblur": "ปรับความคมชัด",
    "videcdh1": "Dolby Vision HEVC (แบบเข้ารหัส)",
    "videclou": "คลาวด์",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "สื่อแบบ AVC0",
    "videdslv": "จางหายไป",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "ปรับความคมชัด",
    "videfire": "ไฟ",
    "videfmns": "ปรับเกรนของฟิล์ม",
    "videgenk": "ปรับความคมชัด",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 บิต 4:2:2",
    "videhev1": "HEVC (ชุดพารามิเตอร์ในรูปแบบบิตสตรีม)",
    "videhvc1": "HEVC",
    "videicod": "รหัส Apple Codec ชั่วคราว",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "รูปภาพ - JPEG",
    "videJvt3": "วิดีโอ Apple H.264/AVC (ตัวอย่าง)",
    "videkpcd": "แผ่นซีดีรูปภาพ",
    "videL555": "RGB 555 ขนาด 16-บิตแบบไม่บีบอัด (Little Endian)",
    "videL565": "RGB 565 ขนาด 16-บิตแบบไม่บีบอัด (Little Endian)",
    "vidematt": "เลื่อนต่อเนื่อง",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "วิดีโอแบบ MPEG-1",
    "videmp2v": "วิดีโอแบบ MPEG-2",
    "videmp4v": "วิดีโอแบบ MPEG-4",
    "videmplo": "ระเบิดภายใน",
    "videmuxa": "HEVC ที่มี Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "ไม่ทราบ",
    "videpng ": "PNG",
    "videpush": "ผลัก",
    "videpxlt": "วิดีโอ Apple Pixlet",
    "videqdh1": "Dolby Vision HEVC (แบบปกป้อง, fragmented MP4)",
    "vider210": "RGB ขนาด 10-บิตแบบไม่บีบอัด",
    "vider408": "ส่วนประกอบของ Y'CbCrA 8-บิต 4:4:4:4 ตามลำดับ A Y' Cb Cr",
    "videRGBA": "RGBA ขนาด 32-บิตแบบไม่บีบอัด",
    "viderle ": "ภาพเคลื่อนไหว",
    "viderpza": "วิดีโอ",
    "vides263": "H.263",
    "videshrp": "ปรับความคมชัด",
    "videslid": "ผลัก",
    "videsmc ": "กราฟิก",
    "videsmpt": "ปัด",
    "videsolr": "ฟิลเตอร์ความสมดุลของสี",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "ฟิลเตอร์ความสมดุลของสี",
    "videtrav": "Traveling Matte",
    "videv210": "ส่วนประกอบของ Y'CbCr 10-บิต 4:2:2",
    "videv216": "ส่วนประกอบของ Y'CbCr 10,12,14,16-บิต 4:2:2",
    "videv308": "ส่วนประกอบของ Y'CbCr 8-บิต 4:4:4",
    "videv408": "ส่วนประกอบของ Y'CbCrA 8-บิต 4:4:4:4 ตามลำดับ Cb Y' Cr A",
    "videv410": "ส่วนประกอบของ Y'CbCr 10-บิต 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-บิต",
    "videxf4c": "XF-AVC Intra 4:4:4 12-บิต",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-บิต",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-บิต",
    "videxfi8": "XF-AVC Intra 4:2:2 8-บิต",
    "videxfia": "XF-AVC Intra 4:2:2 10-บิต",
    "videxplo": "ระเบิดภายใน",
    "videy420": "ส่วนประกอบ Y'CbCr 8-บิต 4:2:0 แบบ Three-Plane",
    "videyuvs": "ส่วนประกอบของ Y'CbCr 8-บิต 4:2:2 ตามลำดับ Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
