/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Erweiterte Untertitel",
    "clcpatcc": "ATSC/52 Teil-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Steuerspur",
    "meta": "Metadaten",
    "metamebx": "Zeitabhängige Metadaten",
    "musimusi": "Musik",
    "muxx": "Muxed",
    "obje": "QTVR-Objekt",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Untertitel",
    "sbtldrmt": "Untertitel",
    "sbtltx3g": "Untertitel",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Ton",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (verschlüsselt)",
    "sounpaac": "AAC (geschützt)",
    "sounpac3": "AC-3 Dolby Digital (geschützt)",
    "sounpach": "HE-AACv1 (geschützt)",
    "sounpacp": "HE-AACv2 (geschützt)",
    "sounpc+3": "Dolby Atmos (geschützt)",
    "sounpec3": "EC-3 Dolby Digital+ (geschützt)",
    "sounqaac": "AAC (geschützt, fragmentiertes MP4)",
    "sounqac3": "AC-3 Dolby Digital (geschützt, fragmentiertes MP4)",
    "sounqach": "HE-AACv1 (geschützt, fragmentiertes MP4)",
    "sounqacp": "HE-AACv2 (geschützt, fragmentiertes MP4)",
    "sounqc+3": "Dolby Atmos (geschützt, fragmentiertes MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (geschützt, fragmentiertes MP4)",
    "sounqlac": "Apple Lossless (geschützt, fragmentiertes MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (geschützt, Transport-Stream)",
    "sounzac3": "AC-3 Dolby Digital (geschützt, Transport-Stream)",
    "sounzach": "HE-AACv1 (geschützt, Transport-Stream)",
    "sounzacp": "HE-AACv2 (geschützt, Transport-Stream)",
    "sounzc+3": "Dolby Atmos (geschützt, Transport-Stream)",
    "sounzec3": "EC-3 Dolby Digital+ (geschützt, Transport-Stream)",
    "sounzlac": "Apple Lossless (geschützt, Transport-Stream)",
    "sprt": "Sprite",
    "strm": "Streaming",
    "strmrtsp": "Streaming",
    "text": "Text",
    "texttext": "QuickTime Text",
    "texttx3g": "3GPP Text",
    "tmcd": "Timecode",
    "tmcdtmcd": "Timecode",
    "tmet": "Zeitabhängige Metadaten",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Unkomprimiertes 1-Bit Indizierte Farben",
    "vide2": "Unkomprimiertes 2-Bit Indizierte Farben",
    "vide2vuy": "Component Y'CbCr 8-Bit 4:2:2 als Cb Y'0 Cr Y'1",
    "vide4": "Unkomprimiertes 4-Bit Indizierte Farben",
    "vide8": "Unkomprimiertes 8-Bit Indizierte Farben",
    "vide8BPS": "Planar RGB",
    "vide16": "Unkomprimiertes 16-Bit RGB 555 (Big Endian)",
    "vide24": "Unkomprimiertes 24-Bit RGB",
    "vide24BG": "Unkomprimiertes 24-Bit BGR",
    "vide32": "Unkomprimiertes 32-Bit ARGB",
    "vide33": "Unkomprimiertes 1-Bit Graustufen",
    "vide34": "Unkomprimiertes 2-Bit Graustufen",
    "vide36": "Unkomprimiertes 4-Bit Graustufen",
    "vide40": "Unkomprimiertes 8-Bit Graustufen",
    "vide5551": "Unkomprimiertes 16-Bit RGB 5551 (Little Endian)",
    "videa2vy": "Two-Plane Component Y'CbCr,A 8-Bit 4:2:2,4",
    "videABGR": "Unkomprimiertes 32-Bit ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Parameter-Sets in Bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Unkomprimiertes 16-Bit Graustufen",
    "videb32a": "Unkomprimiertes 32-Bit AlphaGray",
    "videb48r": "Unkomprimiertes 48-Bit RGB",
    "videb64a": "Unkomprimiertes 64-Bit ARGB",
    "videB565": "Unkomprimiertes 16-Bit RGB 565 (Big Endian)",
    "videBGRA": "Unkomprimiertes 32-Bit BGRA",
    "videbhiv": "bhiv",
    "videblur": "Komplexer Filter",
    "videcdh1": "Dolby Vision HEVC (verschlüsselt)",
    "videclou": "Wolken",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0-Medien",
    "videdslv": "Weiches Überblenden",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Komplexer Filter",
    "videfire": "Feuer",
    "videfmns": "Filmbeschädigungen",
    "videgenk": "Komplexer Filter",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-Bit 4:2:2",
    "videhev1": "HEVC (Parameter-Sets in Bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ Video 5.1",
    "videjpeg": "Foto - JPEG",
    "videJvt3": "Apple H.264/AVC Video (Vorschau)",
    "videkpcd": "Foto-CD",
    "videL555": "Unkomprimiertes 16-Bit RGB 555 (Little Endian)",
    "videL565": "Unkomprimiertes 16-Bit RGB 565 (Little Endian)",
    "vidematt": "Überblenden mit Maske",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1-Video",
    "videmp2v": "MPEG-2-Video",
    "videmp4v": "MPEG-4-Video",
    "videmplo": "Zusammenziehen",
    "videmuxa": "HEVC mit Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 MBit/s)",
    "videmx3p": "MPEG IMX 625/50 (30 MBit/s)",
    "videmx4n": "MPEG IMX 525/60 (40 MBit/s)",
    "videmx4p": "MPEG IMX 625/50 (40 MBit/s)",
    "videmx5n": "MPEG IMX 525/60 (50 MBit/s)",
    "videmx5p": "MPEG IMX 625/50 (50 MBit/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Unbekannt",
    "videpng ": "PNG",
    "videpush": "Schieben",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (geschützt, fragmentiertes MP4)",
    "vider210": "Unkomprimiertes 10-Bit RGB",
    "vider408": "Component Y'CbCrA 8-Bit 4:4:4:4 als A Y' Cb Cr",
    "videRGBA": "Unkomprimiertes 32-Bit RGBA",
    "viderle ": "Animation",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Komplexer Filter",
    "videslid": "Schieben",
    "videsmc ": "Grafiken",
    "videsmpt": "Wischen",
    "videsolr": "Farbabgleich",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Farbabgleich",
    "videtrav": "Stanzmaske",
    "videv210": "Component Y'CbCr 10-Bit 4:2:2",
    "videv216": "Component Y'CbCr 10,12,14,16-Bit 4:2:2",
    "videv308": "Component Y'CbCr 8-Bit 4:4:4",
    "videv408": "Component Y'CbCrA 8-Bit 4:4:4:4 als Cb Y' Cr A",
    "videv410": "Component Y'CbCr 10-Bit 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Zusammenziehen",
    "videy420": "Three-Plane Component Y'CbCr 8-Bit 4:2:0",
    "videyuvs": "Component Y'CbCr 8-Bit 4:2:2 als Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
