/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Κλειστές λεζάντες",
    "clcpatcc": "ATSC/52 μέρος-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Υπόδειξη",
    "meta": "Μεταδεδομένα",
    "metamebx": "Χρονισμένα μεταδεδομένα",
    "musimusi": "Μουσική",
    "muxx": "Πολυπλεγμένο",
    "obje": "Αντικείμενο QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Υπότιτλος",
    "sbtldrmt": "Υπότιτλος",
    "sbtltx3g": "Υπότιτλος",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Εμφάνιση",
    "skinskcr": "Εμφάνιση",
    "skinskdr": "Εμφάνιση",
    "soun": "Ήχος",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (κρυπτογραφημένο)",
    "sounpaac": "AAC (προστατευμένο)",
    "sounpac3": "AC-3 Dolby Digital (προστατευμένο)",
    "sounpach": "HE-AACv1 (προστατευμένο)",
    "sounpacp": "HE-AACv2 (προστατευμένο)",
    "sounpc+3": "Dolby Atmos (προστατευμένο)",
    "sounpec3": "EC-3 Dolby Digital+ (προστατευμένο)",
    "sounqaac": "AAC (προστατευμένο, κατακερματισμένο MP4)",
    "sounqac3": "AC-3 Dolby Digital (προστατευμένο, κατακερματισμένο MP4)",
    "sounqach": "HE-AACv1 (προστατευμένο, κατακερματισμένο MP4)",
    "sounqacp": "HE-AACv2 (προστατευμένο, κατακερματισμένο MP4)",
    "sounqc+3": "Dolby Atmos (προστατευμένο, κατακερματισμένο MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (προστατευμένο, κατακερματισμένο MP4)",
    "sounqlac": "Apple Lossless (προστατευμένο, κατακερματισμένο MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (προστατευμένο, ροή μεταφοράς)",
    "sounzac3": "AC-3 Dolby Digital (προστατευμένο, ροή μεταφοράς)",
    "sounzach": "HE-AACv1 (προστατευμένο, ροή μεταφοράς)",
    "sounzacp": "HE-AACv2 (προστατευμένο, ροή μεταφοράς)",
    "sounzc+3": "Dolby Atmos (προστατευμένο, ροή μεταφοράς)",
    "sounzec3": "EC-3 Dolby Digital+ (προστατευμένο, ροή μεταφοράς)",
    "sounzlac": "Apple Lossless (προστατευμένο, ροή μεταφοράς)",
    "sprt": "Sprite",
    "strm": "Ροή",
    "strmrtsp": "Ροή",
    "text": "Κείμενο",
    "texttext": "Κείμενο QuickTime",
    "texttx3g": "Κείμενο 3GPP",
    "tmcd": "Κωδικός χρόνου",
    "tmcdtmcd": "Κωδικός χρόνου",
    "tmet": "Χρονισμένα μεταδεδομένα",
    "twen": "Tween",
    "vide": "Βίντεο",
    "vide1": "Ασυμπίεστο δεικτοδοτημένο χρώμα 1 bit",
    "vide2": "Ασυμπίεστο 2 bit δεικτοδοτημένο χρώμα",
    "vide2vuy": "Component Y'CbCr 8-bit 4:2:2 ordered Cb Y'0 Cr Y'1",
    "vide4": "Ασυμπίεστο 4 bit δεικτοδοτημένο χρώμα",
    "vide8": "Ασυμπίεστο 8 bit δεικτοδοτημένο χρώμα",
    "vide8BPS": "Επίπεδο RGB",
    "vide16": "Ασυμπίεστο 16 bit RGB 555 (Big Endian)",
    "vide24": "Ασυμπίεστο 24 bit RGB",
    "vide24BG": "Ασυμπίεστο 24 bit BGR",
    "vide32": "Ασυμπίεστο 32 bit ARGB",
    "vide33": "Ασυμπίεστο 1 bit κλίμακα του γκρι",
    "vide34": "Ασυμπίεστο 2 bit κλίμακα του γκρι",
    "vide36": "Ασυμπίεστο 4 bit κλίμακα του γκρι",
    "vide40": "Ασυμπίεστο 8 bit κλίμακα του γκρι",
    "vide5551": "Ασυμπίεστο 16 bit RGB 5551 (Little Endian)",
    "videa2vy": "Two-Plane Component Y'CbCr,A 8-bit 4:2:2,4",
    "videABGR": "Ασυμπίεστο 32 bit ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (σύνολα παραμέτρων στη ροή bit)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Ασυμπίεστο 16 bit κλίμακα του γκρι",
    "videb32a": "Ασυμπίεστο 32 bit AlphaGray",
    "videb48r": "Ασυμπίεστο 48 bit RGB",
    "videb64a": "Ασυμπίεστο 64 bit ARGB",
    "videB565": "Ασυμπίεστο 16 bit RGB 565 (Big Endian)",
    "videBGRA": "Ασυμπίεστο 32 bit BGRA",
    "videbhiv": "bhiv",
    "videblur": "Φίλτρο συνέλιξης",
    "videcdh1": "Dolby Vision HEVC (κρυπτογραφημένο)",
    "videclou": "Cloud",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "Μέσο AVC0",
    "videdslv": "Διασταυρούμενο βαθμιαίο σβήσιμο",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Φίλτρο συνέλιξης",
    "videfire": "Φωτιά",
    "videfmns": "Φίλτρο θορύβου φιλμ",
    "videgenk": "Φίλτρο συνέλιξης",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 bit 4:2:2",
    "videhev1": "HEVC (σύνολα παραμέτρων στη ροή bit)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Βίντεο Indeo™ 5.1",
    "videjpeg": "Φωτογραφία - JPEG",
    "videJvt3": "Βίντεο Apple H.264/AVC (Προεπισκόπηση)",
    "videkpcd": "CD φωτογραφιών",
    "videL555": "Ασυμπίεστο 16 bit RGB 555 (Little Endian)",
    "videL565": "Ασυμπίεστο 16 bit RGB 565 (Little Endian)",
    "vidematt": "Βαθμιαίο σβήσιμο",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Βίντεο MPEG-1",
    "videmp2v": "Βίντεο MPEG-2",
    "videmp4v": "Βίντεο MPEG-4",
    "videmplo": "Implode",
    "videmuxa": "HEVC με άλφα",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/δευτ.)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/δευτ.)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/δευτ.)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/δευτ.)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/δευτ.)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/δευτ.)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Άγνωστο",
    "videpng ": "PNG",
    "videpush": "Ώθηση",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (προστατευμένο, κατακερματισμένο MP4)",
    "vider210": "Ασυμπίεστο 10 bit RGB",
    "vider408": "Component Y'CbCrA 8-bit 4:4:4:4 ordered A Y' Cb Cr",
    "videRGBA": "Ασυμπίεστο 32 bit RGBA",
    "viderle ": "Κινούμενη σχεδίαση",
    "viderpza": "Βίντεο",
    "vides263": "H.263",
    "videshrp": "Φίλτρο συνέλιξης",
    "videslid": "Ώθηση",
    "videsmc ": "Γραφικά",
    "videsmpt": "Σκούπισμα",
    "videsolr": "Φίλτρο εξισορρόπησης χρωμάτων",
    "videSVQ1": "Βίντεο Sorenson",
    "videSVQ3": "Βίντεο Sorenson3",
    "videtiff": "TIFF",
    "videtint": "Φίλτρο εξισορρόπησης χρωμάτων",
    "videtrav": "Κινούμενη μάσκα",
    "videv210": "Component Y'CbCr 10-bit 4:2:2",
    "videv216": "Component Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Component Y'CbCr 8-bit 4:4:4",
    "videv408": "Component Y'CbCrA 8-bit 4:4:4:4 ordered Cb Y' Cr A",
    "videv410": "Component Y'CbCr 10-bit 4:4:4",
    "videVP31": "Βίντεο On2 VP3 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10 bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12 bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10 bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8 bit",
    "videxfia": "XF-AVC Intra 4:2:2 10 bit",
    "videxplo": "Implode",
    "videy420": "Three-Plane Component Y'CbCr 8-bit 4:2:0",
    "videyuvs": "Component Y'CbCr 8-bit 4:2:2 ordered Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
