/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Sous-titres codés",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Indication",
    "meta": "Métadonnées",
    "metamebx": "Métadonnées chronométrées",
    "musimusi": "Musique",
    "muxx": "Multiplexé",
    "obje": "Objet QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Sous-titre",
    "sbtldrmt": "Sous-titre",
    "sbtltx3g": "Sous-titre",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Apparence",
    "skinskcr": "Apparence",
    "skinskdr": "Apparence",
    "soun": "Son",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (chiffré)",
    "sounpaac": "AAC (protégé)",
    "sounpac3": "AC‑3 Dolby Digital (protégé)",
    "sounpach": "HE‑AACv1 (protégé)",
    "sounpacp": "HE‑AACv2 (protégé)",
    "sounpc+3": "Dolby Atmos (protégé)",
    "sounpec3": "EC‑3 Dolby Digital+ (protégé)",
    "sounqaac": "AAC (protégé, MP4 fragmenté)",
    "sounqac3": "AC‑3 Dolby Digital (protégé, MP4 fragmenté)",
    "sounqach": "HE‑AACv1 (protégé, MP4 fragmenté)",
    "sounqacp": "HE‑AACv2 (protégé, MP4 fragmenté)",
    "sounqc+3": "Dolby Atmos (protégé, MP4 fragmenté)",
    "sounqec3": "EC‑3 Dolby Digital+ (protégé, MP4 fragmenté)",
    "sounqlac": "Apple Lossless (protégé, MP4 fragmenté)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protégé, flux de transport)",
    "sounzac3": "AC‑3 Dolby Digital (protégé, flux de transport)",
    "sounzach": "HE‑AACv1 (protégé, flux de transport)",
    "sounzacp": "HE‑AACv2 (protégé, flux de transport)",
    "sounzc+3": "Dolby Atmos (protégé, flux de transport)",
    "sounzec3": "EC‑3 Dolby Digital+ (protégé, flux de transport)",
    "sounzlac": "Apple Lossless (protégé, flux de transport)",
    "sprt": "Icône animée",
    "strm": "Diffusion",
    "strmrtsp": "Diffusion",
    "text": "Texte",
    "texttext": "QuickTime Text",
    "texttx3g": "3GPP Text",
    "tmcd": "Code temporel",
    "tmcdtmcd": "Code temporel",
    "tmet": "Métadonnées chronométrées",
    "twen": "Forme intermédiaire",
    "vide": "Vidéo",
    "vide1": "Couleurs indexées 1 bit sans compression",
    "vide2": "Couleurs indexées 2 bits sans compression",
    "vide2vuy": "Composants Y’CbCr 8 bits 4:2:2 ordre Cb Y’0 Cr Y’1",
    "vide4": "Couleurs indexées 4 bits sans compression",
    "vide8": "Couleurs indexées 8 bits sans compression",
    "vide8BPS": "RVB Plan",
    "vide16": "RVB 555 (gros-boutiste) 16 bits sans compression",
    "vide24": "RVB 24 bits sans compression",
    "vide24BG": "BVR 24 bits sans compression",
    "vide32": "ARVB 32 bits sans compression",
    "vide33": "Échelle de gris 1 bit sans compression",
    "vide34": "Échelle de gris 2 bits sans compression",
    "vide36": "Échelle de gris 4 bits sans compression",
    "vide40": "Échelle de gris 8 bits sans compression",
    "vide5551": "RVB 5551 (petit-boutiste) 16 bits sans compression",
    "videa2vy": "Composants deux plans Y’CbCr,A 8 bits 4:2:2,4",
    "videABGR": "ABVR 32 bits sans compression",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 serveur mandataire",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Ensemble de paramètres dans Bitstream)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Animation JPEG AVR",
    "videb16g": "Échelle de gris 16 bits sans compression",
    "videb32a": "Gris alpha 32 bits sans compression",
    "videb48r": "RVB 48 bits sans compression",
    "videb64a": "ARVB 64 bits sans compression",
    "videB565": "RVB 565 (gros-boutiste) 16 bits sans compression",
    "videBGRA": "BVRA 32 bits sans compression",
    "videbhiv": "bhiv",
    "videblur": "Filtre de convolution",
    "videcdh1": "Dolby Vision HEVC (chiffré)",
    "videclou": "Nuage",
    "videcvid": "Cinepak",
    "videdmb1": "Animation JPEG OpenDML",
    "videdrmi": "Média AVC0",
    "videdslv": "Fondu enchaîné",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtre de convolution",
    "videfire": "Flamme",
    "videfmns": "Filtre de bruit",
    "videgenk": "Filtre de convolution",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 bits 4:2:2",
    "videhev1": "HEVC (Ensemble de paramètres dans Bitstream)",
    "videhvc1": "HEVC",
    "videicod": "Codec Apple Intermediate",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Photo – JPEG",
    "videJvt3": "Vidéo H.264/AVC Apple (aperçu)",
    "videkpcd": "Photo CD",
    "videL555": "RVB 555 (petit-boutiste) 16 bits sans compression",
    "videL565": "RVB 565 (petit-boutiste) 16 bits sans compression",
    "vidematt": "Alternance",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Animation JPEG A",
    "videmjpb": "Animation JPEG B",
    "videmp1v": "Vidéo MPEG-1",
    "videmp2v": "Vidéo MPEG-2",
    "videmp4v": "Vidéo MPEG-4",
    "videmplo": "Implosion",
    "videmuxa": "HEVC avec Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Mo/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mo/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mo/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mo/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mo/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mo/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Inconnu",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (protégé, MP4 fragmenté)",
    "vider210": "RVB 10 bits sans compression",
    "vider408": "Composants Y’CbCrA 8 bits 4:4:4:4 ordre A Y’ Cb Cr",
    "videRGBA": "RVBA 32 bits sans compression",
    "viderle ": "Animation",
    "viderpza": "Vidéo",
    "vides263": "H.263",
    "videshrp": "Filtre de convolution",
    "videslid": "Push",
    "videsmc ": "Graphisme",
    "videsmpt": "Balayage",
    "videsolr": "Filtre d’équilibre des couleurs",
    "videSVQ1": "Vidéo Sorenson",
    "videSVQ3": "Vidéo Sorenson 3",
    "videtiff": "TIFF",
    "videtint": "Filtre d’équilibre des couleurs",
    "videtrav": "Motif mobile",
    "videv210": "Composants Y’CbCr 10 bits 4:2:2",
    "videv216": "Composants Y’CbCr 10,12,14,16 bits 4:2:2",
    "videv308": "Composants Y’CbCr 8 bits 4:4:4",
    "videv408": "Composants Y’CbCrA 8 bits 4:4:4:4 ordre Cb Y’ Cr A",
    "videv410": "Composants Y’CbCr 10 bits 4:4:4",
    "videVP31": "On2 VP3 Vidéo 3.2",
    "videxalg": "XAVC groupe d’image long",
    "videxf4a": "XF-AVC Intra 4:4:4 10 bits",
    "videxf4c": "XF-AVC Intra 4:4:4 12 bits",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 bits",
    "videxfga": "XF-AVC Long GOP 4:2:2 10 bits",
    "videxfi8": "XF-AVC Intra 4:2:2 8 bits",
    "videxfia": "XF-AVC Intra 4:2:2 10 bits",
    "videxplo": "Implosion",
    "videy420": "Composants trois plans Y’CbCr 8 bits 4:2:0",
    "videyuvs": "Composants Y’CbCr 8 bits 4:2:2 ordre Y’0 Cb Y’1 Cr",
    "videzygo": "ZyGoVideo",
]
