/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Kuvaileva tekstitys",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Vihje",
    "meta": "Metadata",
    "metamebx": "Ajastettu metadata",
    "musimusi": "Musiikki",
    "muxx": "Muksattu",
    "obje": "QTVR-objekti",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR-panoraama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Tekstitys",
    "sbtldrmt": "Tekstitys",
    "sbtltx3g": "Tekstitys",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Ääni",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (salattu)",
    "sounpaac": "AAC (suojattu)",
    "sounpac3": "AC-3 Dolby Digital (suojattu)",
    "sounpach": "HE-AACv1 (suojattu)",
    "sounpacp": "HE-AACv2 (suojattu)",
    "sounpc+3": "Dolby Atmos (suojattu)",
    "sounpec3": "EC-3 Dolby Digital+ (suojattu)",
    "sounqaac": "AAC (suojattu, paloiteltu MP4)",
    "sounqac3": "AC-3 Dolby Digital (suojattu, paloiteltu MP4)",
    "sounqach": "HE-AACv1 (suojattu, paloiteltu MP4)",
    "sounqacp": "HE-AACv2 (suojattu, paloiteltu MP4)",
    "sounqc+3": "Dolby Atmos (suojattu, paloiteltu MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (suojattu, paloiteltu MP4)",
    "sounqlac": "Apple Lossless (suojattu, paloiteltu MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (suojattu, siirtovirta)",
    "sounzac3": "AC-3 Dolby Digital (suojattu, siirtovirta)",
    "sounzach": "HE-AACv1 (suojattu, siirtovirta)",
    "sounzacp": "HE-AACv2 (suojattu, siirtovirta)",
    "sounzc+3": "Dolby Atmos (suojattu, siirtovirta)",
    "sounzec3": "EC-3 Dolby Digital+ (suojattu, siirtovirta)",
    "sounzlac": "Apple Lossless (suojattu, siirtovirta)",
    "sprt": "Hahmo",
    "strm": "Striimaus",
    "strmrtsp": "Striimaus",
    "text": "Teksti",
    "texttext": "QuickTime-teksti",
    "texttx3g": "3GPP-teksti",
    "tmcd": "Aikakoodi",
    "tmcdtmcd": "Aikakoodi",
    "tmet": "Ajastettu metadata",
    "twen": "Liike",
    "vide": "Video",
    "vide1": "Pakkaamaton 1-bittinen indeksoitu väri",
    "vide2": "Pakkaamaton 2-bittinen indeksoitu väri",
    "vide2vuy": "Komponentti Y'CbCr 8-bittinen 4:2:2 järjestetty Cb Y'0 Cr Y'1",
    "vide4": "Pakkaamaton 4-bittinen indeksoitu väri",
    "vide8": "Pakkaamaton 8-bittinen indeksoitu väri",
    "vide8BPS": "Planar RGB",
    "vide16": "Pakkaamaton 16-bittinen RGB 555 (big-endian)",
    "vide24": "Pakkaamaton 24-bittinen RGB",
    "vide24BG": "Pakkaamaton 24-bittinen BGR",
    "vide32": "Pakkaamaton 32-bittinen ARGB",
    "vide33": "Pakkaamaton 1-bittinen harmaasävy",
    "vide34": "Pakkaamaton 2-bittinen harmaasävy",
    "vide36": "Pakkaamaton 4-bittinen harmaasävy",
    "vide40": "Pakkaamaton 8-bittinen harmaasävy",
    "vide5551": "Pakkaamaton 16-bittinen RGB 5551 (little-endian)",
    "videa2vy": "Kaksitasoinen komponentti Y'CbCr,A 8-bittinen 4:2:2,4",
    "videABGR": "Pakkaamaton 32-bittinen ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (parametrisarjat bittivirrassa)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Pakkaamaton 16-bittinen harmaasävy",
    "videb32a": "Pakkaamaton 32-bittinen AlphaGray",
    "videb48r": "Pakkaamaton 48-bittinen RGB",
    "videb64a": "Pakkaamaton 64-bittinen ARGB",
    "videB565": "Pakkaamaton 16-bittinen RGB 565 (big-endian)",
    "videBGRA": "Pakkaamaton 32-bittinen BGRA",
    "videbhiv": "bhiv",
    "videblur": "Konvoluutiosuodatin",
    "videcdh1": "Dolby Vision HEVC (salattu)",
    "videclou": "Pilvi",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0-media",
    "videdslv": "Ristihäivytys",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Konvoluutiosuodatin",
    "videfire": "Tuli",
    "videfmns": "Filmikohinasuodatin",
    "videgenk": "Konvoluutiosuodatin",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bittinen 4:2:2",
    "videhev1": "HEVC (parametrisarjat bittivirrassa)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Kuva - JPEG",
    "videJvt3": "Apple H.264/AVC-video (esikatselu)",
    "videkpcd": "Kuva-CD",
    "videL555": "Pakkaamaton 16-bittinen RGB 555 (little-endian)",
    "videL565": "Pakkaamaton 16-bittinen RGB 565 (little-endian)",
    "vidematt": "Liukupyyhkäisy",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1-video",
    "videmp2v": "MPEG-2-video",
    "videmp4v": "MPEG-4-video",
    "videmplo": "Luhistuminen",
    "videmuxa": "HEVC alfalla",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Tuntematon",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet -video",
    "videqdh1": "Dolby Vision HEVC (suojattu, paloiteltu MP4)",
    "vider210": "Pakkaamaton 10-bittinen RGB",
    "vider408": "Komponentti Y'CbCrA 8-bittinen 4:4:4:4 järjestetty A Y' Cb Cr",
    "videRGBA": "Pakkaamaton 32-bittinen RGBA",
    "viderle ": "Animaatio",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Konvoluutiosuodatin",
    "videslid": "Push",
    "videsmc ": "Grafiikka",
    "videsmpt": "Pyyhkäisy",
    "videsolr": "Väritasapainosuodatin",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Väritasapainosuodatin",
    "videtrav": "Liikkuva maski",
    "videv210": "Komponentti Y'CbCr 10-bittinen 4:2:2",
    "videv216": "Komponentti Y'CbCr 10-,12-,14-,16-bittinen 4:2:2",
    "videv308": "Komponentti Y'CbCr 8-bittinen 4:4:4",
    "videv408": "Komponentti Y'CbCrA 8-bittinen 4:4:4:4 järjestetty Cb Y' Cr A",
    "videv410": "Komponentti Y'CbCr 10-bittinen 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bittinen",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bittinen",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bittinen",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bittinen",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bittinen",
    "videxfia": "XF-AVC Intra 4:2:2 10-bittinen",
    "videxplo": "Luhistuminen",
    "videy420": "Kolmitasoinen komponentti Y'CbCr 8-bittinen 4:2:0",
    "videyuvs": "Komponentti Y'CbCr 8-bittinen 4:2:2 järjestetty Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
