/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Subtitrare complexă",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Indiciu",
    "meta": "Metadate",
    "metamebx": "Metadate temporale",
    "musimusi": "Muzică",
    "muxx": "Multiplexat",
    "obje": "Obiect QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panoramă VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Subtitrare",
    "sbtldrmt": "Subtitrare",
    "sbtltx3g": "Subtitrare",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Înfățișare",
    "skinskcr": "Înfățișare",
    "skinskdr": "Înfățișare",
    "soun": "Sunet",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (criptat)",
    "sounpaac": "AAC (protejat)",
    "sounpac3": "AC-3 Dolby Digital (protejat)",
    "sounpach": "HE-AACv1 (protejat)",
    "sounpacp": "HE-AACv2 (protejat)",
    "sounpc+3": "Dolby Atmos (protejat)",
    "sounpec3": "EC-3 Dolby Digital+ (protejat)",
    "sounqaac": "AAC (protejat, MP4 fragmentat)",
    "sounqac3": "AC-3 Dolby Digital (protejat, MP4 fragmentat)",
    "sounqach": "HE-AACv1 (protejat, MP4 fragmentat)",
    "sounqacp": "HE-AACv2 (protejat, MP4 fragmentat)",
    "sounqc+3": "Dolby Atmos (protejat, MP4 fragmentat)",
    "sounqec3": "EC-3 Dolby Digital+ (protejat, MP4 fragmentat)",
    "sounqlac": "Apple Lossless (protejat, MP4 fragmentat)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protejat, flux de transport)",
    "sounzac3": "AC-3 Dolby Digital (protejat, flux de transport)",
    "sounzach": "HE-AACv1 (protejat, flux de transport)",
    "sounzacp": "HE-AACv2 (protejat, flux de transport)",
    "sounzc+3": "Dolby Atmos (protejat, flux de transport)",
    "sounzec3": "EC-3 Dolby Digital+ (protejat, flux de transport)",
    "sounzlac": "Apple Lossless (protejat, flux de transport)",
    "sprt": "Sprite",
    "strm": "Difuzare în flux",
    "strmrtsp": "Difuzare în flux",
    "text": "Text",
    "texttext": "Text QuickTime",
    "texttx3g": "Text 3GPP",
    "tmcd": "Cod de timp",
    "tmcdtmcd": "Cod de timp",
    "tmet": "Metadate temporale",
    "twen": "Intermediar",
    "vide": "Video",
    "vide1": "Culoare indexată, 1 bit, necomprimat",
    "vide2": "Culoare indexată, 2 biți, necomprimat",
    "vide2vuy": "Component Y'CbCr 8 biți 4:2:2 în ordinea Cb Y'0 Cr Y'1",
    "vide4": "Culoare indexată, 4 biți, necomprimat",
    "vide8": "Culoare indexată, 8 biți, necomprimat",
    "vide8BPS": "RGB Planar",
    "vide16": "RGB 555, 16 biți, necomprimat (Big Endian)",
    "vide24": "RGB, 24 biți, necomprimat",
    "vide24BG": "BGR, 24 biți, necomprimat",
    "vide32": "ARGB, 32 biți, necomprimat",
    "vide33": "Tonuri de gri, 1 bit, necomprimat",
    "vide34": "Tonuri de gri, 2 biți, necomprimat",
    "vide36": "Tonuri de gri, 4 biți, necomprimat",
    "vide40": "Tonuri de gri, 8 biți, necomprimat",
    "vide5551": "RGB 5551, 16 biți, necomprimat (Little Endian)",
    "videa2vy": "Component în două planuri Y'CbCr,A 8 biți 4:2:2,4",
    "videABGR": "ABGR, 32 biți, necomprimat",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (seturi de parametri în flux de biți)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Tonuri de gri, 16 biți, necomprimat",
    "videb32a": "AlphaGray, 32 biți, necomprimat",
    "videb48r": "RGB, 48 biți, necomprimat",
    "videb64a": "ARGB, 64 biți, necomprimat",
    "videB565": "RGB 565, 16 biți, necomprimat (Big Endian)",
    "videBGRA": "BGRA, 32 biți, necomprimat",
    "videbhiv": "bhiv",
    "videblur": "Filtru de convoluție",
    "videcdh1": "Dolby Vision HEVC (criptat)",
    "videclou": "Nor",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Anșeneu",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtru de convoluție",
    "videfire": "Foc",
    "videfmns": "Filtru de zgomot film",
    "videgenk": "Filtru de convoluție",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC, 10 biți, 4:2:2",
    "videhev1": "HEVC (seturi de parametri în flux de biți)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Photo - JPEG",
    "videJvt3": "Video Apple H.264/AVC (previzualizare)",
    "videkpcd": "Photo CD",
    "videL555": "RGB 555, 16 biți, necomprimat (Little Endian)",
    "videL565": "RGB 565, 16 biți, necomprimat (Little Endian)",
    "vidematt": "Ștergere gradient",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Video MPEG-1",
    "videmp2v": "Video MPEG-2",
    "videmp4v": "Video MPEG-4",
    "videmplo": "Implozie",
    "videmuxa": "HEVC cu alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "necunoscută",
    "videpng ": "PNG",
    "videpush": "Împingere",
    "videpxlt": "Video Apple Pixlet",
    "videqdh1": "Dolby Vision HEVC (protejat, MP4 fragmentat)",
    "vider210": "RGB, 10 biți, necomprimat",
    "vider408": "Component Y'CbCrA 8 biți 4:4:4:4 în ordinea A Y' Cb Cr",
    "videRGBA": "RGBA, 32 biți, necomprimat",
    "viderle ": "Animație",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Filtru de convoluție",
    "videslid": "Împingere",
    "videsmc ": "Grafică",
    "videsmpt": "Ștergere",
    "videsolr": "Filtru de balans de culoare",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filtru de balans de culoare",
    "videtrav": "Traveling Matte",
    "videv210": "Componente Y'CbCr 10 biți 4:2:2",
    "videv216": "Componente Y'CbCr 10,12,14,16 biți 4:2:2",
    "videv308": "Componente Y'CbCr 8 biți 4:4:4",
    "videv408": "Componente Y'CbCrA 8 biți 4:4:4:4 în ordinea Cb Y' Cr A",
    "videv410": "Componente Y'CbCr 10 biți 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10 biți",
    "videxf4c": "XF-AVC Intra 4:4:4 12 biți",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8 biți",
    "videxfga": "XF-AVC Long GOP 4:2:2 10 biți",
    "videxfi8": "XF-AVC Intra 4:2:2 8 biți",
    "videxfia": "XF-AVC Intra 4:2:2 10 biți",
    "videxplo": "Implozie",
    "videy420": "Component în trei planuri Y'CbCr 8 biți 4:2:0",
    "videyuvs": "Componente Y'CbCr 8 biți 4:2:2 ordine Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
