/// Generated from AVAssetExportPresets.plist
let AVAssetExportPresets = [
    "AVAssetExportPreset3GPRelease6MMS": [
        "Audio": [
            "audioPreset": "Preset_AMR_8kHz_Mono_12kbit_CBR",
            "minAudioBitRate": 12800,
        ],
        "audioInterleavingAdvance": 0.500000,
        "maxFileSize": 1_228_800,
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 15,
            "frameDurationValue": 1,
            "height": 240,
            "maxFrameRate": 16,
            "maxHeight": 240,
            "maxWidth": 320,
            "minHeight": 96,
            "minVideoBitRate": 64000,
            "minWidth": 128,
            "profileLevel": "H264_Baseline_AutoLevel",
            "scalingMode": "Letterbox",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 131_072,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "ApplyRotation",
            "width": 320,
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPreset640x480": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "maxHeight": 640,
            "maxWidth": 640,
            "profileLevel": "H264_Main_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 3_500_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPreset960x540": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "maxHeight": 960,
            "maxWidth": 960,
            "profileLevel": "H264_Main_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 5_250_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPreset1280x720": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "maxHeight": 1280,
            "maxWidth": 1280,
            "profileLevel": "H264_Main_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 10_500_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPreset1920x1080": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "entropyMode": "CABAC",
            "maxHeight": 1920,
            "maxWidth": 1920,
            "profileLevel": "H264_High_AutoLevel",
            "videoAverageBitRate": 15_000_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPreset3840x2160": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "entropyMode": "CABAC",
            "maxHeight": 3840,
            "maxWidth": 3840,
            "profileLevel": "H264_High_AutoLevel",
            "videoAverageBitRate": 25_000_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetAppleM4A": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "videoCodec": 1_851_876_449,
        ],
    ],
    "AVAssetExportPresetAudioOnlyMMS": [
        "Audio": [
            "audioPreset": "Preset_AMR_8kHz_Mono_12kbit_CBR",
            "minAudioBitRate": 12800,
        ],
        "audioInterleavingAdvance": 0.500000,
        "maxFileSize": 604_160,
        "Video": [
            "videoCodec": 1_851_876_449,
        ],
    ],
    "AVAssetExportPresetAuxSmall": [
        "Audio": [
            "audioPreset": "Preset_NoAudio",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 30,
            "maxFrameRate": 32,
            "maxHeight": 585,
            "maxWidth": 780,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 800_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "ApplyRotation",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetAVCAnimoji": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 640,
                    "maxWidth": 640,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 600_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 480,
                    "maxWidth": 480,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 550_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 320,
                    "maxWidth": 320,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 320_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 192,
                    "maxWidth": 192,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 120_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetHEVC1920x1080": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2100_HLG",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "SMPTE_ST_2084_PQ",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "maxHeight": 1920,
            "maxWidth": 1920,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 11_250_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetHEVC1920x1080WithAlpha": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "alphaEncoding": true,
            "alphaQuality": 0.750000,
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "maxHeight": 1920,
            "maxWidth": 1920,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 11_250_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetHEVC3840x2160": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2100_HLG",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "SMPTE_ST_2084_PQ",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "maxHeight": 3840,
            "maxWidth": 3840,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 15_000_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetHEVC3840x2160WithAlpha": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "alphaEncoding": true,
            "alphaQuality": 0.750000,
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "maxHeight": 3840,
            "maxWidth": 3840,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 15_000_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetHEVCAnimojiWithAlpha": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "alphaEncoding": true,
                    "alphaQuality": 0.600000,
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 60,
                    "frameDurationValue": 1,
                    "maxFrameRate": 64,
                    "maxHeight": 640,
                    "maxWidth": 640,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 900_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "alphaEncoding": true,
                    "alphaQuality": 0.600000,
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 640,
                    "maxWidth": 640,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 650_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "alphaEncoding": true,
                    "alphaQuality": 0.600000,
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 640,
                    "maxWidth": 640,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 450_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "alphaEncoding": true,
                    "alphaQuality": 0.600000,
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 480,
                    "maxWidth": 480,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 350_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                ],
                "Video": [
                    "alphaEncoding": true,
                    "alphaQuality": 0.600000,
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 320,
                    "maxWidth": 320,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 200_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
                ],
                "Video": [
                    "alphaEncoding": true,
                    "alphaQuality": 0.600000,
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 192,
                    "maxWidth": 192,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 160_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetHEVCHighestQuality": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2100_HLG",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "SMPTE_ST_2084_PQ",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "maxHeight": 3840,
            "maxWidth": 3840,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 15_000_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetHEVCHighestQualityWithAlpha": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "alphaEncoding": true,
            "alphaQuality": 0.750000,
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "maxHeight": 3840,
            "maxWidth": 3840,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 15_000_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetHighestQuality": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "entropyMode": "CABAC",
            "maxHeight": 3840,
            "maxWidth": 3840,
            "profileLevel": "H264_High_AutoLevel",
            "videoAverageBitRate": 25_000_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetICPL": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 90,
            "maxFrameRate": 30,
            "maxHeight": 640,
            "maxWidth": 640,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 880_804,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetICPL480x480": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 90,
            "maxFrameRate": 30,
            "maxHeight": 480,
            "maxWidth": 480,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 880_804,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetICPL960x960": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 90,
            "maxFrameRate": 30,
            "maxHeight": 960,
            "maxWidth": 960,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 3_355_443,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetICPLAux": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 18,
            "maxFrameRate": 32,
            "maxHeight": 480,
            "maxWidth": 640,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 1_150_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetICPLAuxHD": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 18,
            "maxFrameRate": 32,
            "maxHeight": 720,
            "maxWidth": 1280,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 4_400_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetICPLHD": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 90,
            "maxFrameRate": 30,
            "maxHeight": 1280,
            "maxWidth": 1280,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 3_355_443,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetICPLHEVC960x960WithHDR": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2100_HLG",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "SMPTE_ST_2084_PQ",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 30,
            "maxHeight": 960,
            "maxWidth": 960,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 3_355_443,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetICPLHEVC1280x1280WithHDR": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2100_HLG",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "SMPTE_ST_2084_PQ",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 30,
            "maxHeight": 1280,
            "maxWidth": 1280,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 4_200_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetICPLHEVC1440x1440WithHDR": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2100_HLG",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "SMPTE_ST_2084_PQ",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 30,
            "maxHeight": 1440,
            "maxWidth": 1440,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 6_000_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetICPLHEVC1920x1080": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 30,
            "maxHeight": 1080,
            "maxWidth": 1920,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 6_000_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetICPLHEVC1920x1920WithHDR": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPropertyTiers": [
                [
                    "colorPrimaries": "ITU_R_709_2",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "P3_D65",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_709_2",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2020",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "ITU_R_2100_HLG",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
                [
                    "colorPrimaries": "ITU_R_2020",
                    "transferFunction": "SMPTE_ST_2084_PQ",
                    "ycbcrMatrix": "ITU_R_2020",
                ],
            ],
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 30,
            "maxHeight": 1920,
            "maxWidth": 1920,
            "profileLevel": "HEVC_Main_AutoLevel",
            "videoAverageBitRate": 6_000_000,
            "videoCodec": 1_752_589_105,
            "videoMatrixHandling": "PreserveMatrix",
        ],
    ],
    "AVAssetExportPresetLowQuality": [
        "Audio": [
            "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 15,
            "frameDurationValue": 1,
            "maxFrameRate": 16,
            "maxHeight": 192,
            "maxWidth": 192,
            "profileLevel": "H264_Baseline_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 128_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetLowQuality_16x9": [
        "Audio": [
            "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 15,
            "frameDurationValue": 1,
            "maxFrameRate": 16,
            "maxHeight": 224,
            "maxWidth": 224,
            "profileLevel": "H264_Baseline_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 128_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetMail": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
            "audioSettingPerChannelCount": [
                "2": [
                    "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
            ],
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 32,
            "maxHeight": 480,
            "maxWidth": 480,
            "profileLevel": "H264_Baseline_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 700_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetMail_16x9": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
            "audioSettingPerChannelCount": [
                "2": [
                    "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
            ],
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 32,
            "maxHeight": 568,
            "maxWidth": 568,
            "profileLevel": "H264_Baseline_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 700_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetMediumQuality": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
            "audioSettingPerChannelCount": [
                "2": [
                    "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
            ],
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 32,
            "maxHeight": 480,
            "maxWidth": 480,
            "profileLevel": "H264_Main_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 700_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetMediumQuality_16x9": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
            "audioSettingPerChannelCount": [
                "2": [
                    "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
            ],
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 32,
            "maxHeight": 568,
            "maxWidth": 568,
            "profileLevel": "H264_Main_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 700_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetMessage": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 960,
                    "maxWidth": 960,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 1_250_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 640,
                    "maxWidth": 640,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 900_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 480,
                    "maxWidth": 480,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 700_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 320,
                    "maxWidth": 320,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 420_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 192,
                    "maxWidth": 192,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 128_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetMessage_16x9": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 1280,
                    "maxWidth": 1280,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 2_200_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 960,
                    "maxWidth": 960,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 1_250_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 568,
                    "maxWidth": 568,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 700_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 352,
                    "maxWidth": 352,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 420_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 224,
                    "maxWidth": 224,
                    "profileLevel": "H264_Main_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 128_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetMessageAudio": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "audioSettingPerChannelCount": [
                        "2": [
                            "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                            "maxAudioBitRate": 168_000,
                        ],
                    ],
                    "maxAudioBitRate": 168_000,
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetMessageAux": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "entropyMode": "CABAC",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "keyFrameInterval": 18,
                    "maxFrameRate": 32,
                    "maxHeight": 720,
                    "maxWidth": 960,
                    "profileLevel": "H264_High_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 4_400_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "entropyMode": "CABAC",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "keyFrameInterval": 18,
                    "maxFrameRate": 32,
                    "maxHeight": 540,
                    "maxWidth": 720,
                    "profileLevel": "H264_High_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 2_875_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPrimaries": "ITU_R_709_2",
                    "entropyMode": "CABAC",
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "keyFrameInterval": 18,
                    "maxFrameRate": 32,
                    "maxHeight": 480,
                    "maxWidth": 640,
                    "profileLevel": "H264_High_AutoLevel",
                    "transferFunction": "ITU_R_709_2",
                    "videoAverageBitRate": 1_150_000,
                    "videoCodec": 1_635_148_593,
                    "videoMatrixHandling": "PreserveMatrix",
                    "ycbcrMatrix": "ITU_R_709_2",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetMessageHEVCWithHDR": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 960,
                    "maxWidth": 960,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 1_250_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 640,
                    "maxWidth": 640,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 900_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "maxAudioBitRate": 168_000,
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 480,
                    "maxWidth": 480,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 700_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 320,
                    "maxWidth": 320,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 420_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 192,
                    "maxWidth": 192,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 128_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetMessageHEVCWithHDR_16x9": [
        "mediaTiers": [
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 1280,
                    "maxWidth": 1280,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 2_200_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 960,
                    "maxWidth": 960,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 1_250_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 30,
                    "frameDurationValue": 1,
                    "maxFrameRate": 32,
                    "maxHeight": 568,
                    "maxWidth": 568,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 700_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 352,
                    "maxWidth": 352,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 420_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
            [
                "Audio": [
                    "audioPreset": "Preset_AACHE_44kHz_Mono_24kbit",
                    "preserveAlternateTracks": false,
                ],
                "Video": [
                    "colorPropertyTiers": [
                        [
                            "colorPrimaries": "ITU_R_709_2",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "P3_D65",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_709_2",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_709_2",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2020",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "ITU_R_2100_HLG",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                        [
                            "colorPrimaries": "ITU_R_2020",
                            "transferFunction": "SMPTE_ST_2084_PQ",
                            "ycbcrMatrix": "ITU_R_2020",
                        ],
                    ],
                    "frameDurationTimeScale": 15,
                    "frameDurationValue": 1,
                    "maxFrameRate": 16,
                    "maxHeight": 224,
                    "maxWidth": 224,
                    "profileLevel": "HEVC_Main_AutoLevel",
                    "usageMode": 0,
                    "videoAverageBitRate": 128_000,
                    "videoCodec": 1_752_589_105,
                    "videoMatrixHandling": "PreserveMatrix",
                ],
            ],
        ],
    ],
    "AVAssetExportPresetMMS": [
        "Audio": [
            "audioPreset": "Preset_AMR_8kHz_Mono_12kbit_CBR",
            "minAudioBitRate": 12800,
        ],
        "audioInterleavingAdvance": 0.500000,
        "maxFileSize": 604_160,
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 10,
            "frameDurationValue": 1,
            "height": 144,
            "maxFrameRate": 16,
            "maxHeight": 144,
            "maxWidth": 176,
            "minHeight": 96,
            "minVideoBitRate": 90000,
            "minWidth": 128,
            "scalingMode": "Letterbox",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 128_000,
            "videoCodec": 1_748_121_139,
            "videoMatrixHandling": "ApplyRotation",
            "width": 176,
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetPhotoStream": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_128kbit",
        ],
        "Video": [
            "colorPrimaries": "SMPTE_C",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 30,
            "maxFrameRate": 30,
            "maxHeight": 640,
            "maxWidth": 640,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 880_804,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "ApplyRotation",
            "ycbcrMatrix": "ITU_R_601_4",
        ],
    ],
    "AVAssetExportPresetPhotoStreamHD": [
        "Audio": [
            "audioPreset": "Preset_AAC_48kHz_Stereo_160kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "frameReordering": true,
            "keyFrameInterval": 30,
            "maxFrameRate": 30,
            "maxHeight": 1280,
            "maxWidth": 1280,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "usageMode": 0,
            "videoAverageBitRate": 2_936_013,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "ApplyRotation",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetYouTube": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
            "audioSettingPerChannelCount": [
                "2": [
                    "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
            ],
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 32,
            "maxHeight": 480,
            "maxWidth": 480,
            "profileLevel": "H264_Main_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 700_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetYouTube_16x9": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Mono_64kbit",
            "audioSettingPerChannelCount": [
                "2": [
                    "audioPreset": "Preset_AAC_44kHz_Stereo_128kbit",
                    "maxAudioBitRate": 168_000,
                ],
            ],
            "maxAudioBitRate": 168_000,
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "frameDurationTimeScale": 30,
            "frameDurationValue": 1,
            "maxFrameRate": 32,
            "maxHeight": 568,
            "maxWidth": 568,
            "profileLevel": "H264_Main_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 700_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
    "AVAssetExportPresetYouTubeHD": [
        "Audio": [
            "audioPreset": "Preset_AAC_44kHz_Stereo_256kbit",
        ],
        "Video": [
            "colorPrimaries": "ITU_R_709_2",
            "entropyMode": "CABAC",
            "maxHeight": 1280,
            "maxWidth": 1280,
            "profileLevel": "H264_High_AutoLevel",
            "transferFunction": "ITU_R_709_2",
            "videoAverageBitRate": 4_500_000,
            "videoCodec": 1_635_148_593,
            "videoMatrixHandling": "PreserveMatrix",
            "ycbcrMatrix": "ITU_R_709_2",
        ],
    ],
]
