/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Legendas Ocultas",
    "clcpatcc": "ATSC/52 parte-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Sinalizado",
    "meta": "Metadados",
    "metamebx": "Metadados Programados",
    "musimusi": "Música",
    "muxx": "Muxed",
    "obje": "Objeto do QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "Panorama VR",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Legenda",
    "sbtldrmt": "Legenda",
    "sbtltx3g": "Legenda",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Máscara",
    "skinskcr": "Máscara",
    "skinskdr": "Máscara",
    "soun": "Som",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (criptografado)",
    "sounpaac": "AAC (protegido)",
    "sounpac3": "AC-3 Dolby Digital (protegido)",
    "sounpach": "HE-AACv1 (protegido)",
    "sounpacp": "HE-AACv2 (protegido)",
    "sounpc+3": "Dolby Atmos (protegido)",
    "sounpec3": "EC-3 Dolby Digital+ (protegido)",
    "sounqaac": "AAC (protegido, MP4 fragmentado)",
    "sounqac3": "AC-3 Dolby Digital (protegido, MP4 fragmentado)",
    "sounqach": "HE-AACv1 (protegido, MP4 fragmentado)",
    "sounqacp": "HE-AACv2 (protegido, MP4 fragmentado)",
    "sounqc+3": "Dolby Atmos (protegido, MP4 fragmentado)",
    "sounqec3": "EC-3 Dolby Digital+ (protegido, MP4 fragmentado)",
    "sounqlac": "Apple Lossless (protegido, MP4 fragmentado)",
    "sounvdva": "DV",
    "sounzaac": "AAC (protegido, transmissão de transporte)",
    "sounzac3": "AC-3 Dolby Digital (protegido, transmissão de transporte)",
    "sounzach": "HE-AACv1 (protegido, transmissão de transporte)",
    "sounzacp": "HE-AACv2 (protegido, transmissão de transporte)",
    "sounzc+3": "Dolby Atmos (protegido, transmissão de transporte)",
    "sounzec3": "EC-3 Dolby Digital+ (protegido, transmissão de transporte)",
    "sounzlac": "Apple Lossless (protegido, transmissão de transporte)",
    "sprt": "Sprite",
    "strm": "Transmissão",
    "strmrtsp": "Transmissão",
    "text": "Texto",
    "texttext": "Texto do QuickTime",
    "texttx3g": "Texto 3GPP",
    "tmcd": "Código de Tempo",
    "tmcdtmcd": "Código de Tempo",
    "tmet": "Metadados Programados",
    "twen": "Interpolação",
    "vide": "Vídeo",
    "vide1": "Cor indexada de 1 bit não comprimida",
    "vide2": "Cor indexada de 2 bits não comprimida",
    "vide2vuy": "Componente Y'CbCr 8 bits 4:2:2 ordenado Cb Y'0 Cr Y'1",
    "vide4": "Cor indexada de 4 bits não comprimida",
    "vide8": "Cor indexada de 8 bits não comprimida",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555 de 16 bits não comprimido (Big Endian)",
    "vide24": "RGB de 24 bits não comprimido",
    "vide24BG": "BGR de 24 bits não comprimido",
    "vide32": "ARGB de 32 bits não comprimido",
    "vide33": "Tons de cinza de 1 bit não comprimidos",
    "vide34": "Tons de cinzas de 2 bits não comprimidos",
    "vide36": "Tons de cinzas de 4 bits não comprimidos",
    "vide40": "Tons de cinzas de 8 bits não comprimidos",
    "vide5551": "RGB 5551 de 16 bits não comprimido (Little Endian)",
    "videa2vy": "Componente em Dois Planos Y'CbCr,A 8 bits 4:2:2,4",
    "videABGR": "ABGR de 32 bits não comprimido",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (Parâmetro Definido em Sequência de Bits)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Tons de cinzas de 16 bits não comprimidos",
    "videb32a": "AlphaGray de 32 bits não comprimido",
    "videb48r": "RGB de 48 bits não comprimido",
    "videb64a": "ARGB de 64-bits não comprimido",
    "videB565": "RGB 565 de 16 bits não comprimido (Big Endian)",
    "videBGRA": "BGRA de 32 bits não comprimido",
    "videbhiv": "bhiv",
    "videblur": "Filtro de Convolução",
    "videcdh1": "Dolby Vision HEVC (criptografado)",
    "videclou": "Nuvem",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "Mídia AVC0",
    "videdslv": "Desvanecimento Cruzado",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Filtro de Convolução",
    "videfire": "Fogo",
    "videfmns": "Filtro de Ruído de Filme",
    "videgenk": "Filtro de Convolução",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC de 10 bits 4:2:2",
    "videhev1": "HEVC (Coleções de Parâmetros em Sequência de Bits)",
    "videhvc1": "HEVC",
    "videicod": "Codec Intermediário da Apple",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Foto - JPEG",
    "videJvt3": "Vídeo Apple H.264/AVC (Pré-visualização)",
    "videkpcd": "CD de Fotos",
    "videL555": "RGB 555 de 16 bits não comprimido (Little Endian)",
    "videL565": "RGB 565 de 16 bits não comprimido (Little Endian)",
    "vidematt": "Transição por Gradação",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Vídeo MPEG-1",
    "videmp2v": "Vídeo MPEG-2",
    "videmp4v": "Vídeo MPEG-4",
    "videmplo": "Implodir",
    "videmuxa": "HEVC com Alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Desconhecido",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Vídeo Apple Pixlet",
    "videqdh1": "Dolby Vision HEVC (protegido, MP4 fragmentado)",
    "vider210": "RGB de 10 bits não comprimido",
    "vider408": "Componente Y'CbCrA 8 bits 4:4:4:4 ordenado A Y' Cb Cr",
    "videRGBA": "RGBA de 32 bits não comprimido",
    "viderle ": "Animação",
    "viderpza": "Vídeo",
    "vides263": "H.263",
    "videshrp": "Filtro de Convolução",
    "videslid": "Push",
    "videsmc ": "Gráficos",
    "videsmpt": "Varredura",
    "videsolr": "Filtro de Equilíbrio de Cores",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Filtro de Equilíbrio de Cores",
    "videtrav": "Montagem por Composição",
    "videv210": "Componente Y'CbCr 10 bits 4:2:2",
    "videv216": "Componente Y'CbCr 10,12,14,16 bits 4:2:2",
    "videv308": "Componente Y'CbCr 8 bits 4:4:4",
    "videv408": "Componente Y'CbCrA 8 bits 4:4:4:4 ordenado Cb Y' Cr A",
    "videv410": "Componente Y'CbCr 10 bits 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Implodir",
    "videy420": "Componente em Três Planos Y'CbCr 8 bits 4:2:0",
    "videyuvs": "Componente Y'CbCr 8 bits 4:2:2 ordenado Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
