/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Dold textning",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Tips",
    "meta": "Metadata",
    "metamebx": "Tidmetadata",
    "musimusi": "Musik",
    "muxx": "Muxad",
    "obje": "QTVR-objekt",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR-panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Undertext",
    "sbtldrmt": "Undertext",
    "sbtltx3g": "Undertext",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skin",
    "skinskcr": "Skin",
    "skinskdr": "Skin",
    "soun": "Ljud",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (krypterad)",
    "sounpaac": "AAC (skyddad)",
    "sounpac3": "AC-3 Dolby Digital (skyddad)",
    "sounpach": "HE-AACv1 (skyddad)",
    "sounpacp": "HE-AACv2 (skyddad)",
    "sounpc+3": "Dolby Atmos (skyddad)",
    "sounpec3": "EC-3 Dolby Digital+ (skyddad)",
    "sounqaac": "AAC (skyddad, fragmenterad MP4)",
    "sounqac3": "AC-3 Dolby Digital (skyddad, fragmenterad MP4)",
    "sounqach": "HE-AACv1 (skyddad, fragmenterad MP4)",
    "sounqacp": "HE-AACv2 (skyddad, fragmenterad MP4)",
    "sounqc+3": "Dolby Atmos (skyddad, fragmenterad MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (skyddad, fragmenterad MP4)",
    "sounqlac": "Apple Lossless (skyddad, fragmenterad MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (skyddad, transportström)",
    "sounzac3": "AC-3 Dolby Digital (skyddad, transportström)",
    "sounzach": "HE-AACv1 (skyddad, transportström)",
    "sounzacp": "HE-AACv2 (skyddad, transportström)",
    "sounzc+3": "Dolby Atmos (skyddad, transportström)",
    "sounzec3": "EC-3 Dolby Digital+ (skyddad, transportström)",
    "sounzlac": "Apple Lossless (skyddad, transportström)",
    "sprt": "Sprite",
    "strm": "Strömmande",
    "strmrtsp": "Strömmande",
    "text": "Text",
    "texttext": "QuickTime-text",
    "texttx3g": "3GPP-text",
    "tmcd": "Tidskod",
    "tmcdtmcd": "Tidskod",
    "tmet": "Tidmetadata",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Okomprimerad 1-bits indexerad färg",
    "vide2": "Okomprimerad 2-bitars indexerad färg",
    "vide2vuy": "Komponent Y'CbCr 8-bitars 4:2:2 ordnad Cb Y'0 Cr Y'1",
    "vide4": "Okomprimerad 4-bitars indexerad färg",
    "vide8": "Okomprimerad 8-bitars indexerad färg",
    "vide8BPS": "Planar RGB",
    "vide16": "Okomprimerad 16-bitars RGB 555 (stor endian)",
    "vide24": "Okomprimerad 24-bitars RGB",
    "vide24BG": "Okomprimerad 24-bitars BGR",
    "vide32": "Okomprimerad 32-bitars ARGB",
    "vide33": "Okomprimerad 1-bits gråskala",
    "vide34": "Okomprimerad 2-bitars gråskala",
    "vide36": "Okomprimerad 4-bitars gråskala",
    "vide40": "Okomprimerad 8-bitars gråskala",
    "vide5551": "Okomprimerad 16-bitars RGB 5551 (liten endian)",
    "videa2vy": "Tvåplans komponent Y'CbCr,A 8-bitars 4:2:2,4",
    "videABGR": "Okomprimerad 32-bitars ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (parameteruppsättningar i bitströmmen)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Okomprimerad 16-bitars gråskala",
    "videb32a": "Okomprimerad 32-bitars alfagrå",
    "videb48r": "Okomprimerad 48-bitars RGB",
    "videb64a": "Okomprimerad 64-bitars ARGB",
    "videB565": "Okomprimerad 16-bitars RGB 565 (stor endian)",
    "videBGRA": "Okomprimerad 32-bitars BGRA",
    "videbhiv": "bhiv",
    "videblur": "Sammansättningsfilter",
    "videcdh1": "Dolby Vision HEVC (krypterad)",
    "videclou": "Moln",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Övertoning",
    "videdv5n": "DVCPRO50 – NTSC",
    "videdv5p": "DVCPRO50 – PAL",
    "videdvc ": "DV/DVCPRO – NTSC",
    "videdvcp": "DVC – PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO – PAL",
    "videEIDI": "EIDI",
    "videembs": "Sammansättningsfilter",
    "videfire": "Eld",
    "videfmns": "Filmbrusfilter",
    "videgenk": "Sammansättningsfilter",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bitars 4:2:2",
    "videhev1": "HEVC (parameteruppsättningar i bitströmmen)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Foto – JPEG",
    "videJvt3": "Apple H.264/AVC-video (förhandsvisning)",
    "videkpcd": "Photo CD",
    "videL555": "Okomprimerad 16-bitars RGB 555 (liten endian)",
    "videL565": "Okomprimerad 16-bitars RGB 565 (liten endian)",
    "vidematt": "Övertoningssvep",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1-video",
    "videmp2v": "MPEG-2-video",
    "videmp4v": "MPEG-4-video",
    "videmplo": "Implodera",
    "videmuxa": "HEVC med alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mbit/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mbit/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mbit/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mbit/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mbit/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mbit/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Okänt",
    "videpng ": "PNG",
    "videpush": "Knuff",
    "videpxlt": "Apple Pixlet-video",
    "videqdh1": "Dolby Vision HEVC (skyddad, fragmenterad MP4)",
    "vider210": "Okomprimerad 10-bitars RGB",
    "vider408": "Komponent Y'CbCrA 8-bitars 4:4:4:4 ordnad A Y' Cb Cr",
    "videRGBA": "Okomprimerad 32-bitars RGBA",
    "viderle ": "Animering",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Sammansättningsfilter",
    "videslid": "Knuff",
    "videsmc ": "Grafik",
    "videsmpt": "Svep",
    "videsolr": "Färgbalansfilter",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Färgbalansfilter",
    "videtrav": "Rörlig mask",
    "videv210": "Komponent Y'CbCr 10-bitars 4:2:2",
    "videv216": "Komponent Y'CbCr 10,12,14,16-bitars 4:2:2",
    "videv308": "Komponent Y'CbCr 8-bitars 4:4:4",
    "videv408": "Komponent Y'CbCrA 8-bitars 4:4:4:4 ordnad Cb Y' Cr A",
    "videv410": "Komponent Y'CbCr 10-bitars 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bitars",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bitars",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bitars",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bitars",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bitars",
    "videxfia": "XF-AVC Intra 4:2:2 10-bitars",
    "videxplo": "Implodera",
    "videy420": "Treplans komponent Y'CbCr 8-bitars 4:2:0",
    "videyuvs": "Komponent Y'CbCr 8-bitars 4:2:2 ordnad Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
