/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Приховані субтитри",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Підказка",
    "meta": "Метадані",
    "metamebx": "Синхронізовані метадані",
    "musimusi": "Музика",
    "muxx": "Мультиплексний",
    "obje": "Обʼєкт QTVR",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR Panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Субтитр",
    "sbtldrmt": "Субтитр",
    "sbtltx3g": "Субтитр",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Оболонка",
    "skinskcr": "Skin",
    "skinskdr": "Оболонка",
    "soun": "Звук",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (зашифрований)",
    "sounpaac": "AAC (захищене)",
    "sounpac3": "AC-3 Dolby Digital (захищений)",
    "sounpach": "HE-AACv1 (захищений)",
    "sounpacp": "HE-AACv2 (захищений)",
    "sounpc+3": "Dolby Atmos (захищений)",
    "sounpec3": "EC-3 Dolby Digital+ (захищений)",
    "sounqaac": "AAC (захищений, фрагментований MP4)",
    "sounqac3": "AC-3 Dolby Digital (захищений, фрагментований MP4)",
    "sounqach": "HE-AACv1 (захищений, фрагментований MP4)",
    "sounqacp": "HE-AACv2 (захищений, фрагментований MP4)",
    "sounqc+3": "Dolby Atmos (захищений, фрагментований MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (захищений, фрагментований MP4)",
    "sounqlac": "Apple Lossless (захищений, фрагментований MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (захищений, транспортний потік)",
    "sounzac3": "AC-3 Dolby Digital (захищений, транспортний потік)",
    "sounzach": "HE-AACv1 (захищений, транспортний потік)",
    "sounzacp": "HE-AACv2 (захищений, транспортний потік)",
    "sounzc+3": "Dolby Atmos (захищений, транспортний потік)",
    "sounzec3": "EC-3 Dolby Digital+ (захищений, транспортний потік)",
    "sounzlac": "Apple Lossless (захищений, транспортний потік)",
    "sprt": "Спрайт",
    "strm": "Трансляція",
    "strmrtsp": "Трансляція",
    "text": "Текст",
    "texttext": "Текст QuickTime",
    "texttx3g": "Текст 3GPP",
    "tmcd": "Часовий код",
    "tmcdtmcd": "Часовий код",
    "tmet": "Синхронізовані метадані",
    "twen": "Tween",
    "vide": "Відео",
    "vide1": "Кольорове, без компресії, 1‑бітне, індексоване",
    "vide2": "Кольорове, без компресії, 2‑бітне, індексоване",
    "vide2vuy": "Компонентне Y'CbCr, 8‑бітне, 4:2:2, у порядку Cb Y'0 Cr Y'1",
    "vide4": "Кольорове, без компресії, 4‑бітне, індексоване",
    "vide8": "Кольорове, без компресії, 8‑бітне, індексоване",
    "vide8BPS": "Planar RGB",
    "vide16": "RGB 555, без компресії, 16‑бітне (Big Endian)",
    "vide24": "RGB, без компресії, 24‑бітне",
    "vide24BG": "BGR, без компресії, 24‑бітне",
    "vide32": "ARGB, без компресії, 32‑бітне",
    "vide33": "Монохромне, без компресії, 1‑бітне",
    "vide34": "Монохромне, без компресії, 2‑бітне",
    "vide36": "Монохромне, без компресії, 4‑бітне",
    "vide40": "Монохромне, без компресії, 8‑бітне",
    "vide5551": "RGB 5551, без компресії, 16‑бітне (Little Endian)",
    "videa2vy": "Двоплощинне компонентне Y'CbCr,A, 8‑бітне, 4:2:2,4",
    "videABGR": "ABGR, без компресії, 32‑бітне",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (набори параметрів у бітовому потоці)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Монохромне, без компресії, 16‑бітне",
    "videb32a": "AlphaGray, без компресії, 32‑бітне",
    "videb48r": "RGB, без компресії, 48‑бітне",
    "videb64a": "ARGB, без компресії, 64‑бітне",
    "videB565": "RGB 565, без компресії, 16‑бітне (Big Endian)",
    "videBGRA": "BGRA, без компресії, 32‑бітне",
    "videbhiv": "bhiv",
    "videblur": "Фільтр згортання",
    "videcdh1": "Dolby Vision HEVC (зашифрований)",
    "videclou": "Cloud",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0 Media",
    "videdslv": "Монтажний перехід",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO - NTSC",
    "videdvcp": "DVC - PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO - PAL",
    "videEIDI": "EIDI",
    "videembs": "Фільтр згортання",
    "videfire": "Fire",
    "videfmns": "Фільтр «Стара плівка»",
    "videgenk": "Фільтр згортання",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10 біт 4:2:2",
    "videhev1": "HEVC (набори параметрів у бітовому потоці)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™ Video 4.3",
    "videIV50": "Indeo™ video 5.1",
    "videjpeg": "Фото - JPEG",
    "videJvt3": "Apple H.264/AVC Video (передогляд)",
    "videkpcd": "Photo CD",
    "videL555": "RGB 555, без компресії, 16‑бітне (Little Endian)",
    "videL565": "RGB 565, без компресії, 16‑бітне (Little Endian)",
    "vidematt": "Градієнтне стирання",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "Відео MPEG-1",
    "videmp2v": "Відео MPEG-2",
    "videmp4v": "Відео MPEG-4",
    "videmplo": "Поглинання",
    "videmuxa": "HEVC з Alpha",
    "videmx3n": "MPEG IMX 525/60 (30 Мбіт/с)",
    "videmx3p": "MPEG IMX 625/50 (30 Мбіт/с)",
    "videmx4n": "MPEG IMX 525/60 (40 Мбіт/с)",
    "videmx4p": "MPEG IMX 625/50 (40 Мбіт/с)",
    "videmx5n": "MPEG IMX 525/60 (50 Мбіт/с)",
    "videmx5p": "MPEG IMX 625/50 (50 Мбіт/с)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Невідомо",
    "videpng ": "PNG",
    "videpush": "Виштовхування",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (захищений, фрагментований MP4)",
    "vider210": "RGB, без компресії, 10‑бітне",
    "vider408": "Компонентне Y'CbCrA, 8‑бітне, 4:4:4:4, у порядку A Y' Cb Cr",
    "videRGBA": "RGBA, без компресії, 32‑бітне",
    "viderle ": "Анімація",
    "viderpza": "Відео",
    "vides263": "H.263",
    "videshrp": "Фільтр згортання",
    "videslid": "Виштовхування",
    "videsmc ": "Графіка",
    "videsmpt": "Стирання",
    "videsolr": "Фільтр колірного балансу",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Фільтр колірного балансу",
    "videtrav": "Динамічна маска",
    "videv210": "Компонентне Y'CbCr, 10‑бітне, 4:2:2",
    "videv216": "Компонентне Y'CbCr 10,12,14,16‑бітне, 4:2:2",
    "videv308": "Компонентне Y'CbCr, 8‑бітне, 4:4:4",
    "videv408": "Компонентне Y'CbCrA, 8‑бітне, 4:4:4:4, у порядку Cb Y' Cr A",
    "videv410": "Компонентне Y'CbCr, 10‑бітне, 4:4:4",
    "videVP31": "On2 VP3 Video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4, 10‑бітне",
    "videxf4c": "XF-AVC Intra 4:4:4, 12‑бітне",
    "videxfg8": "XF-AVC Long GOP 4:2:2, 8‑бітне",
    "videxfga": "XF-AVC Long GOP 4:2:2, 10‑бітне",
    "videxfi8": "XF-AVC Intra 4:2:2, 8‑бітне",
    "videxfia": "XF-AVC Intra 4:2:2, 10‑бітне",
    "videxplo": "Центрування",
    "videy420": "Триплощинне компонентне Y'CbCr, 8‑бітне, 4:2:0",
    "videyuvs": "Компонентне Y'CbCr, 8‑бітне, 4:2:2, у порядку Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
