/// Generated from MediaAndSubtypes.strings
let MediaAndSubtypes: [String: Any] = [
    "clcp": "Skjult teksting",
    "clcpatcc": "ATSC/52 part-4",
    "clcpc608": "CEA 608",
    "clcpc708": "CEA 708",
    "hintrtp ": "Hint",
    "meta": "Metadata",
    "metamebx": "Tidsbestemt metadata",
    "musimusi": "Musikk",
    "muxx": "Multiplekset",
    "obje": "QTVR-objekt",
    "odsm": "MPEG-4 ODSM",
    "odsmmp4s": "MPEG-4 ODSM",
    "pano": "VR-panorama",
    "qtvr": "QuickTime VR",
    "qtvrqtvr": "QuickTime VR",
    "qtz ": "Quartz Composer",
    "qtz qtz ": "Quartz Composer",
    "sbtl": "Teksting",
    "sbtldrmt": "Teksting",
    "sbtltx3g": "Teksting",
    "sdsm": "MPEG-4 SDSM",
    "sdsmmp4s": "MPEG-4 SDSM",
    "skin": "Skall",
    "skinskcr": "Skall",
    "skinskdr": "Skall",
    "soun": "Lyd",
    "sounalac": "Apple Lossless",
    "sounclac": "Apple Lossless (kryptert)",
    "sounpaac": "AAC-lyd (beskyttet)",
    "sounpac3": "AC-3 Dolby Digital (beskyttet)",
    "sounpach": "HE-AACv1 (beskyttet)",
    "sounpacp": "HE-AACv2 (beskyttet)",
    "sounpc+3": "Dolby Atmos (beskyttet)",
    "sounpec3": "EC-3 Dolby Digital+ (beskyttet)",
    "sounqaac": "AAC (beskyttet, fragmentert MP4)",
    "sounqac3": "AC-3 Dolby Digital (beskyttet, fragmentert MP4)",
    "sounqach": "HE-AACv1 (beskyttet, fragmentert MP4)",
    "sounqacp": "HE-AACv2 (beskyttet, fragmentert MP4)",
    "sounqc+3": "Dolby Atmos (beskyttet, fragmentert MP4)",
    "sounqec3": "EC-3 Dolby Digital+ (beskyttet, fragmentert MP4)",
    "sounqlac": "Apple Lossless (beskyttet, fragmentert MP4)",
    "sounvdva": "DV",
    "sounzaac": "AAC (beskyttet, transportstrøm)",
    "sounzac3": "AC-3 Dolby Digital (beskyttet, transportstrøm)",
    "sounzach": "HE-AACv1 (beskyttet, transportstrøm)",
    "sounzacp": "HE-AACv2 (beskyttet, transportstrøm)",
    "sounzc+3": "Dolby Atmos (beskyttet, transportstrøm)",
    "sounzec3": "EC-3 Dolby Digital+ (beskyttet, transportstrøm)",
    "sounzlac": "Apple Lossless (beskyttet, transportstrøm)",
    "sprt": "Sprite",
    "strm": "Strømming",
    "strmrtsp": "Strømming",
    "text": "Tekst",
    "texttext": "QuickTime-tekst",
    "texttx3g": "3GPP-tekst",
    "tmcd": "Tidskode",
    "tmcdtmcd": "Tidskode",
    "tmet": "Tidsbestemt metadata",
    "twen": "Tween",
    "vide": "Video",
    "vide1": "Ukomprimert 1-bit indeksert farge",
    "vide2": "Ukomprimert 2-bit indeksert farge",
    "vide2vuy": "Komponent Y'CbCr 8-bit 4:2:2 i rekkefølgen Cb Y'0 Cr Y'1",
    "vide4": "Ukomprimert 4-bit indeksert farge",
    "vide8": "Ukomprimert 8-bit indeksert farge",
    "vide8BPS": "Planar RGB",
    "vide16": "Ukomprimert 16-bit RGB 555 (Big Endian)",
    "vide24": "Ukomprimert 24-bit RGB",
    "vide24BG": "Ukomprimert 24-bit BGR",
    "vide32": "Ukomprimert 32-bit ARGB",
    "vide33": "Ukomprimert 1-bit gråtone",
    "vide34": "Ukomprimert 2-bit gråtone",
    "vide36": "Ukomprimert 4-bit gråtone",
    "vide40": "Ukomprimert 8-bit gråtone",
    "vide5551": "Ukomprimert 16-bit RGB 5551 (Little Endian)",
    "videa2vy": "Toplans komponent Y'CbCr,A 8-bit 4:2:2,4",
    "videABGR": "Ukomprimert 32-bit ABGR",
    "videACTL": "Streambox ACT-L2",
    "videai1p": "AVC-Intra 100 720p60/30/24",
    "videai1q": "AVC-Intra 100 720p50/25",
    "videai2p": "AVC-Intra 200 720p60/30/24",
    "videai2q": "AVC-Intra 200 720p50/25",
    "videai5p": "AVC-Intra 50 720p60/30/24",
    "videai5q": "AVC-Intra 50 720p50/25",
    "videai12": "AVC-Intra 100 1080p50/25",
    "videai13": "AVC-Intra 100 1080p60/30/24",
    "videai15": "AVC-Intra 100 1080i50",
    "videai16": "AVC-Intra 100 1080i60",
    "videai22": "AVC-Intra 200 1080p50/25",
    "videai23": "AVC-Intra 200 1080p60/30/24",
    "videai25": "AVC-Intra 200 1080i50",
    "videai26": "AVC-Intra 200 1080i60",
    "videai42": "AVC-Intra 4:2:2",
    "videai44": "AVC-Intra 4:4:4",
    "videai52": "AVC-Intra 50 1080p50/25",
    "videai53": "AVC-Intra 50 1080p60/30/24",
    "videai55": "AVC-Intra 50 1080i50",
    "videai56": "AVC-Intra 50 1080i60",
    "videailt": "AVC-Intra LT",
    "videaivx": "XAVC Intra",
    "videap4h": "Apple ProRes 4444",
    "videap4x": "Apple ProRes 4444 XQ",
    "videapch": "Apple ProRes 422 HQ",
    "videapcn": "Apple ProRes 422",
    "videapco": "Apple ProRes 422 Proxy",
    "videapcs": "Apple ProRes 422 LT",
    "videaprh": "Apple ProRes RAW HQ",
    "videaprn": "Apple ProRes RAW",
    "videavc1": "H.264",
    "videavc3": "H.264 (parametersett i bitstrøm)",
    "videAVdh": "Avid DNxHR",
    "videAVdn": "Avid DNxHD",
    "videavlg": "AVC-LongG",
    "videavr ": "Motion JPEG AVR",
    "videb16g": "Ukomprimert 16-bit gråtone",
    "videb32a": "Ukomprimert 32-bit AlphaGray",
    "videb48r": "Ukomprimert 48-bit RGB",
    "videb64a": "Ukomprimert 64-bit ARGB",
    "videB565": "Ukomprimert 16-bit RGB 565 (Big Endian)",
    "videBGRA": "Ukomprimert 32-bit BGRA",
    "videbhiv": "bhiv",
    "videblur": "Convolution-filter",
    "videcdh1": "Dolby Vision HEVC (kryptert)",
    "videclou": "Sky",
    "videcvid": "Cinepak",
    "videdmb1": "Motion JPEG OpenDML",
    "videdrmi": "AVC0-medium",
    "videdslv": "Kryssuttoning",
    "videdv5n": "DVCPRO50 - NTSC",
    "videdv5p": "DVCPRO50 - PAL",
    "videdvc ": "DV/DVCPRO – NTSC",
    "videdvcp": "DVC – PAL",
    "videdvh1": "Dolby Vision HEVC",
    "videdvh2": "DVCPRO HD (1080p25)",
    "videdvh3": "DVCPRO HD (1080p30)",
    "videdvh5": "DVCPRO HD (1080i50)",
    "videdvh6": "DVCPRO HD (1080i60)",
    "videdvhp": "DVCPRO HD (720p60)",
    "videdvhq": "DVCPRO HD (720p50)",
    "videdvpp": "DVCPRO – PAL",
    "videEIDI": "EIDI",
    "videembs": "Convolution-filter",
    "videfire": "Fire",
    "videfmns": "Filmstøyfilter",
    "videgenk": "Convolution-filter",
    "videgif ": "GIF",
    "videh261": "H.261",
    "videh263": "H.263",
    "videhe22": "HEVC 10-bit 4:2:2",
    "videhev1": "HEVC (parametersett i bitstrøm)",
    "videhvc1": "HEVC",
    "videicod": "Apple Intermediate Codec",
    "videIV41": "Intel Indeo™-video 4.3",
    "videIV50": "Indeo™-video 5.1",
    "videjpeg": "Foto - JPEG",
    "videJvt3": "Apple H.264/AVC-video (forhåndsvisning)",
    "videkpcd": "Photo CD",
    "videL555": "Ukomprimert 16-bit RGB 555 (Little Endian)",
    "videL565": "Ukomprimert 16-bit RGB 565 (Little Endian)",
    "vidematt": "Forløpningsutvisking",
    "videmjp2": "JPEG 2000",
    "videmjpa": "Motion JPEG A",
    "videmjpb": "Motion JPEG B",
    "videmp1v": "MPEG-1-video",
    "videmp2v": "MPEG-2-video",
    "videmp4v": "MPEG-4-video",
    "videmplo": "Sammentrekning",
    "videmuxa": "HEVC med alfa",
    "videmx3n": "MPEG IMX 525/60 (30 Mb/s)",
    "videmx3p": "MPEG IMX 625/50 (30 Mb/s)",
    "videmx4n": "MPEG IMX 525/60 (40 Mb/s)",
    "videmx4p": "MPEG IMX 625/50 (40 Mb/s)",
    "videmx5n": "MPEG IMX 525/60 (50 Mb/s)",
    "videmx5p": "MPEG IMX 625/50 (50 Mb/s)",
    "VideoDynamicRangeDolbyVision": "Dolby Vision 5",
    "VideoDynamicRangeDolbyVision8p4": "Dolby Vision 8.4",
    "VideoDynamicRangeHDR10": "HDR10",
    "VideoDynamicRangeHLG": "HLG",
    "VideoDynamicRangeSDR": "SDR",
    "VideoDynamicRangeUnknown": "Ukjent",
    "videpng ": "PNG",
    "videpush": "Push",
    "videpxlt": "Apple Pixlet Video",
    "videqdh1": "Dolby Vision HEVC (beskyttet, fragmentert MP4)",
    "vider210": "Ukomprimert 10-bit RGB",
    "vider408": "Komponent Y'CbCrA 8-bit 4:4:4:4 i rekkefølgen A Y' Cb Cr",
    "videRGBA": "Ukomprimert 32-bit RGBA",
    "viderle ": "Animasjon",
    "viderpza": "Video",
    "vides263": "H.263",
    "videshrp": "Convolution-filter",
    "videslid": "Push",
    "videsmc ": "Grafikk",
    "videsmpt": "Visk ut",
    "videsolr": "Fargebalansefilter",
    "videSVQ1": "Sorenson Video",
    "videSVQ3": "Sorenson Video 3",
    "videtiff": "TIFF",
    "videtint": "Fargebalansefilter",
    "videtrav": "Bevegelig kanalmaske",
    "videv210": "Komponent Y'CbCr 10-bit 4:2:2",
    "videv216": "Komponent Y'CbCr 10,12,14,16-bit 4:2:2",
    "videv308": "Komponent Y'CbCr 8-bit 4:4:4",
    "videv408": "Komponent Y'CbCrA 8-bit 4:4:4:4 i rekkefølgen Cb Y' Cr A",
    "videv410": "Komponent Y'CbCr 10-bit 4:4:4",
    "videVP31": "On2 VP3-video 3.2",
    "videxalg": "XAVC Long GOP",
    "videxf4a": "XF-AVC Intra 4:4:4 10-bit",
    "videxf4c": "XF-AVC Intra 4:4:4 12-bit",
    "videxfg8": "XF-AVC Long GOP 4:2:2 8-bit",
    "videxfga": "XF-AVC Long GOP 4:2:2 10-bit",
    "videxfi8": "XF-AVC Intra 4:2:2 8-bit",
    "videxfia": "XF-AVC Intra 4:2:2 10-bit",
    "videxplo": "Sammentrekning",
    "videy420": "Treplans komponent Y'CbCr 8-bit 4:2:0",
    "videyuvs": "Komponent Y'CbCr 8-bit 4:2:2 i rekkefølgen Y'0 Cb Y'1 Cr",
    "videzygo": "ZyGoVideo",
]
